### ISSUE TITLE
Plugin does not detect existing git

### ISSUE THREAD

**Issue by CineTek** [github-for-unity/Unity#1004]
Hi, I am running into an issue when trying to setup our repo on anyone's PC other than mine...

The project repository existed outside of Github for Unity for a while and my git structure is as follows:

ProjectName/Game/Assets/etc
On GitHub, everything is fine and in my local instance as well (I added the Github plugin!)
But whenever anyone wants to download the repository then for some reason the plugin wants to initialize a new repo and does not let us add a remote branch first! So the user is forced to make a commit and then the plugin tries to create a new repo apparently

Our project flow to reproduce is as follows:
1. Developer downloads repo from GitHub
2. Opens up Unity3D
3. Github plugin gets initialized
4. GitHub plugin fails to find existing git structure apparently
5. Prompts to commit every single file

**Comment by StanleyGoldman** [comment]
Hey @CineTek 
Sorry it's taken so long to get back to you. Been 🤹‍♂️ a few different things at the same time.

Okay, I've heard people make this mistake before, so it's not your fault. At this point GitHub for Unity does not have support for cloning projects. It can only initialize them so you will have to work a bit differently to clone them to another machine.

The easiest steps can be found here: [getting-started.md#cloning-an-existing-repository](https://github.com/github-for-unity/Unity/blob/master/docs/using/getting-started.md#cloning-an-existing-repository)

I'm going to close this issue, but feel free to re-open it if you have additional questions.
