### ISSUE TITLE
Detect files to track in LFS due to size

### ISSUE THREAD

**Issue by francisco-chavez** [github-for-unity/Unity#1005]
#### Problem:
1. Files that are not tracked in LFS may grow over time to be over 500MB.
1. Users might attempt to commit files that are larger than 500MB.

Both scenarios result in a situation where the user cannot push to GitHub.

#### Solution:
1. Detect files that are not tracked and greater than 500MB.
1. Warn users about the scenario and prompt to automatically resolve.
1. Add the file to be tracked by LFS
1. If the file has history, run command to convert history to LFS

##### Original issue from @francisco-chavez:
> ### Description
> 
> 
> 
> ### Steps to Reproduce
> 
> 1. Add a lot of lights to a scene.
> 2. Have a bunch of static items in the scene
> 3. Let Unity bake the lightmaps for 19 hours
> 4. Have a resulting LightingData.asset file that's about 500 MB in size.
> 5. Commit LightingData.asset.
> 6. Spend 2 hours undoing and redoing commits as you try to figure out a way around the 100 MB size limit for non-LFS files.
> 
> **Expected behavior:** I expect all files (except the meta files) inside the baked lighting folder to be managed by LFS because they're either binary files or image files.
> 
> **Actual behavior:** The binary file LightingData.asset is as something else, and my pushes get rejected. Not only do the pushes get rejected, I don't even get any feedback as to why. I had to open a different program to find out that this commit contained a file that violated the 100 MB limit.
> 
> **Reproduces how often:** Everytime a file that's over 100 MBs that isn't assoicated with the rules you've put in place for the LFS system. I should add, you forgot to associate EXR image files with LFS. Unity generates that image file type when doing lightmap baking, so it would be a good idea to add it to the LFS system.
> 
> ### Additional Information
> 
> Any additional information, configuration or data that might be necessary to reproduce the issue.
>

**Comment by StanleyGoldman** [comment]
Hey @francisco-chavez 
Sorry it's taken so long to get back to you. I've been 🤹‍♂️ a few different things at once.

So yea, you hit a few different troubles with the git database limit, and the errors that come back from the server are not always apparent. But it seems like you've resolved your issues.

I have a few questions:
- Did you initialize the repo/project with GitHub for Unity?
  - If so, what version of GitHub for Unity did you do it with?
- What did you have in your `.gitattributes` file for `*.asset` files?
  - What do you have now?

**Comment by StanleyGoldman** [comment]
Also, I've been talking to @shana and doing a bit more research...
The problem is a bit more nuanced than that...

https://github.com/github-for-unity/Unity/blob/35f80df7097d1f650360dfeed7df157a3228d6db/src/GitHub.Api/Resources/.gitattributes#L4-L6

We generally don't track `.asset` files in LFS. They are text files, and for most of the beginning of your project they will be far under 500MB. Over the course of your project, you've crossed that 500MB threshold.

So what we need is functionality to detect files that are over 500MB and untracked. It could then prompt the user about the scenario, and automatically track the file and convert it with the appropriate git commands.

**Comment by StanleyGoldman** [comment]
I updated the issue to be a feature. Sorry you had to figure this out the hard way.

**Comment by francisco-chavez** [comment]
I did an update to the latest released version  of the GitHub plugin for Unity from the Unity Asset Store the day before submitting the ticket. When I created the project, one of the first things I did was install the plugin from the asset store. As for the issue itself, I never actually resolved it; I just gave up on committing the light-maps and deleted them. I did try copying the lfs settings in .gitattributes that were for images and used them for the *.asset files, but that didn't work. So, my resolution was to play with the lightmap bake settings until the generated file was below the file size limit.

-Francisco


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by francisco-chavez** [comment]
Sorry, I guess I wasn't clear one of the details. The Unity Project I was working on is a conversion of a finished project that wasn't fully compatible with Unity. The file size limit that I hit is 100 MB, but the file that I created was a bit over 500 MB. That being said, any text file that's anywhere close 100 MB is probably not something meant to be read by humans. I mean, there are some fairly large books that are measured in the tens of KB when stored as an uncompressed text file; I know this because a few years back, I was comparing adaptive huffman encoding to zip-file compression with Romeo & Juliet as my base text file. Unless they have images or something encoded in them, human readable files should be well under 1 MB. The *.asset files may be text files, but that's only because we're setting the serialization settings in Unity to enforce text encoding to increase compatibility with Git.

Thanks for your help on this,
-Francisco


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by 40detectives** [comment]
There are some _.asset_ files that are not text. Please, look at some terrain assets, as well as LightingData.asset to check for yourselves. Ideally, we should get **Gihub for Unity** to check if _*.asset_ files are binary or not.

**Comment by davl3232** [comment]
Following what @40detectives said, covering each file type possible at the generated .gitattributes could be impossible. I found one file type supported by Unity that's missing from the .gitattributes, EXR files. There could be more.

Also there are projects that use uncommon file types that are not understood by Unity out of the box and are used by scripts and Unity Store packages.

Even if you could add those to the .gitattributes yourself, it would be a big hassle to look at inner workings of third party packages in some projects.

I believe implementing the file size detection could solve this.

**Comment by francisco-chavez** [comment]
Out of curiosity, are there any *.asset files that are text? 

I'm not talking about files that contain text because the serialization settings in the project have been set to text so that git can do a proper diff. I'm talking about text files that were actually meant to contain text that's meant to be read by humans. I haven't looked at too many *.asset files, but the few that I did look contained serialized data that's been formatted to text in such a way that the diff system used by git won't replace the entire file every time there's a tiny change (which is git's default behavior for binary files that aren't integrated with LFS).

With that run-on sentence out of the way, I'm back  to my question. Does Unity contain any *.asset files that actually are text?

**Comment by davl3232** [comment]
I just checked. Animations, post-processing profiles and scenes are YAML files.

**Comment by francisco-chavez** [comment]
@davl3232 , did you set your serialization setting to "Mixed" before looking at this? Also, if you do this, you might, might, need to make a small change to a scene and save it before Unity actually starts changing things over to another serialization; you may also need to restart Unity and then reopen the project. I've noticed that Unity doesn't always carry out the changes made to a project's setting right away. I know this from personal experience, and it wasn't a fun thing to learn.

All the Unity projects I make nowadays have serialization set to "Text" by default. With previous versions of Unity, I would need to change the serialization over to "Text" for projects I was planning to store in a git repo. I've seen Unity Scene files that are serialized to binary, and the diff systems that come with git will tell you that they can't be diff'ed. 

YAML isn't a bad way to turn binary data into something that can be read by a human, but even then, not all of that the information is understandable to humans without a really good understanding of every system that's in play. 

I looked at a post-processing profile after reading your replay. Some parts were very readable, and some parts weren't. At one point in the file, it was line after line of "0.5". I'm guessing it was an array (or list) of some kind. The same thing goes with scenes. If I run a diff to a scene that's been serialized to YAML, and I remember the changes I made to the scene, then most of the stuff that shows up in the diff window is understandable, but not always all of it. Due to the limits in how git handles binary files, YAML is great for small stuff like Settings files, but because of YAML and Text serialization, there are plenty of files in Unity that aren't meant to be read by humans without a specialized editor of some kind. So, yeah, with the exception of well known file types, using a file size (and perhaps location) might be the best way to solve what items go into LFS.

**Comment by Cdddo** [comment]
The ability to automatically detect and track large files would be great. This is common with lighting data. Also working with CAD data sometimes I end up with _prefabs_ that are easily over 100 MB.

This could be the cause of why sometimes when initializing github on a pre-existing project leads to problems with not showing anything on the changes window, and not being able to push, and being forced to use Desktop as a workaround.
