### ISSUE TITLE
Option to disable UpdateCheck

### ISSUE THREAD

**Issue by sambonfire** [github-for-unity/Unity#1010]
### Prerequisites

Unity
Out of date github for unity plugin

### Description

When launching Unity, the github plugin checks if it is out of date, and if so it prompts the user to upgrade with a popup window.

There are a couple of issues with this:
1. This popup is displayed even when we run Unity in headless mode (for example, when we want to generate a build)
2. We don't want artists to ever accidentally click that button and do the upgrade themselves

Ideally, we would just like a version of the UpdateCheck that would just write a warning to the console to let us know if the plugin is out of date, or else just disable the update check completely (we are happy to do it manually).

### Steps to Reproduce

1. Install an old version of the github for unity plugin
2. launch unity
3. notice the popup window prompting you to upgrade

**Expected behavior:**

Ideally, we'd like an option to change this to just disable it completely or to just log to the console.

**Actual behavior:**

There is currently no way to disable this window that I'm aware of.

**Reproduces how often:**

100%

### Additional Information

none

**Comment by StanleyGoldman** [comment]
I have to look more into the update check. I vaguely remember that the setting is stored in either the users local or remote profile. It makes sense that you would want to disable it at a repository level.

In regards to your builds, you are going to need a bit more than that. If you set the environment variable `GITHUB_UNITY_DISABLE`. It will prevent the plugin from loading at all.

https://github.com/github-for-unity/Unity/blob/2b41d4bb52a2d875cca749d6a9b31e21a5fd8544/src/UnityExtension/Assets/Editor/GitHub.Unity/ExtensionLoader/ExtensionLoader.cs#L33-L34
