### ISSUE TITLE
GitHub for Unity won't unlock my files

### ISSUE THREAD

**Issue by Ecnassianer** [github-for-unity/Unity#1012]
### Description

When I try to lock a file it works and other people can see my locks. When I go back to release a lock, the option is grayed out. Clicking it does nothing. I can however use git lfs unlock to release the lock on that file.

I've only started using Git LFS and Github for Unity, so I might be misconfigured somehow.

### Steps to Reproduce

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** 100%

### Additional Information
[github-unity.log](https://github.com/github-for-unity/Unity/files/2819791/github-unity.log)

**Comment by StanleyGoldman** [comment]
Hmm... Well this is odd..

```
190131-18:10:26.714  INFO [ 1] <Global>                            Initializing GitHubForUnity:'v1.2.1' Unity:'v2018.3.0f2'
190131-18:10:28.891 ERROR [24] <SystemSettings>                    SaveToCache Error
System.UnauthorizedAccessException: Access to the path "C:\ProgramData\GitHubUnity\systemsettings.json" is denied.
```

**Comment by StanleyGoldman** [comment]
What files do you have in `C:\ProgramData\GitHubUnity\` if any?

**Comment by Ecnassianer** [comment]
![image](https://user-images.githubusercontent.com/231247/52151085-bcd1f580-2626-11e9-8d3b-263f31eb86c0.png)

**Comment by Ecnassianer** [comment]
That json file contains this:

{"GitInstallationState":{"GitIsValid":true,"GitLfsIsValid":true,"GitZipExists":true,"GitLfsZipExists":true,"GitInstallationPath":"C:\\Users\\MY_USERNAME\\AppData\\Local\\GitHubUnity\\git","GitExecutablePath":"C:\\Users\\MY_USERNAME\\AppData\\Local\\GitHubUnity\\git\\cmd\\git.exe","GitLfsInstallationPath":"C:\\Users\\MY_USERNAME\\AppData\\Local\\GitHubUnity\\git-lfs","GitLfsExecutablePath":"C:\\Users\\MY_USERNAME\\AppData\\Local\\GitHubUnity\\git-lfs\\git-lfs.exe","GitPackage":{"Md5":"58ee14cb4ce8767167db64b271a0a599","Url":"http://ghfvs-installer.github.com/unity/git/windows/git.zip","ReleaseNotes":null,"ReleaseNotesUrl":null,"Message":null},"GitLfsPackage":{"Md5":"78ff68661485e1c09f7b8d82c4317ab5","Url":"http://ghfvs-installer.github.com/unity/git/windows/git-lfs.zip","ReleaseNotes":null,"ReleaseNotesUrl":null,"Message":null},"GitLastCheckTime":"2018-10-31T22:24:26.869+00:00","IsCustomGitPath":false,"GitVersion":{"Version":"2.17.0.windows.1"},"GitLfsVersion":{"Version":"2.4.0"}}}

**Comment by StanleyGoldman** [comment]
I take it usernames have been changed to protect the innocent.. 😄 

So hmm, all that looks right. But why would you no longer be able to write to the file, has something changed on your system?

**Comment by Ecnassianer** [comment]
No idea. I can't save over that file with visual studio's json editor either.

**Comment by Ecnassianer** [comment]
I tried to delete the JSON file and it asked for Administrator access. I said yes and it deleted.

Ok wild theory time.

My account got deactivated. Then a new account got created with the same username. That file may have been created by the previous account, so I didn't have permission to write to it. I opened a closed Unity and the plugin wrote a new copy of the file.

**Comment by Ecnassianer** [comment]
I locked a file and tried to release it again and my log file is just this:
190201-13:51:38.972  INFO [ 1] <Global>                            Initializing GitHubForUnity:'v1.2.1' Unity:'v2018.3.0f2'

**Comment by Ecnassianer** [comment]
Hey, this one is better
[github-unity.log](https://github.com/github-for-unity/Unity/files/2823511/github-unity.log)
