### ISSUE TITLE
If index.lock already exists, a reasonable error message is not displayed to the user

### ISSUE THREAD

**Issue by sambonfire** [github-for-unity/Unity#1013]
### Prerequisites

You must have a .git/index.lock file that exists

### Description

I noticed that an artist was having trouble with the plugin.  The issue he reported to me was that he was trying to commit changes but it wasn't working.

I looked at his computer, and sure enough, he had files selected, had entered a good description, and when he hit the "commit to master" button nothing seemed to happen.  We checked the console for any error logs but nothing was there.

Going to the command line, we tried to manually commit, and received this error message:

```
fatal: Unable to create 'D:/XXX/.git/index.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
```

In this case, we just had to force remove the file, and then the plugin started working again.

As this is a reasonable error, it would just be nice if this could be surfaced to the user in some way.

### Steps to Reproduce

1. Make sure the .git/index.lock file exists
2. Try to commit a change to master

**Expected behavior:**  An error message would be raised

**Actual behavior:** The error is silently ignored.

**Reproduces how often:** 100%

### Additional Information

none

**Comment by StanleyGoldman** [comment]
Yep, this makes sense.

**Comment by vadimgrig** [comment]
rm .git/index.lock

**Comment by khokharhimanshu** [comment]
simply go to the your project file than search the  .git/index.lock file .if the file is exist then delete it your error was solve .
my error was solve that way .

**Comment by Aongkon** [comment]
how to solve this
