### ISSUE TITLE
Error importing package in Unity

### ISSUE THREAD

**Issue by ejgutierrez74** [github-for-unity/Unity#1018]
I cant install latest package of github for unity:

I downloaded the latest version 1.2.1 and import as a custom package, i select to imort all the files but this message arises for every file.

Copying Temp/Export Package/48eb153816693401397241b99e75328a/d516f2a1bec6a9645a084ef8c9237132/asset to Assets\Plugins\GitHub\Editor\AsyncBridge.Net35.dll: 

Im on unity 2017.4.21 and Ubuntu 18.04

Thanks

**Comment by DouglasUrner** [comment]
This also happens on the macOS 10.14.3 beta.

**Comment by StanleyGoldman** [comment]
@ejgutierrez74 This is related to the Ubuntu issues as I mentioned in the other issue you created.

https://github.com/github-for-unity/Unity/issues/1015

@DouglasUrner If you can send over a log file. I would appreciate it.

**Comment by ejgutierrez74** [comment]
@StanleyGoldman dont know if its the same issue, probably is different.... This one was that if you download the package and want to import it in your project, it gets the error said in the first post.

This is the first step to unity github to work, if its not installed / import it cant work ;)

The other error is a second step, once installed ( imported in your project), you configure your account and the remote repository, but it doesnt work as expected with the log attached.

Perhaps the bug, error has the same root, but from outside seem different. If you consider there is the same error close this issue. 

Thansk

**Comment by dilas12345** [comment]
I am having similar issue, this time around in my case i can't get my packages, say "There are no packages" and at the bottom it says "Error refreshing packages". And I am working on Ubuntu OS
