### ISSUE TITLE
GitHub for Unity should save chosen portable git

### ISSUE THREAD

**Issue by StanleyGoldman** [github-for-unity/Unity#102]
As mentioned by user @mbbmbbmm [here](https://github.com/github-for-unity/Unity/issues/75#issuecomment-313960762), GitHub for Unity does not retain the chosen portable git between runs.

**Comment by mbbmbbmm** [comment]
When I start a new session the github-unity.log only says 

170710-14:30:17  INFO [ 1] <Global>                            Initializing GitHub for Unity version 0.15.0.0

I haven't much more info here, only that the issue exists on both of my computers (one win10 PC, one win7 Notebook, both Unity 5.6.1 and newest Git)

**Comment by StanleyGoldman** [comment]
Hey @mbbmbbmm the log will show a lot more if you Enable Trace Logging.

![](http://i.imgur.com/1YuXhUC.png)

See if you can capture logs of when you set the git installation and when you startup.
I will also try to reproduce the error soon.

**Comment by mbbmbbmm** [comment]
Will do!

**Comment by mbbmbbmm** [comment]
So here's the log from opening the project and assigning the correct install:
[github-unity.log.txt](https://github.com/github-for-unity/Unity/files/1137923/github-unity.log.txt)
And after reopening the project:
[github-unity.log2.txt](https://github.com/github-for-unity/Unity/files/1137979/github-unity.log2.txt)

One thing I found is that when I chose my install manually the exe is not shown. It seems there are two "." before the exe?
![cantfindgitexe](https://user-images.githubusercontent.com/12198715/28055616-103d6638-661a-11e7-9720-d74760a82534.png)

Only when I chose "All files" the git.exe is shown.
![gitexefoundasallfiles](https://user-images.githubusercontent.com/12198715/28055634-1abcab50-661a-11e7-88f8-373287b7cc39.png)

**Comment by StanleyGoldman** [comment]
Another 🐛 found. You are on a roll!
