### ISSUE TITLE
Error ubuntu 18.04 cant push to remote

### ISSUE THREAD

**Issue by ejgutierrez74** [github-for-unity/Unity#1020]
### Description
I have unity project.
I downloaded and imported Github for unity 1.2.1
I have a repository in github ( empty already created=.
Set the remote repository as:  https://github.com/ejgutierrez74/tfmEduardoCode2017
It should began to update local and remote repository ( sync), nothing happens.
If i want to push all files error arisss:

error: src refspec master does not match any.
error: fallo el push de algunas referencias a 'https://github.com/ejgutierrez74/tfmEduardoCode2017'

Gets stuck and i can do it anything else...
If i got to changes: it doesnt detect any changes in local

![imagen](https://user-images.githubusercontent.com/11474846/53304466-d1945880-3875-11e9-9f14-10e9552edbc6.png)

![imagen](https://user-images.githubusercontent.com/11474846/53304477-04d6e780-3876-11e9-8d79-3964fc655fe3.png)

[github-unity.log](https://github.com/github-for-unity/Unity/files/2898324/github-unity.log)

**Comment by StanleyGoldman** [comment]
Hey @ejgutierrez74 there are currently issues running GitHub for Unity on Ubuntu.
You can follow up here for more details.

https://github.com/github-for-unity/Unity/issues/1015.
