### ISSUE TITLE
Post-import package conflict

### ISSUE THREAD

**Issue by zhenzhu143321** [github-for-unity/Unity#1023]
Library\PackageCache\com.unity.mathematics@0.0.12-preview.20\Unity.Mathematics.Editor\PostNormalizedVectorDrawer.cs(28,22): error CS0433: The type 'IReadOnlyList<T>' exists in both 'ReadOnlyCollectionsInterfaces, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' and 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'

**Comment by zhenzhu143321** [comment]
After removing the ECS package and reloading the ECS package, the conflict is gone.

**Comment by StanleyGoldman** [comment]
So it sounds like everything is working now, so I'm going to close this issue.

Were you also switching between the 3.5 and 4.0 profiles?
We only ship IReadOnlyInterfaces for the 3.5 profile, but I believe this particular ECS stuff is 4.0 only.
So it seems like a race condition or other weirdness.

**Comment by shana** [comment]
We've had another user with the same issue, and they didn't switch profiles. All the other DLLs were properly disabled, only the `IReadOnlyCollectionInterfaces` dll was enabled (and it shouldn't be)

**Comment by shana** [comment]
We've had another user with the same issue, and they didn't switch profiles. All the other DLLs were properly disabled, only the `IReadOnlyCollectionInterfaces` dll was enabled (and it shouldn't be). Something is fishy.

**Comment by jaspercayne** [comment]
I just got hit with this too. Only once I removed Entities to reinstall it the package manager no longer shows Entities or Mathematics now... But I still have the Hybrid Renderer installed? Checking my manifest.json confirms this too, Unity somehow removed dependencies without removing the Renderer package and I have no idea how to fix this one.

**Comment by bjporter** [comment]
Also got this.

3 Entities package errors like this:
Library\PackageCache\com.unity.entities@0.0.12-preview.29\Unity.Entities\Injection\InjectionHook.cs(95,25): error CS0433: The type 'IReadOnlyCollection<T>' exists in both 'ReadOnlyCollectionsInterfaces, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' and 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'

and 1 Mathematics package error:
Library\PackageCache\com.unity.mathematics@1.0.0-preview.1\Unity.Mathematics.Editor\PostNormalizedVectorDrawer.cs(28,22): error CS0433: The type 'IReadOnlyList<T>' exists in both 'ReadOnlyCollectionsInterfaces, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' and 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'

Removing these packages fixes the problem. Unity version is 2019.2.0a9

**Comment by bjporter** [comment]
My apologies, it looks like this was fixed in 1.3.0

I didn't realize the Unity Asset Store version was so far behind (version 1.2.1)

**Comment by shana** [comment]
The asset store package has been updated, so this should be good now.
