### ISSUE TITLE
need loading bar or progress percentage

### ISSUE THREAD

**Issue by afshinunity** [github-for-unity/Unity#1024]
first of all thanks for developing this beautiful package.
we all know that git in command line has progress bar that show the progress percentage of commits or pushes, pulls etc...why it isn't in github for unity ui? sometimes it took 1 minute to suddenly show me the push success MessageBox, sometimes 7 minutes later shows up suddenly.
we need to know excatly where we are.
i'm using version 1.2.1 with unity 2018.2

**Comment by StanleyGoldman** [comment]
Thanks for using our stuff.

Your request makes sense, but i don't know how easy it will be.
There are already some bugs in the wild (#871) that involve calling git and are a challenge to solve.

We accept pull requests and I will be glad to help you if you get stuck.

**Comment by afshinunity** [comment]
@StanleyGoldman 
thanks for your support.
actually you can help me in something. what is the proper way of updating github for unity plugin?
since our project is big and we're close to the release date, i'm not sure about hitting the update to new version button and facing with issues after that.
is that safe to update? what is the proper steps of updating github for unity plugin?

**Comment by afshinunity** [comment]
@StanleyGoldman 
hi Stanley. i assume you didn't see my previous comment. so i mentioned you again. please tell me something about it or show us documentation link if there is... regards.

**Comment by StanleyGoldman** [comment]
Hey @afshinunity. Sorry, i missed your message.
You have two options:
1. Open the new `unitypackage` with your Unity project open. It should offer to replace the files.
2. With your Unity project closed, delete the files for GitHub for Unity. Open the project, open the new `unitypackage`.

After both steps you will have to commit the files and push. After that you should be good.

**Comment by Cdddo** [comment]
Please it would be great to have some progress indicator. I've been adding GitHub to a group of old projects and the initial commit of many thousands of files takes quite some time and there isn't even an activity indicator in the github window, just everything greyed out. Had to look in the task manager to see that git was still working and nothing had gone unresponsive.
