### ISSUE TITLE
add .cubemap files to lfs

### ISSUE THREAD

**Issue by naam00** [github-for-unity/Unity#1025]
Because it's impossible to push a commit that has a non-lfs filetype larger than 100MB in it, please have .cubemap files be included -- these regularly grow larger than that.

Conversely, maybe add an option to delete a specific (local) commit, so we can fix the lfs assignment and re-commit.

**Comment by JohnKavanagh1050** [comment]
Has .cubemap been added to github lfs? I'm having size issues with this file type and I've added it to .gitattributes but still wont push..

**Comment by shana** [comment]
@JohnKavanagh1050 No, the default file doesn't have it. If you've added it to the .gitattributes file, it will only apply on files added after you apply it, so if you had already committed a cubemap file before you added the extension to the .gitattributes file, it's not tracked by lfs. If you can't push, you can migrate the local files to lfs by following https://github.com/git-lfs/git-lfs/wiki/Tutorial#migrating-existing-repository-data-to-lfs, and then you should be able to push.

**Comment by JohnKavanagh1050** [comment]
Thank you! I managed to add .cubemap to my git lfs and its all pushing to
github fine now.

regards,
John Kavanagh
