### ISSUE TITLE
Cannot Push first commit to Remote

### ISSUE THREAD

**Issue by pnkflydgr** [github-for-unity/Unity#1028]
I created a repository from the Unity editor successfully.  It initially created an empty Assets folder and a .gitignore file.  All my files showed up as changed so I committed.  It ran for a while and said success.  I checked the local .git folder and it's the same size as my Assets folder.  I now see push has a 1 next to it --> Push (1).  So I tried to push it.  It says pushing for a minute and then nothing.  I turned on tracing and here is the log:

190305-22:07:44.073  INFO [ 1] <Global>                            Initializing GitHubForUnity:'v1.2.1' Unity:'v2018.3.2f1'
190305-22:49:20.247  INFO [ 1] <Global>                            Trace Logging Enabled
190305-22:50:08.785 TRACE [13] <UsageTracker>                      Already sent today

![image](https://user-images.githubusercontent.com/13042290/53855311-0f426100-3f9b-11e9-9b8a-2bbfa972d545.png)

Update:  Now it's just starting pushes on it's own.  I am starting to see some files in the repository but there's some errors in the trace.log:

190305-22:07:44.073  INFO [ 1] <Global>                            Initializing GitHubForUnity:'v1.2.1' Unity:'v2018.3.2f1'
190305-22:49:20.247  INFO [ 1] <Global>                            Trace Logging Enabled
190305-22:50:08.785 TRACE [13] <UsageTracker>                      Already sent today
190305-23:04:12.335 TRACE [14] <ProcessWrapper>                    Rate limit exceeded: https://lfs.github.com/pnkflydgr/Encounters/objects/6317d840a947d08ec8fa62273b7dea094d45cae2c09f48f7a22de3db49e63b32/verify
190305-23:04:12.337 TRACE [14] <ProcessWrapper>                    Rate limit exceeded: https://lfs.github.com/pnkflydgr/Encounters/objects/837722ab0513974fe4b8a458fb5e229c5a5593479eed9226ddab072fac2655bc/verify
190305-23:04:12.339 TRACE [14] <ProcessWrapper>                    Rate limit exceeded: https://lfs.github.com/pnkflydgr/Encounters/objects/9c3a3049e4758eb013a66ac64a5a020cdc6f6ccd1509883fd5710ec465f4f1a9/verify
190305-23:04:12.340 TRACE [14] <ProcessWrapper>                    Rate limit exceeded: https://lfs.github.com/pnkflydgr/Encounters/objects/9c117ab5b9c776e3ff3484b5fa3d9b6718116372aa8df610d816e5475ab32235/verify
190305-23:04:12.342 TRACE [14] <ProcessWrapper>                    Rate limit exceeded: https://lfs.github.com/pnkflydgr/Encounters/objects/be558552592ec1b09a2938adc80eb4aee1adb00031a9d70861bd32546afed024/verify
190305-23:04:12.343 TRACE [14] <ProcessWrapper>                    Rate limit exceeded: https://lfs.github.com/pnkflydgr/Encounters/objects/036da7196994b67e459cb1306f56a4794aa56ad4b4c0353f0d90786117b75c9c/verify
190305-23:04:12.344 TRACE [14] <ProcessWrapper>                    Rate limit exceeded: https://lfs.github.com/pnkflydgr/Encounters/objects/ec80a9364841aafbd3a6a4eb63db3b4f042f25b5096da167728277c021b67e80/verify
190305-23:04:12.345 TRACE [14] <ProcessWrapper>                    Rate limit exceeded: https://lfs.github.com/pnkflydgr/Encounters/objects/5229ea06a77fa118a8fbb67cddac4819c088c6985b2b4327bec59a9cbb51babe/verify
190305-23:04:12.346 TRACE [14] <ProcessWrapper>                    Rate limit exceeded: https://lfs.github.com/pnkflydgr/Encounters/objects/e108be4fe858b557d85102889114cfe15555e5760378bec3b5e15881f1ba690b/verify
190305-23:04:12.347 TRACE [14] <ProcessWrapper>                    Rate limit exceeded: https://lfs.github.com/pnkflydgr/Encounters/objects/8cd066b0f477e1ff3ad786edd0de49099cab9a920c82ff9b67767a1e42bc0065/verify
190305-23:04:12.348 TRACE [14] <ProcessWrapper>                    Rate limit exceeded: https://lfs.github.com/pnkflydgr/Encounters/objects/9ca4da54484421c6ab26330d371dc611143316412592f44265f4a5e85370963f/verify
190305-23:04:12.350 TRACE [14] <ProcessWrapper>                    Rate limit exceeded: https://lfs.github.com/pnkflydgr/Encounters/objects/e5ea1a35b2b122e6e6738aa52e04d605c49a750b0fdc31b964282f9617f0dc57/verify
190305-23:04:12.351 TRACE [14] <ProcessWrapper>                    Rate limit exceeded: https://lfs.github.com/pnkflydgr/Encounters/objects/cbe3f1d034127fc53ec073dc62e605188cb46e8ff287c350631e04571b6a26e2/verify
190305-23:04:12.352 TRACE [14] <ProcessWrapper>                    Rate limit exceeded: https://lfs.github.com/pnkflydgr/Encounters/objects/c5b94d0ff2ee74f6b7f17f676403256d6f6651f68555a855459f8126b4d2812d/verify
190305-23:04:12.353 TRACE [14] <ProcessWrapper>                    Rate limit exceeded: https://lfs.github.com/pnkflydgr/Encounters/objects/a4de3759715acd1bdb353ebbf507af499a5220959f3fc0981e0cd70e24e7674f/verify
190305-23:04:12.354 TRACE [14] <ProcessWrapper>                    Rate limit exceeded: https://lfs.github.com/pnkflydgr/Encounters/objects/11817c62f35f685055a4f0af9a735e1fa3df8304b667086a092a641121a79ea6/verify
190305-23:04:12.356 TRACE [14] <ProcessWrapper>                    Rate limit exceeded: https://lfs.github.com/pnkflydgr/Encounters/objects/095e9e468ec263814b50a1ce60d2ebc1ea0f3a73c8f518fa19a64ce3595b2d36/verify
190305-23:04:12.357 TRACE [14] <ProcessWrapper>                    Rate limit exceeded: https://lfs.github.com/pnkflydgr/Encounters/objects/87e1bc91825e9aa7fe64adf562428dd3dca329211b8d907516fbf7472b11f639/verify
190305-23:04:12.358 TRACE [14] <ProcessWrapper>                    Rate limit exceeded: https://lfs.github.com/pnkflydgr/Encounters/objects/eea232c641c8138538b54f1ffce3f9dcd693c8c1a81f7d9ed17f0ca23011989e/verify
190305-23:04:12.359 TRACE [14] <ProcessWrapper>                    Rate limit exceeded: https://lfs.github.com/pnkflydgr/Encounters/objects/c7c98db35e32c95962c03aaa20b65bf98bfa11195efc4a573f304dc291e2565a/verify
190305-23:04:12.360 TRACE [14] <ProcessWrapper>                    Rate limit exceeded: https://lfs.github.com/pnkflydgr/Encounters/objects/df6e7dca2fa94b496cd6cae772d990c6c1808d04bcef07e323ec952a532730f4/verify
190305-23:04:12.361 TRACE [14] <ProcessWrapper>                    Rate limit exceeded: https://lfs.github.com/pnkflydgr/Encounters/objects/1e2ee65a9230411ba8892bbb9ebb2665c81ed08eda2a6e8d4443e0c6d30490ca/verify
190305-23:04:12.363 TRACE [14] <ProcessWrapper>                    Rate limit exceeded: https://lfs.github.com/pnkflydgr/Encounters/objects/973ab9e36908bcd88ff4235908fa4643c1b58f66de189385737c185627656a65/verify
190305-23:04:12.364 TRACE [14] <ProcessWrapper>                    Rate limit exceeded: https://lfs.github.com/pnkflydgr/Encounters/objects/1a4ecf2edfa97d0e5e262255eca54fb39476415e83a5d541a393c407fc44d5a8/verify
190305-23:04:12.365 TRACE [14] <ProcessWrapper>                    Rate limit exceeded: https://lfs.github.com/pnkflydgr/Encounters/objects/7191454340c0300ba4ffaa8849a5da57049b46a4e31917f45eec4c75f0c024fc/verify
190305-23:04:12.366 TRACE [14] <ProcessWrapper>                    Rate limit exceeded: https://lfs.github.com/pnkflydgr/Encounters/objects/7bc2afed0cb5f02d04f582fd37615ad43ddaaa1a0091780fc03817c1693f0273/verify
190305-23:04:12.367 TRACE [14] <ProcessWrapper>                    Rate limit exceeded: https://lfs.github.com/pnkflydgr/Encounters/objects/cac3002667136fa216d1d427713a037366c7518d661776e5252242e57bd4e2c7/verify
190305-23:04:12.368 TRACE [14] <ProcessWrapper>                    Rate limit exceeded: https://lfs.github.com/pnkflydgr/Encounters/objects/5ae02f5de6b1bd3adb4550765681b2a994ecffe1793b093eb654b0211cb168c6/verify
190305-23:04:12.370 TRACE [14] <ProcessWrapper>                    Rate limit exceeded: https://lfs.github.com/pnkflydgr/Encounters/objects/a0b53e1b1e492cdaf8c2a7287a426375d8308b912d6c390bbc70733e378d0acc/verify
190305-23:04:12.371 TRACE [14] <ProcessWrapper>                    Rate limit exceeded: https://lfs.github.com/pnkflydgr/Encounters/objects/100684c87fb8516dbdae0265bd4e4278526dbec2c6b461b9c301f69cccd62d40/verify
190305-23:04:12.372 TRACE [14] <ProcessWrapper>                    Rate limit exceeded: https://lfs.github.com/pnkflydgr/Encounters/objects/eac8bede0cf8cef14ffa4ee655a48101f4b99b37fbe2d910de5de1c69087befa/verify
190305-23:04:12.374 TRACE [14] <ProcessWrapper>                    Rate limit exceeded: https://lfs.github.com/pnkflydgr/Encounters/objects/323577c3fe86161d75dd15d088fb92cd233bf9817d84a8d724161e0e85e1142f/verify
190305-23:04:12.376 TRACE [14] <ProcessWrapper>                    Rate limit exceeded: https://lfs.github.com/pnkflydgr/Encounters/objects/a5139ef8d6c5bd28b20d00694bac0cab3366ab4938c2d074e2665201b725ee5e/verify
190305-23:04:12.377 TRACE [14] <ProcessWrapper>                    Rate limit exceeded: https://lfs.github.com/pnkflydgr/Encounters/objects/75b91290cc612c139494c2c7a25d401bfbb697b0a555f9aeb4250373a13d2ab0/verify
190305-23:04:12.378 TRACE [14] <ProcessWrapper>                    Rate limit exceeded: https://lfs.github.com/pnkflydgr/Encounters/objects/52438b1b073d1090785c708cd2aaebbb02b333c276c15e8d9f91b35208d1cd76/verify
190305-23:04:12.379 TRACE [14] <ProcessWrapper>                    Rate limit exceeded: https://lfs.github.com/pnkflydgr/Encounters/objects/3428e52eed43e1ef298490529742faa18b56138a5dff2134eb75460170dc45f9/verify
190305-23:04:12.380 TRACE [14] <ProcessWrapper>                    Rate limit exceeded: https://lfs.github.com/pnkflydgr/Encounters/objects/4e57f8260e03c442aa78c719c730c9717ac22a0f2b58ba7cefb201ceaa341a79/verify
190305-23:04:12.381 TRACE [14] <ProcessWrapper>                    Rate limit exceeded: https://lfs.github.com/pnkflydgr/Encounters/objects/b3d6e61f59407d43cb93ec35822ca7227dba3b598d77afbef3a706c9c370efcb/verify
190305-23:04:12.382 TRACE [14] <ProcessWrapper>                    Rate limit exceeded: https://lfs.github.com/pnkflydgr/Encounters/objects/f1ead77d73dcb9dabeed1a4e2556e45db6ff8b6efd86de2a7c075143a5b5839d/verify
190305-23:04:12.383 TRACE [14] <ProcessWrapper>                    Rate limit exceeded: https://lfs.github.com/pnkflydgr/Encounters/objects/45643c07490070d854a99eb8c4feb2ba7c4c73660e7087a7488ac912d3546c8e/verify
190305-23:04:12.384 TRACE [14] <ProcessWrapper>                    Rate limit exceeded: https://lfs.github.com/pnkflydgr/Encounters/objects/dc0f17e143e38c19f6cb3d9a01f8948b52eccd899f229a0b20a963c7a4aba974/verify
190305-23:04:12.385 TRACE [14] <ProcessWrapper>                    Rate limit exceeded: https://lfs.github.com/pnkflydgr/Encounters/objects/455d9cb01dba904d7b1bc11911a25ab03c090920f23a76e51506f7957e47c304/verify
190305-23:04:12.386 TRACE [14] <ProcessWrapper>                    Rate limit exceeded: https://lfs.github.com/pnkflydgr/Encounters/objects/e85603121ae57f3044c5c45b3cf33e0088a588c534e081b6eb31c67ec4f8d123/verify
190305-23:04:12.388 TRACE [14] <ProcessWrapper>                    Rate limit exceeded: https://lfs.github.com/pnkflydgr/Encounters/objects/d88be55f67e13dc03646ef5ad78136d9d7391e4f88802bb9c33f79f2c4db1631/verify
190305-23:04:12.388 TRACE [14] <ProcessWrapper>                    batch response: Rate limit exceeded: https://github.com/pnkflydgr/Encounters.git/info/lfs/objects/batch
190305-23:04:12.390 TRACE [14] <ProcessWrapper>                    batch response: Rate limit exceeded: https://github.com/pnkflydgr/Encounters.git/info/lfs/objects/batch
190305-23:04:12.391 TRACE [14] <ProcessWrapper>                    batch response: Rate limit exceeded: https://github.com/pnkflydgr/Encounters.git/info/lfs/objects/batch
190305-23:04:12.392 TRACE [14] <ProcessWrapper>                    batch response: Rate limit exceeded: https://github.com/pnkflydgr/Encounters.git/info/lfs/objects/batch
190305-23:04:12.394 TRACE [14] <ProcessWrapper>                    batch response: Rate limit exceeded: https://github.com/pnkflydgr/Encounters.git/info/lfs/objects/batch
190305-23:04:12.395 TRACE [14] <ProcessWrapper>                    batch response: Rate limit exceeded: https://github.com/pnkflydgr/Encounters.git/info/lfs/objects/batch
190305-23:04:12.396 TRACE [14] <ProcessWrapper>                    batch response: Rate limit exceeded: https://github.com/pnkflydgr/Encounters.git/info/lfs/objects/batch
190305-23:04:12.397 TRACE [14] <ProcessWrapper>                    batch response: Rate limit exceeded: https://github.com/pnkflydgr/Encounters.git/info/lfs/objects/batch
190305-23:04:12.398 TRACE [14] <ProcessWrapper>                    batch response: Rate limit exceeded: https://github.com/pnkflydgr/Encounters.git/info/lfs/objects/batch
190305-23:04:12.399 TRACE [14] <ProcessWrapper>                    batch response: Rate limit exceeded: https://github.com/pnkflydgr/Encounters.git/info/lfs/objects/batch
190305-23:04:12.415 TRACE [14] <ProcessWrapper>                    error: failed to push some refs to 'https://github.com/pnkflydgr/Encounters.git'
190305-23:04:12.527 TRACE [12] <ProcessWrapper>                    Running 'C:\Users\pnkfl\AppData\Local\GitHubUnity\git\cmd\git.exe -c i18n.logoutputencoding=utf8 -c core.quotepath=false status -b -u --porcelain'
190305-23:04:12.536 ERROR [711] <TaskManager>                       Exception on exclusive thread: 1 push -u origin master:master
GitHub.Unity.ProcessException: Rate limit exceeded: https://lfs.github.com/pnkflydgr/Encounters/objects/6317d840a947d08ec8fa62273b7dea094d45cae2c09f48f7a22de3db49e63b32/verify
Rate limit exceeded: https://lfs.github.com/pnkflydgr/Encounters/objects/837722ab0513974fe4b8a458fb5e229c5a5593479eed9226ddab072fac2655bc/verify
Rate limit exceeded: https://lfs.github.com/pnkflydgr/Encounters/objects/9c3a3049e4758eb013a66ac64a5a020cdc6f6ccd1509883fd5710ec465f4f1a9/verify
Rate limit exceeded: https://lfs.github.com/pnkflydgr/Encounters/objects/9c117ab5b9c776e3ff3484b5fa3d9b6718116372aa8df610d816e5475ab32235/verify
Rate limit exceeded: https://lfs.github.com/pnkflydgr/Encounters/objects/be558552592ec1b09a2938adc80eb4aee1adb00031a9d70861bd32546afed024/verify
Rate limit exceeded: https://lfs.github.com/pnkflydgr/Encounters/objects/036da7196994b67e459cb1306f56a4794aa56ad4b4c0353f0d90786117b75c9c/verify
Rate limit exceeded: https://lfs.github.com/pnkflydgr/Encounters/objects/ec80a9364841aafbd3a6a4eb63db3b4f042f25b5096da167728277c021b67e80/verify
Rate limit exceeded: https://lfs.github.com/pnkflydgr/Encounters/objects/5229ea06a77fa118a8fbb67cddac4819c088c6985b2b4327bec59a9cbb51babe/verify
Rate limit exceeded: https://lfs.github.com/pnkflydgr/Encounters/objects/e108be4fe858b557d85102889114cfe15555e5760378bec3b5e15881f1ba690b/verify
Rate limit exceeded: https://lfs.github.com/pnkflydgr/Encounters/objects/8cd066b0f477e1ff3ad786edd0de49099cab9a920c82ff9b67767a1e42bc0065/verify
Rate limit exceeded: https://lfs.github.com/pnkflydgr/Encounters/objects/9ca4da54484421c6ab26330d371dc611143316412592f44265f4a5e85370963f/verify
Rate limit exceeded: https://lfs.github.com/pnkflydgr/Encounters/objects/e5ea1a35b2b122e6e6738aa52e04d605c49a750b0fdc31b964282f9617f0dc57/verify
Rate limit exceeded: https://lfs.github.com/pnkflydgr/Encounters/objects/cbe3f1d034127fc53ec073dc62e605188cb46e8ff287c350631e04571b6a26e2/verify
Rate limit exceeded: https://lfs.github.com/pnkflydgr/Encounters/objects/c5b94d0ff2ee74f6b7f17f676403256d6f6651f68555a855459f8126b4d2812d/verify
Rate limit exceeded: https://lfs.github.com/pnkflydgr/Encounters/objects/a4de3759715acd1bdb353ebbf507af499a5220959f3fc0981e0cd70e24e7674f/verify
Rate limit exceeded: https://lfs.github.com/pnkflydgr/Encounters/objects/11817c62f35f685055a4f0af9a735e1fa3df8304b667086a092a641121a79ea6/verify
Rate limit exceeded: https://lfs.github.com/pnkflydgr/Encounters/objects/095e9e468ec263814b50a1ce60d2ebc1ea0f3a73c8f518fa19a64ce3595b2d36/verify
Rate limit exceeded: https://lfs.github.com/pnkflydgr/Encounters/objects/87e1bc91825e9aa7fe64adf562428dd3dca329211b8d907516fbf7472b11f639/verify
Rate limit exceeded: https://lfs.github.com/pnkflydgr/Encounters/objects/eea232c641c8138538b54f1ffce3f9dcd693c8c1a81f7d9ed17f0ca23011989e/verify
Rate limit exceeded: https://lfs.github.com/pnkflydgr/Encounters/objects/c7c98db35e32c95962c03aaa20b65bf98bfa11195efc4a573f304dc291e2565a/verify
Rate limit exceeded: https://lfs.github.com/pnkflydgr/Encounters/objects/df6e7dca2fa94b496cd6cae772d990c6c1808d04bcef07e323ec952a532730f4/verify
Rate limit exceeded: https://lfs.github.com/pnkflydgr/Encounters/objects/1e2ee65a9230411ba8892bbb9ebb2665c81ed08eda2a6e8d4443e0c6d30490ca/verify
Rate limit exceeded: https://lfs.github.com/pnkflydgr/Encounters/objects/973ab9e36908bcd88ff4235908fa4643c1b58f66de189385737c185627656a65/verify
Rate limit exceeded: https://lfs.github.com/pnkflydgr/Encounters/objects/1a4ecf2edfa97d0e5e262255eca54fb39476415e83a5d541a393c407fc44d5a8/verify
Rate limit exceeded: https://lfs.github.com/pnkflydgr/Encounters/objects/7191454340c0300ba4ffaa8849a5da57049b46a4e31917f45eec4c75f0c024fc/verify
Rate limit exceeded: https://lfs.github.com/pnkflydgr/Encounters/objects/7bc2afed0cb5f02d04f582fd37615ad43ddaaa1a0091780fc03817c1693f0273/verify
Rate limit exceeded: https://lfs.github.com/pnkflydgr/Encounters/objects/cac3002667136fa216d1d427713a037366c7518d661776e5252242e57bd4e2c7/verify
Rate limit exceeded: https://lfs.github.com/pnkflydgr/Encounters/objects/5ae02f5de6b1bd3adb4550765681b2a994ecffe1793b093eb654b0211cb168c6/verify
Rate limit exceeded: https://lfs.github.com/pnkflydgr/Encounters/objects/a0b53e1b1e492cdaf8c2a7287a426375d8308b912d6c390bbc70733e378d0acc/verify
Rate limit exceeded: https://lfs.github.com/pnkflydgr/Encounters/objects/100684c87fb8516dbdae0265bd4e4278526dbec2c6b461b9c301f69cccd62d40/verify
Rate limit exceeded: https://lfs.github.com/pnkflydgr/Encounters/objects/eac8bede0cf8cef14ffa4ee655a48101f4b99b37fbe2d910de5de1c69087befa/verify
Rate limit exceeded: https://lfs.github.com/pnkflydgr/Encounters/objects/323577c3fe86161d75dd15d088fb92cd233bf9817d84a8d724161e0e85e1142f/verify
Rate limit exceeded: https://lfs.github.com/pnkflydgr/Encounters/objects/a5139ef8d6c5bd28b20d00694bac0cab3366ab4938c2d074e2665201b725ee5e/verify
Rate limit exceeded: https://lfs.github.com/pnkflydgr/Encounters/objects/75b91290cc612c139494c2c7a25d401bfbb697b0a555f9aeb4250373a13d2ab0/verify
Rate limit exceeded: https://lfs.github.com/pnkflydgr/Encounters/objects/52438b1b073d1090785c708cd2aaebbb02b333c276c15e8d9f91b35208d1cd76/verify
Rate limit exceeded: https://lfs.github.com/pnkflydgr/Encounters/objects/3428e52eed43e1ef298490529742faa18b56138a5dff2134eb75460170dc45f9/verify
Rate limit exceeded: https://lfs.github.com/pnkflydgr/Encounters/objects/4e57f8260e03c442aa78c719c730c9717ac22a0f2b58ba7cefb201ceaa341a79/verify
Rate limit exceeded: https://lfs.github.com/pnkflydgr/Encounters/objects/b3d6e61f59407d43cb93ec35822ca7227dba3b598d77afbef3a706c9c370efcb/verify
Rate limit exceeded: https://lfs.github.com/pnkflydgr/Encounters/objects/f1ead77d73dcb9dabeed1a4e2556e45db6ff8b6efd86de2a7c075143a5b5839d/verify
Rate limit exceeded: https://lfs.github.com/pnkflydgr/Encounters/objects/45643c07490070d854a99eb8c4feb2ba7c4c73660e7087a7488ac912d3546c8e/verify
Rate limit exceeded: https://lfs.github.com/pnkflydgr/Encounters/objects/dc0f17e143e38c19f6cb3d9a01f8948b52eccd899f229a0b20a963c7a4aba974/verify
Rate limit exceeded: https://lfs.github.com/pnkflydgr/Encounters/objects/455d9cb01dba904d7b1bc11911a25ab03c090920f23a76e51506f7957e47c304/verify
Rate limit exceeded: https://lfs.github.com/pnkflydgr/Encounters/objects/e85603121ae57f3044c5c45b3cf33e0088a588c534e081b6eb31c67ec4f8d123/verify
Rate limit exceeded: https://lfs.github.com/pnkflydgr/Encounters/objects/d88be55f67e13dc03646ef5ad78136d9d7391e4f88802bb9c33f79f2c4db1631/verify
batch response: Rate limit exceeded: https://github.com/pnkflydgr/Encounters.git/info/lfs/objects/batch
batch response: Rate limit exceeded: https://github.com/pnkflydgr/Encounters.git/info/lfs/objects/batch
batch response: Rate limit exceeded: https://github.com/pnkflydgr/Encounters.git/info/lfs/objects/batch
batch response: Rate limit exceeded: https://github.com/pnkflydgr/Encounters.git/info/lfs/objects/batch
batch response: Rate limit exceeded: https://github.com/pnkflydgr/Encounters.git/info/lfs/objects/batch
batch response: Rate limit exceeded: https://github.com/pnkflydgr/Encounters.git/info/lfs/objects/batch
batch response: Rate limit exceeded: https://github.com/pnkflydgr/Encounters.git/info/lfs/objects/batch
batch response: Rate limit exceeded: https://github.com/pnkflydgr/Encounters.git/info/lfs/objects/batch
batch response: Rate limit exceeded: https://github.com/pnkflydgr/Encounters.git/info/lfs/objects/batch
batch response: Rate limit exceeded: https://github.com/pnkflydgr/Encounters.git/info/lfs/objects/batch
error: failed to push some refs to 'https://github.com/pnkflydgr/Encounters.git'
  at GitHub.Unity.ProcessTask`1+<>c__DisplayClass20_0[T].<RunWithReturn>b__1 () [0x00116] in C:\projects\unity\src\GitHub.Api\Tasks\ProcessTask.cs:371 
  at GitHub.Unity.ProcessWrapper.Run () [0x003cd] in C:\projects\unity\src\GitHub.Api\Tasks\ProcessTask.cs:199 
  at GitHub.Unity.ProcessTask`1[T].RunWithReturn (System.Boolean success) [0x00061] in C:\projects\unity\src\GitHub.Api\Tasks\ProcessTask.cs:380 
  at GitHub.Unity.TaskBase`1[TResult].RunSynchronously () [0x00049] in C:\projects\unity\src\GitHub.Api\Tasks\TaskBase.cs:685 
  at System.Threading.Tasks.Task`1[TResult].InnerInvoke () [0x0000f] in <ac823e2bb42b41bda67924a45a0173c3>:0 
  at System.Threading.Tasks.Task.Execute () [0x00010] in <ac823e2bb42b41bda67924a45a0173c3>:0 
=======
  at GitHub.Unity.TaskManager+<>c__DisplayClass29_0`1[T].<ScheduleExclusive>b__0 (System.Threading.Tasks.Task tt) [0x00000] in C:\projects\unity\src\GitHub.Api\Tasks\TaskManager.cs:128 
  at System.Threading.Tasks.ContinuationTaskFromTask.InnerInvoke () [0x00000] in <ac823e2bb42b41bda67924a45a0173c3>:0 
  at System.Threading.Tasks.Task.Execute () [0x00000] in <ac823e2bb42b41bda67924a45a0173c3>:0 
  at System.Threading.Tasks.Task.ExecutionContextCallback (System.Object obj) [0x00000] in <ac823e2bb42b41bda67924a45a0173c3>:0 
  at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in <ac823e2bb42b41bda67924a45a0173c3>:0 
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in <ac823e2bb42b41bda67924a45a0173c3>:0 
  at System.Threading.Tasks.Task.ExecuteWithThreadLocal (System.Threading.Tasks.Task& currentTaskSlot) [0x00000] in <ac823e2bb42b41bda67924a45a0173c3>:0 
  at System.Threading.Tasks.Task.ExecuteEntry (System.Boolean bPreventDoubleExecution) [0x00000] in <ac823e2bb42b41bda67924a45a0173c3>:0 
  at System.Threading.Tasks.TaskScheduler.TryExecuteTask (System.Threading.Tasks.Task task) [0x00000] in <ac823e2bb42b41bda67924a45a0173c3>:0 
  at GitHub.Unity.ThreadPerTaskScheduler+<>c__DisplayClass4_0.<QueueTask>b__0 () [0x00000] in C:\projects\unity\src\GitHub.Api\Tasks\ConcurrentExclusiveInterleave.cs:440 
  at System.Threading.ThreadHelper.ThreadStart_Context (System.Object state) [0x00000] in <ac823e2bb42b41bda67924a45a0173c3>:0 
  at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in <ac823e2bb42b41bda67924a45a0173c3>:0 
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in <ac823e2bb42b41bda67924a45a0173c3>:0 
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) [0x00000] in <ac823e2bb42b41bda67924a45a0173c3>:0 
  at System.Threading.ThreadHelper.ThreadStart () [0x00000] in <ac823e2bb42b41bda67924a45a0173c3>:0 
190305-23:04:12.724 TRACE [12] <ProcessWrapper>                    Running 'C:\Users\pnkfl\AppData\Local\GitHubUnity\git\cmd\git.exe push -u origin master:master'
190305-23:05:10.023 TRACE [13] <ProcessWrapper>                    To https://github.com/pnkflydgr/Encounters.git
190305-23:05:10.024 TRACE [13] <ProcessWrapper>                       04fe129..899ce54  master -> master
190305-23:05:10.133 TRACE [12] <ProcessWrapper>                    Running 'C:\Users\pnkfl\AppData\Local\GitHubUnity\git\cmd\git.exe -c i18n.logoutputencoding=utf8 -c core.quotepath=false status -b -u --porcelain'
190305-23:05:10.326 TRACE [12] <ProcessWrapper>                    Running 'C:\Users\pnkfl\AppData\Local\GitHubUnity\git\cmd\git.exe -c i18n.logoutputencoding=utf8 -c core.quotepath=false status -b -u --porcelain'
190305-23:05:10.512 TRACE [12] <ProcessWrapper>                    Running 'C:\Users\pnkfl\AppData\Local\GitHubUnity\git\cmd\git.exe fetch --prune --tags origin'
190305-23:05:11.344 TRACE [12] <ProcessWrapper>                    Running 'C:\Users\pnkfl\AppData\Local\GitHubUnity\git\cmd\git.exe fetch --prune --tags origin'
190305-23:05:12.235 TRACE [12] <ProcessWrapper>                    Running 'C:\Users\pnkfl\AppData\Local\GitHubUnity\git\cmd\git.exe pull origin master'
190305-23:05:13.167 TRACE [152] <ProcessWrapper>                    From https://github.com/pnkflydgr/Encounters
190305-23:05:13.169 TRACE [152] <ProcessWrapper>                     * branch            master     -> FETCH_HEAD
190305-23:05:13.328 TRACE [12] <RepositoryWatcher>                 Watching Path: "E:\games\unity\Encounters\Encounters"
190305-23:05:13.329 TRACE [12] <ProcessWrapper>                    Running 'C:\Users\pnkfl\AppData\Local\GitHubUnity\git\cmd\git.exe rev-list --left-right --count master...origin/master'
190305-23:05:13.493 TRACE [12] <ProcessWrapper>                    Running 'C:\Users\pnkfl\AppData\Local\GitHubUnity\git\cmd\git.exe push -u origin master:master'
190305-23:05:15.277 TRACE [14] <ProcessWrapper>                    Everything up-to-date
190305-23:05:15.388 TRACE [12] <ProcessWrapper>                    Running 'C:\Users\pnkfl\AppData\Local\GitHubUnity\git\cmd\git.exe push -u origin master:master'
190305-23:05:17.144 TRACE [145] <ProcessWrapper>                    Everything up-to-date
190305-23:05:17.253 TRACE [12] <ProcessWrapper>                    Running 'C:\Users\pnkfl\AppData\Local\GitHubUnity\git\cmd\git.exe push -u origin master:master'
190305-23:05:18.895 TRACE [145] <ProcessWrapper>                    Everything up-to-date
190305-23:05:19.005 TRACE [12] <ProcessWrapper>                    Running 'C:\Users\pnkfl\AppData\Local\GitHubUnity\git\cmd\git.exe push -u origin master:master'
190305-23:05:20.886 TRACE [150] <ProcessWrapper>                    Everything up-to-date
190305-23:05:20.995 TRACE [12] <ProcessWrapper>                    Running 'C:\Users\pnkfl\AppData\Local\GitHubUnity\git\cmd\git.exe rev-list --left-right --count master...origin/master'
190305-23:05:21.154 TRACE [12] <ProcessWrapper>                    Running 'C:\Users\pnkfl\AppData\Local\GitHubUnity\git\cmd\git.exe rev-list --left-right --count master...origin/master'
190305-23:05:21.314 TRACE [12] <ProcessWrapper>                    Running 'C:\Users\pnkfl\AppData\Local\GitHubUnity\git\cmd\git.exe rev-list --left-right --count master...origin/master'
190305-23:05:21.473 TRACE [12] <ProcessWrapper>                    Running 'C:\Users\pnkfl\AppData\Local\GitHubUnity\git\cmd\git.exe rev-list --left-right --count master...origin/master'
190305-23:05:21.632 TRACE [12] <ProcessWrapper>                    Running 'C:\Users\pnkfl\AppData\Local\GitHubUnity\git\cmd\git.exe rev-list --left-right --count master...origin/master'
190305-23:05:21.791 TRACE [12] <ProcessWrapper>                    Running 'C:\Users\pnkfl\AppData\Local\GitHubUnity\git\cmd\git.exe rev-list --left-right --count master...origin/master'
190305-23:05:21.955 TRACE [12] <ProcessWrapper>                    Running 'C:\Users\pnkfl\AppData\Local\GitHubUnity\git\cmd\git.exe rev-list --left-right --count master...origin/master'

**Comment by pnkflydgr** [comment]
Seems to be working ok now.  I'm guess because the initial commit was so large, there were some delays and errors.

**Comment by JotaRata** [comment]
How did you fixed this?
 I'm having troubles right now...
