### ISSUE TITLE
Please use asmdef files in github for unity

### ISSUE THREAD

**Issue by Ecnassianer** [github-for-unity/Unity#1029]
I use asmdef files in my project, which means I need to create asmdef files for Github For Unity and put them in the Github for Unity folder. But then when I update Github For Unity they get deleted and I have to recreate them.

Please create asmdef files for this project. It will also speed up compile times for projects that use Github for Unity, since they won't have to recompile Github for Unity every time.

Thank you!

**Comment by StanleyGoldman** [comment]
Hi @Ecnassianer 

How are you performing this upgrade, is the package installer deleting the file?
