### ISSUE TITLE
Update to v1.3.0 causes changes view problem

### ISSUE THREAD

**Issue by mmiao** [github-for-unity/Unity#1032]
### Prerequisites

[github-unity.log](https://github.com/github-for-unity/Unity/files/2955896/github-unity.log)

### Description
I updated from v1.2 to the latest version then I got an error and changes view starts to behave strangely.

Stack trace:
LoadSerializedFileAndForget can only be called from the main thread.
Constructors and field initializers will be executed from the loading thread when loading a scene.
Don't use this function in the constructor or field initializers, instead move initialization code to the Awake or Start function.
UnityEditorInternal.InternalEditorUtility:LoadSerializedFileAndForget(String)
GitHub.Unity.ScriptObjectSingleton`1:CreateAndLoad() (at C:/projects/unity/src/UnityExtension/Assets/Editor/GitHub.Unity/ScriptObjectSingleton.cs:78)
GitHub.Unity.ScriptObjectSingleton`1:get_Instance() (at C:/projects/unity/src/UnityExtension/Assets/Editor/GitHub.Unity/ScriptObjectSingleton.cs:53)
GitHub.Unity.<>c:<get_Environment>b__10_4() (at C:/projects/unity/src/UnityExtension/Assets/Editor/GitHub.Unity/ApplicationCache.cs:150)
GitHub.Unity.<>c__DisplayClass8_0:<SetCacheInitializer>b__0() (at C:/projects/unity/src/GitHub.Api/Cache/CacheContainer.cs:19)
System.Lazy`1:get_Value()
GitHub.Unity.CacheContainer:GetCache(CacheType) (at C:/projects/unity/src/GitHub.Api/Cache/CacheContainer.cs:46)
GitHub.Unity.Repository:InvalidationFailed(Exception, CacheType) (at C:/projects/unity/src/GitHub.Api/Git/Repository.cs:263)
GitHub.Unity.<>c__DisplayClass74_0:<CacheHasBeenInvalidated>b__2(Exception) (at C:/projects/unity/src/GitHub.Api/Git/Repository.cs:229)
System.Delegate:DynamicInvoke(Object[])
GitHub.Unity.TaskBase:RaiseFaultHandlers(Exception) (at C:/projects/unity/src/GitHub.Api/Tasks/TaskBase.cs:453)
GitHub.Unity.<>c__DisplayClass20_0:<RunWithReturn>b__1() (at C:/projects/unity/src/GitHub.Api/Tasks/ProcessTask.cs:497)
GitHub.Unity.ProcessWrapper:Run() (at C:/projects/unity/src/GitHub.Api/Tasks/ProcessTask.cs:199)
GitHub.Unity.ProcessTaskWithListOutput`1:RunWithReturn(Boolean) (at C:/projects/unity/src/GitHub.Api/Tasks/ProcessTask.cs:506)
GitHub.Unity.TaskBase`1:RunSynchronously() (at C:/projects/unity/src/GitHub.Api/Tasks/TaskBase.cs:685)
System.Threading.Tasks.TaskScheduler:TryExecuteTask(Task)
GitHub.Unity.<>c__DisplayClass4_0:<QueueTask>b__0() (at C:/projects/unity/src/GitHub.Api/Tasks/ConcurrentExclusiveInterleave.cs:440)
 

### Steps to Reproduce

1. Update to v1.3 from v1.2.
2. Do some change on code, refresh to see the changes
3. Try to commit

**Expected behavior:** Changes view show all the changes

**Actual behavior:** The changes on plugins(cause by update) always show up, even in history view you can see they are already committed. The changes in other parts of the code never show up, but they also get committed.
**Reproduces how often:** 100%

**Comment by ersagunkuruca** [comment]
I have the same problem. I recently updated but I don't know if it started with the update or if it was there before. I didn't notice any errors after the update. I don't have any now. 

Changes view is unpredictable, mostly showing what changes there were before a few commits. Although Project view shows right + and . symbols for changed and added files. It seems like all changed files are staged each time I commit. I have no choice (if I want to use Github for Unity anyway). I can't choose between the files that didn't change to stage some of the files that did change. 😄 

Any feedback or temporary workaround would be great. Thanks.

**Comment by StanleyGoldman** [comment]
Hey, thanks for bringing this to my attention.
I should be able to resolve it and push out a patch release soon.
The only workaround would be to downgrade temporarily.

**Comment by mmiao** [comment]
> I have the same problem. I recently updated but I don't know if it started with the update or if it was there before. I didn't notice any errors after the update. I don't have any now.
> 
> Changes view is unpredictable, mostly showing what changes there were before a few commits. Although Project view shows right + and . symbols for changed and added files. It seems like all changed files are staged each time I commit. I have no choice (if I want to use Github for Unity anyway). I can't choose between the files that didn't change to stage some of the files that did change. 😄
> 
> Any feedback or temporary workaround would be great. Thanks.

Currently I roll back to v1.2 and everything works fine for me. As developer already recognized this problem I believe it will be fixed in future.

**Comment by mmiao** [comment]
> Hey, thanks for bringing this to my attention.
> I should be able to resolve it and push out a patch release soon.
> The only workaround would be to downgrade temporarily.

Glad to hear that! Let me know if you need any more information.

**Comment by mrdaemon** [comment]
Hi, just mentioning that this is still happening for me on 1.3.1
