### ISSUE TITLE
RSA Certficate Error whilst signing in : "Bad Signature"

### ISSUE THREAD

**Issue by reithegoat** [github-for-unity/Unity#1036]
### Prerequisites

- Be sure to run with tracing enabled to capture runtime details in the log file
- Include the log file in the PR.
  - On Windows, the extension log file is at `%LOCALAPPDATA%\GitHubUnity\github-unity.log`
  - On macOS, the extension log file is at `~/Library/Logs/GitHubUnity/github-unity.log`
  - On linux, the extension log file is at `~/.local/share/GitHubUnity/github-unity.log`

### Description

BEFORE: Error occurs whilst attempting to sign in via, both, in the browser and within the editor.
AFTER: After looking at the error more, I noticed a "bad signature" error, and seeing RSA made me think it's the fault of an invalid certificate. 
### Steps to Reproduce

1. [First Step]
Import the GitHub Unity package from the official site (not the Asset Store)
2. [Second Step]
Initialize a Git
3. [Third Step]
Attempt to sign in

**Expected behavior:** [What you expect to happen]
It would sign me in

**Actual behavior:** [What actually happens]
Showed me an error for an RSA certificate

**Reproduces how often:** [What percentage of the time does it reproduce?]
For me, all the time.

**Image of the error**
![image](https://user-images.githubusercontent.com/11689362/54881875-0a026480-4e2b-11e9-8ee9-c12038813fc0.png)

**Other Info**
I checked the runtime log, there's nothing except one line letting me know GitHub for Unity has been initialized.

EDIT: Yes, I know the username in the field is different than the one I have, I typed in the correct username but still showed the same error.

**EDIT 2:** After looking at the error some more, I'm thinking it's a faulty certificate causing the issue.

**Comment by shana** [comment]
What version of Unity is this?

**Comment by reithegoat** [comment]
Unity 2018.3.14

**Comment by nimda32** [comment]
Did anyone find a solution to this issue? 
Currently seeing this on Windows 10, 2018.4.15
