### ISSUE TITLE
Could not find a part of the path

### ISSUE THREAD

**Issue by thegiantbeast** [github-for-unity/Unity#1037]
I'm getting the following error in my project:

> DirectoryNotFoundException: Could not find a part of the path "/foobar/Assets/Editor/GitHub.Unity/IconsAndLogos/renamed.png".

And following the error log, I got into this file:

https://github.com/github-for-unity/Unity/blob/a32f4e405dea9b04aeaedd055863f31d5113be03/src/UnityExtension/Assets/Editor/GitHub.Unity/Misc/Styles.cs#L122

And looking into this folder where it seems to search for the icons, that specific file doesn't exist at all, the closest thing to it is the "moved" one:
https://github.com/github-for-unity/Unity/tree/master/src/UnityExtension/Assets/Editor/GitHub.Unity/IconsAndLogos

Attaching the entire log output:
`DirectoryNotFoundException: Could not find a part of the path "/foobar/Assets/Editor/GitHub.Unity/IconsAndLogos/renamed.png".
System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean anonymous, System.IO.FileOptions options) (at <d7ac571ca2d04b2f981d0d886fa067cf>:0)
System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share) (at <d7ac571ca2d04b2f981d0d886fa067cf>:0)
(wrapper remoting-invoke-with-check) System.IO.FileStream..ctor(string,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare)
System.IO.File.OpenRead (System.String path) (at <d7ac571ca2d04b2f981d0d886fa067cf>:0)
System.IO.File.ReadAllBytes (System.String path) (at <d7ac571ca2d04b2f981d0d886fa067cf>:0)
GitHub.Unity.FileSystem.ReadAllBytes (System.String path) (at C:/projects/unity/src/GitHub.Api/IO/FileSystem.cs:189)
GitHub.Unity.FSWrapper.ReadAllBytes (GitHub.Unity.NPath path) (at C:/projects/unity/src/GitHub.Api/IO/NiceIO.cs:1333)
GitHub.Unity.NPath.ReadAllBytes () (at C:/projects/unity/src/GitHub.Api/IO/NiceIO.cs:874)
GitHub.Unity.Utility.GetIcon (System.String filename, System.String filename2x, System.Boolean invertColors) (at C:/projects/unity/src/UnityExtension/Assets/Editor/GitHub.Unity/Misc/Utility.cs:42)
GitHub.Unity.Styles.GetFileStatusIcon (GitHub.Unity.GitFileStatus status, System.Boolean isLocked) (at C:/projects/unity/src/UnityExtension/Assets/Editor/GitHub.Unity/Misc/Styles.cs:123)
GitHub.Unity.ProjectWindowInterface.OnProjectWindowItemGUI (System.String guid, UnityEngine.Rect itemRect) (at C:/projects/unity/src/UnityExtension/Assets/Editor/GitHub.Unity/UI/ProjectWindowInterface.cs:325)
UnityEditor.ProjectBrowser.OnGUIAssetCallback (System.Int32 instanceID, UnityEngine.Rect rect) (at /Users/builduser/buildslave/unity/build/Editor/Mono/ProjectBrowser.cs:667)
UnityEditor.IMGUI.Controls.TreeViewController.DoItemGUI (UnityEditor.IMGUI.Controls.TreeViewItem item, System.Int32 row, System.Single rowWidth, System.Boolean hasFocus) (at /Users/builduser/buildslave/unity/build/Editor/Mono/GUI/TreeView/TreeViewController.cs:501)
UnityEditor.IMGUI.Controls.TreeViewController.IterateVisibleItems (System.Int32 firstRow, System.Int32 numVisibleRows, System.Single rowWidth, System.Boolean hasFocus) (at /Users/builduser/buildslave/unity/build/Editor/Mono/GUI/TreeView/TreeViewController.cs:679)
UnityEditor.IMGUI.Controls.TreeViewController.OnGUI (UnityEngine.Rect rect, System.Int32 keyboardControlID) (at /Users/builduser/buildslave/unity/build/Editor/Mono/GUI/TreeView/TreeViewController.cs:605)
UnityEditor.ProjectBrowser.OnGUI () (at /Users/builduser/buildslave/unity/build/Editor/Mono/ProjectBrowser.cs:1948)
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <d7ac571ca2d04b2f981d0d886fa067cf>:0)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <d7ac571ca2d04b2f981d0d886fa067cf>:0)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at <d7ac571ca2d04b2f981d0d886fa067cf>:0)
UnityEditor.HostView.Invoke (System.String methodName, System.Object obj) (at /Users/builduser/buildslave/unity/build/Editor/Mono/HostView.cs:342)
UnityEditor.HostView.Invoke (System.String methodName) (at /Users/builduser/buildslave/unity/build/Editor/Mono/HostView.cs:336)
UnityEditor.HostView.InvokeOnGUI (UnityEngine.Rect onGUIPosition, UnityEngine.Rect viewRect) (at /Users/builduser/buildslave/unity/build/Editor/Mono/HostView.cs:310)
UnityEditor.DockArea.DrawView (UnityEngine.Rect viewRect, UnityEngine.Rect dockAreaRect, System.Boolean customBorder, System.Boolean floatingWindow, System.Boolean isBottomTab) (at /Users/builduser/buildslave/unity/build/Editor/Mono/GUI/DockArea.cs:361)
UnityEditor.DockArea.OldOnGUI () (at /Users/builduser/buildslave/unity/build/Editor/Mono/GUI/DockArea.cs:320)
UnityEngine.Experimental.UIElements.IMGUIContainer.DoOnGUI (UnityEngine.Event evt, UnityEngine.Matrix4x4 worldTransform, UnityEngine.Rect clippingRect, System.Boolean isComputingLayout) (at /Users/builduser/buildslave/unity/build/Modules/UIElements/IMGUIContainer.cs:266)
UnityEngine.Experimental.UIElements.IMGUIContainer.HandleIMGUIEvent (UnityEngine.Event e, UnityEngine.Matrix4x4 worldTransform, UnityEngine.Rect clippingRect) (at /Users/builduser/buildslave/unity/build/Modules/UIElements/IMGUIContainer.cs:438)
UnityEngine.Experimental.UIElements.IMGUIContainer.HandleIMGUIEvent () (at /Users/builduser/buildslave/unity/build/Modules/UIElements/IMGUIContainer.cs:412)
UnityEngine.Experimental.UIElements.ImmediateStylePainter.DrawImmediate (System.Action callback) (at /Users/builduser/buildslave/unity/build/Modules/UIElements/ImmediateStylePainter.cs:113)
UnityEngine.Experimental.UIElements.IMGUIContainer.DoRepaint (UnityEngine.Experimental.UIElements.IStylePainter painter) (at /Users/builduser/buildslave/unity/build/Modules/UIElements/IMGUIContainer.cs:98)
UnityEngine.Experimental.UIElements.VisualElement.Repaint (UnityEngine.Experimental.UIElements.IStylePainter painter) (at /Users/builduser/buildslave/unity/build/Modules/UIElements/VisualElement.cs:862)
UnityEngine.Experimental.UIElements.VisualTreeRepaintUpdater.PaintSubTree (UnityEngine.Experimental.UIElements.VisualElement root, UnityEngine.Matrix4x4 offset, System.Boolean shouldClip, System.Boolean shouldCache, UnityEngine.Rect currentGlobalClip) (at /Users/builduser/buildslave/unity/build/Modules/UIElements/VisualTreeRepaintUpdater.cs:310)
UnityEngine.Experimental.UIElements.VisualTreeRepaintUpdater.PaintSubTreeChildren (UnityEngine.Experimental.UIElements.VisualElement root, UnityEngine.Matrix4x4 offset, System.Boolean shouldClip, System.Boolean shouldCache, UnityEngine.Rect textureClip) (at /Users/builduser/buildslave/unity/build/Modules/UIElements/VisualTreeRepaintUpdater.cs:328)
UnityEngine.Experimental.UIElements.VisualTreeRepaintUpdater.PaintSubTree (UnityEngine.Experimental.UIElements.VisualElement root, UnityEngine.Matrix4x4 offset, System.Boolean shouldClip, System.Boolean shouldCache, UnityEngine.Rect currentGlobalClip) (at /Users/builduser/buildslave/unity/build/Modules/UIElements/VisualTreeRepaintUpdater.cs:314)
UnityEngine.Experimental.UIElements.VisualTreeRepaintUpdater.Update () (at /Users/builduser/buildslave/unity/build/Modules/UIElements/VisualTreeRepaintUpdater.cs:35)
UnityEngine.Experimental.UIElements.VisualTreeUpdater.UpdateVisualTree () (at /Users/builduser/buildslave/unity/build/Modules/UIElements/VisualTreeUpdater.cs:70)
UnityEngine.Experimental.UIElements.Panel.Repaint (UnityEngine.Event e) (at /Users/builduser/buildslave/unity/build/Modules/UIElements/Panel.cs:507)
UnityEngine.Experimental.UIElements.UIElementsUtility.DoDispatch (UnityEngine.Experimental.UIElements.BaseVisualElementPanel panel) (at /Users/builduser/buildslave/unity/build/Modules/UIElements/UIElementsUtility.cs:230)
UnityEngine.Experimental.UIElements.UIElementsUtility.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr) (at /Users/builduser/buildslave/unity/build/Modules/UIElements/UIElementsUtility.cs:68)
UnityEngine.GUIUtility.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr) (at /Users/builduser/buildslave/unity/build/Modules/IMGUI/GUIUtility.cs:179)
`

**Comment by mwegner** [comment]
I'm seeing this too.  For anyone who bumps into it, the easy workaround to is to [grab an icon from here](https://github.com/github-for-unity/Unity/tree/master/src/UnityExtension/Assets/Editor/GitHub.Unity/IconsAndLogos) and add to your project as a loose file in `Editor/GitHub.Unity/IconsAndLogos/renamed.png` (and `renamed@2x.png`).  You don't need to fully build/repack.
