### ISSUE TITLE
Github for Unity should create an appropriate gitignore

### ISSUE THREAD

**Issue by jwvanderbeck** [github-for-unity/Unity#1040]
There are well accepted standards for which files to commit to git and which not to commit to git for Unity projects.  The Github client even has presets for this.

The Github for Unity asset should set this up for the user on a new repo.  I shouldn't need to go into the command line and manually set this up.

**Comment by gamodulon** [comment]
It does set it up on init automatically (both .gitignore & .gitattributes for lfs). (ver. 1.3.0)

**Comment by jwvanderbeck** [comment]
hmm it did not for me.  I had neither file.

**Comment by FurkanKambay** [comment]
what's the version? the log file will probably tell why the files were not created.

**Comment by shana** [comment]
This should definitely be happening on a new repo, it creates these files and commits them as the first commit of your project. If that didn't happen for you, likely you don't have the commit either and something went wrong there, as @FurkanKambay says.

**Comment by shana** [comment]
Actually, I think this is the same problem as #1044. Release 1.3.1 (https://github.com/github-for-unity/Unity/releases/tag/v1.3.1.6478) should fix this! 🤞
