### ISSUE TITLE
Initial commit changes not detected correctly

### ISSUE THREAD

**Issue by VertexityStudio** [github-for-unity/Unity#1041]
Trying GitHub for Unity on existing project so new distant repo and for the first commit, GitHub for Unity should detect all existing project files but nothing. It just detect .GitIgnore, .GitAttributes, create an empty Assets folder on repo... that's all :(

**Comment by shana** [comment]
Release 1.3.1 (https://github.com/github-for-unity/Unity/releases/tag/v1.3.1.6478) should fix this! 🤞
