### ISSUE TITLE
Github for Unity not working with MRTK

### ISSUE THREAD

**Issue by Avalin** [github-for-unity/Unity#1042]
### Prerequisites

Errors not happening at runtime, so I don't see how it's relevant

### Description

Compilation errors with MRTK. Seemingly some of the same libraries are used but different versions? 

### Steps to Reproduce

1. Initialize new project
2. Get MRTK v2 Beta .unitypackage from [here](https://github.com/Microsoft/MixedRealityToolkit-Unity/releases)
3. Double-click unitypackage and import it to the new project
4. Import Github for Unity found [here](https://assetstore.unity.com/packages/tools/version-control/github-for-unity-118069)
5. Partytime with compilation errors

**Expected behavior:** [What you expect to happen]
Ability to use Github functionalities for project implementing MRTK 

**Actual behavior:** [What actually happens]
Compilation errors

**Reproduces how often:** [What percentage of the time does it reproduce?]
100% I'd say

### Additional Information
![1](https://user-images.githubusercontent.com/15669154/55535342-3897ff00-56b7-11e9-9b29-3fbacbdefd76.png)
Above is an image of some of the errors

### Workaround
Found out that by installing Github for Unity directly from [here](https://unity.github.com/), instead of Asset Store, there will be no errors.

**Comment by shana** [comment]
I think this might be a problem that's fixed already in the latest release, but the asset store package isn't updated, I'll track that down.

**Comment by shana** [comment]
The asset store was updated, closing this.
