### ISSUE TITLE
Ball collider is going through a rectangle collider

### ISSUE THREAD

**Issue by josephparis97** [github-for-unity/Unity#1043]
hi ! I am trying to controle a Ball with a plateform. I use a joystick to controle the plateform. I don't know if it s a bug but the ball pass trough the plateform...
![plateformproblem](https://user-images.githubusercontent.com/47667216/55741105-c7e14180-5a2c-11e9-9a9a-7308f6d16596.gif)

I don't know why it is doing this because the Sphere has a colider and a RigidBody, the plateform has a collider.
![image](https://user-images.githubusercontent.com/47667216/55741224-0ecf3700-5a2d-11e9-89e6-2d65d2890076.png)
![image](https://user-images.githubusercontent.com/47667216/55741311-4342f300-5a2d-11e9-84ae-8928d3a10e85.png)
![image](https://user-images.githubusercontent.com/47667216/55741335-4fc74b80-5a2d-11e9-922f-bff237ae795b.png)
Can someone help me ?

**Comment by Anthonipples** [comment]
This is the repo for github for unity, please direct your questions to the unity answers website
