### ISSUE TITLE
Having trouble with push...

### ISSUE THREAD

**Issue by ChiefBreakeverything** [github-for-unity/Unity#1044]
Hey guys, I'm trying out Github for Unity 1.3.0 with Unity 2018.3.4f1 and its not going very well.

The parts that work thus far are...

1. Start with a fresh Unity project
2. Install the plugin before anything else
3. Log into GitHubForUnity with my Github username
4. Publish a new remote repository

That all goes relatively smoothly. However, I can't push at all, not even the Initial commit containing the new gitattributes/gitignore files. The fields 'Path to git' and 'Path to git lfs' both look right...

I'm really excited about this plugin because it's exactly what our team needs... I'd be happy to hang out and help debugging if its useful at all. Here's a pastebin of my github-unity.log contents

https://pastebin.com/rR3WmiqG

**Comment by VirtualMaestro** [comment]
The same issue for me.
