### ISSUE TITLE
EndLayoutGroup: BeginLayoutGroup must be called first.

### ISSUE THREAD

**Issue by dwyermt** [github-for-unity/Unity#1047]
Unity 2019.1.1f1, MacOS 10.14.4

Receive this error after building blank project with this plugin. 

EndLayoutGroup: BeginLayoutGroup must be called first.
UnityEngine.GUILayout:EndVertical()
GitHub.Unity.Window:OnUI() (at C:/projects/unity/src/UnityExtension/Assets/Editor/GitHub.Unity/UI/Window.cs:506)
GitHub.Unity.BaseWindow:OnGUI() (at C:/projects/unity/src/UnityExtension/Assets/Editor/GitHub.Unity/UI/BaseWindow.cs:93)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

**Comment by Blend-arena** [comment]
I m also facing the same problem but not yet got the proper solution......

**Comment by raghavmittal101** [comment]
I am also facing the same problem on Windows10 Unity 2019 LTS
