### ISSUE TITLE
Multiple instances of unity for the same project complains about saving serialized files for another instance

### ISSUE THREAD

**Issue by hiradyazdan** [github-for-unity/Unity#1048]
### Prerequisites

There's no runtime error for this issue. But the backtrace log in the unity editor console is as follows:

```c#
You may not pass in objects that are already persistent

UnityEditorInternal.InternalEditorUtility:SaveToSerializedFileAndForgetInternal(String, Object[], Boolean)
UnityEditorInternal.InternalEditorUtility:SaveToSerializedFileAndForget(Object[], String, Boolean) (at /Users/builduser/buildslave/unity/build/Editor/Mono/InternalEditorUtility.bindings.cs:230)
GitHub.Unity.ScriptObjectSingleton`1:Save(Boolean) (at C:/projects/unity/src/UnityExtension/Assets/Editor/GitHub.Unity/ScriptObjectSingleton.cs:103)
GitHub.Unity.ManagedCacheBase`1:SaveData(DateTimeOffset, Boolean) (at C:/projects/unity/src/UnityExtension/Assets/Editor/GitHub.Unity/ApplicationCache.cs:235)
GitHub.Unity.GitAheadBehindCache:set_Ahead(Int32) (at C:/projects/unity/src/UnityExtension/Assets/Editor/GitHub.Unity/ApplicationCache.cs:693)
GitHub.Unity.<>c__DisplayClass78_0:<RepositoryManagerOnGitAheadBehindStatusUpdated>b__0() (at C:/projects/unity/src/GitHub.Api/Git/Repository.cs:302)
GitHub.Unity.<>c__DisplayClass6_0:<.ctor>b__0(Boolean) (at C:/projects/unity/src/GitHub.Api/Tasks/ActionTask.cs:292)
GitHub.Unity.ActionTask:Run(Boolean) (at C:/projects/unity/src/GitHub.Api/Tasks/ActionTask.cs:317)
GitHub.Unity.TaskBase:RunSynchronously() (at C:/projects/unity/src/GitHub.Api/Tasks/TaskBase.cs:299)
System.Threading.Tasks.SynchronizationContextTaskScheduler:PostCallback(Object)
GitHub.Unity.<>c__DisplayClass1_0:<Post>b__0() (at C:/projects/unity/src/UnityExtension/Assets/Editor/GitHub.Unity/Threading/SingleThreadSynchronizationContext.cs:20)
UnityEditor.EditorApplication:Internal_CallDelayFunctions()
```

### Description

Once firing multiple instance of unity/unity editor for the same project using symlink approach, the console starts collecting errors as above in a number of times on the second instance. It basically complains about having to save serialized files on another instance is not possible as they're already saved on the first instance.

### Steps to Reproduce

1. Following this [instruction](https://support.unity3d.com/hc/en-us/articles/115003118426-Running-multiple-instances-of-Unity-referencing-the-same-project) create a second project, having its directories/files symlinked to the first one (Assets, Project Settings, Library, Logs, Packages, etc..)
2. Have initial unity editor running
2. Open the second created project
3. Focus on the first project editor instance and you'll see the errors coming up
4. Optionally you can see more of the same errors happening once your second instance is running/playing the simulation.

**Expected behavior:**
No errors should be thrown and shown on the console.

**Actual behavior:**
The errors above are thrown in an excessive number of times and are not helpful, as they're not related to the work stream. Also, not sure if they cause git or editor conflicts.

**Reproduces how often:**
Every time

**Comment by shana** [comment]
I talked to unity devs about this, and this method of running multiple instances of the Unity Editor all pointing to the same project is definitely not supported, which is why this particular Unity API is breaking for you. The recommended way of doing this type of thing is to have multiple players, I'm told. I can't fix this particular error, it's Unity throwing, not us, and it'll cause problems for the GitHub plugin in general.

**Comment by hiradyazdan** [comment]
I would've suggested to only disable the plugin (as yourself mentioned on discord) if it detects there's another project (i.e. symlinked project) is opened. I personally fixed it by doing it in my project, it would be neat if it's done through the plugin automagically rather than me doing it. But thanks anyway for following that up 👍
