### ISSUE TITLE
Git Add fails due to too many files being added

### ISSUE THREAD

**Issue by thorade** [github-for-unity/Unity#105]
### Steps to Reproduce

1. Open existing Unity project
2. Assets -> Import Package -> Import github-for-unity v0.15
3. create new repo from github web ui
4. in Unity, initialize and push (successfull)
5. got to changes, see 759 changes, select all, type commit message, commit

** Behavior:** 
Typing the commit message is very slow.
Hitting the commit button seems to result in no action.

**Reproduces how often:**
100% reproducible in this project

### Additional Information

Here is my log:

[github-unity_log.txt](https://github.com/github-for-unity/Unity/files/1135863/github-unity_log.txt)

**Comment by shana** [comment]
@thorade Yeah, we're working on fixing performance problems in the Changes view (#23), it's not performing well when there's a lot of changes on screen 😢

**Comment by StanleyGoldman** [comment]
Hey @thorade you are hitting the performance problem that @shana is talking about, but there is also another issue that you've encountered here. We need to be smart about how we perform `git add`.

**Comment by StanleyGoldman** [comment]
If all files are being added we can shortcut with `git add .`
If a large subset of files are being added we need to batch the `git add` operation to not encounter this error.

**Comment by thorade** [comment]
Thanks. I'll try to work around it by manually adding the files in smaller chunks, tomorrow.

**Comment by thorade** [comment]
So, commiting worked, split it up into 7 commits.
But now pushing those 7 commits at once fails...
Just in case, here is a log:
[github-unity-log.txt](https://github.com/github-for-unity/Unity/files/1141764/github-unity-log.txt)

**Comment by StanleyGoldman** [comment]
Script to generate content for this bug

https://gist.github.com/StanleyGoldman/c84e31e174a91e1ff28770feaaf8da29

**Comment by thorade** [comment]
Just a note: 
In my case, ~650 of the ~750 files were from one asset (SteamVR) that is available for free on the asset store.
https://www.assetstore.unity3d.com/
Unfortunately, it is not possible to just define such dependencies (and their versions) and let Unity handle it as it would be done e.g. in Python or Ruby:
https://forum.unity3d.com/threads/asset-store-dependencies-handling.406090/#post-3142849

**Comment by StanleyGoldman** [comment]
Yea, that would be nice.

Either way, that script right there generates about 800 files and folders. Enough for me to see the problem you were talking about.

I have a PR #119 that reduces the amount of time it takes to generate the three by ~%80, but it's still kinda slow with 800 items in the tree.

I'm trying to fix the add functionality now...
