### ISSUE TITLE
Issue logging into github (Fatal: ArgumentException encountered. Login exception)

### ISSUE THREAD

**Issue by AnthonyLombard** [github-for-unity/Unity#1051]
### Prerequisites

- Be sure to run with tracing enabled to capture runtime details in the log file
- Include the log file in the PR.
  - On Windows, the extension log file is at `%LOCALAPPDATA%\GitHubUnity\github-unity.log`
  - On macOS, the extension log file is at `~/Library/Logs/GitHubUnity/github-unity.log`
  - On linux, the extension log file is at `~/.local/share/GitHubUnity/github-unity.log`

### Description

Cannot login to Github (Tried with browser but also get cannot validate token)

### Steps to Reproduce

1. Install plugin
2. hit sign in button
3. enter credentials (Tested and working on github)
4. Login failed error after a fews seconds

Login and be able to publish repo

stuck at login failed screen 

**Reproduces how often:** Every time
[github-unity.log](https://github.com/github-for-unity/Unity/files/3182037/github-unity.log)

### Additional Information
[github-unity.log](https://github.com/github-for-unity/Unity/files/3182046/github-unity.log)

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by Usmankha2020** [comment]
same issue

**Comment by mediajolt001** [comment]
Same issue.

**Comment by shana** [comment]
@mediajolt001 Your log indicates that git is unusable in your system:

```
190522-16:43:10.693 TRACE [80] <ProcessWrapper>                    Running '/usr/bin/git --version'
190522-16:43:10.726 TRACE [84] <ProcessWrapper>                    xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
```

Github for Unity doesn't install git on Mac, it relies on whatever is available on the system, so you need to make sure git works first.

**Comment by shana** [comment]
@Anthonipples In your case, it looks like you're using a git that's configured to run the Git Credential Manager tool to manage credentials (https://github.com/microsoft/Git-Credential-Manager-for-Windows), and that tool is throwing an exception when we try to set credentials through it:

```
190515-11:57:07.733 TRACE [245] <ProcessWrapper>                    Running 'C:\Program Files\Git\cmd\git.exe credential-manager erase'
190515-11:57:07.831 TRACE [241] <ProcessWrapper>                    Fatal: ArgumentException encountered.
190515-11:57:07.946  WARN [245] <LoginManager>                      Login Exception
```

Try switching to the bundled git in the Settings view of GitHub for Unity (the bundled git is preconfigured to use `wincred` instead of `manager` as the git credential helper tool. Alternatively, you can try switching to `wincred` on your system git by doing `git config --global credential.helper wincred` on the command line.

**Comment by Rexogamer** [comment]
My friend @GhashtoDersA is getting this error when he tries to log in (he’s tried logging in on browser): HttpError: write EPROTO
101057795:error:04091068:rsa routines:INIT_RSA_VERIFY:bad signature:openss|\crypto\rsa\rsa sign.c:278:

**Comment by MarkoShiva** [comment]
Same here

**Comment by MarkoShiva** [comment]
I get error.

**Comment by MarkoShiva** [comment]
same here

**Comment by babazu** [comment]
same here

**Comment by crkatz06** [comment]
Same, I get the HttpError: write EPROTO 101057795 etc... I am running Unity 2020.1.3f1, just installed github for unity an can't sign in. Also running win10. I tried git config --global credential.helper wincred it states "git" is not recognized as an internal or external command, operable program or batch file.
