### ISSUE TITLE
Having issues with git on unity 

### ISSUE THREAD

**Issue by Spagpix** [github-for-unity/Unity#1064]
I download git for unity from the asset store with a project open and under window git simply does not show up? I'm at a loss as to how to fix this its 2019.1.4f version of unity? Any suggestions? 

### Prerequisites

- Be sure to run with tracing enabled to capture runtime details in the log file
- Include the log file in the PR.
  - On Windows, the extension log file is at `%LOCALAPPDATA%\GitHubUnity\github-unity.log`
  - On macOS, the extension log file is at `~/Library/Logs/GitHubUnity/github-unity.log`
  - On linux, the extension log file is at `~/.local/share/GitHubUnity/github-unity.log`

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by sarrowsmith** [comment]
Try this:
1. Editor->Project Settings->Editor: Version Control/Mode = Visible Meta Files
2. File->Save Project
3. Quit Unity and re-open the project.

**Comment by Spagpix** [comment]
Thanks mate
