### ISSUE TITLE
Issue on Mac OS X with libsfw.bundle

### ISSUE THREAD

**Issue by aproctor** [github-for-unity/Unity#1065]
### Description
After Github for Unity is added to a Unity project, you will be prompted multiple times with the OS X `App can't be opened because it is from an unidentified developer` regarding `libsfw.bundle`.  This happens every time you try to play your project. 

This is due to settings on Gatekeeper that prevent applications from running unless they're from the App Store or an Identified Developer.

### Steps to Reproduce

1. Ensure your Security & Privacy settings in OS X are set to allow apps only from "App Store and Identified Developers" or "App Store"
2. Import Github for Unity into your project
3. (Optional?) Open up the GitHub window and connect to a repo
4. Run your project in any scene

**Expected behavior:** The game to play without any prompts

**Actual behavior:** Multiple prompts pop up complaining that libsfw.bundle will not be opened because it's an unidentified developer.

**Reproduces how often:** 100%
If you do launch with Allow app downloaded from "Anywhere", it appears that reproduction rate may be 0% once libsfw.bundle has been launched successfully once.

### Additional Information
On earlier versions of OS X you can change your security settings to allow apps from anywhere to run, but as of Sierra this is no longer an option in the settings window.

There is a work around to disable Gatekeeper via the terminal, but it's not very obvious. You must run `sudo spctl --master-disable`.  This will re-add the "Anywhere" option to your security settings window.

Also note that most applications that trip this setting up will have an option to "open anyways" within the OS X security window.  But it won't do anything meaningful when you click "open anyways", and it won't be white listed for future launch requests.

**Comment by shana** [comment]
Hmmm, this is a problem. I'll need to figure out how to sign the library.

**Comment by faaip** [comment]
Any news on this one? Thanks.

**Comment by pt-paulrahme** [comment]
Bump on this? We're looking to integrate this across a large team, but can't have every Mac user getting prompted 4 times in a row whenever they open the Unity project, especially the way the default option (if you hit Enter) being to move it to the bin.

![Screenshot 2020-06-03 at 09 18 14](https://user-images.githubusercontent.com/62744502/83613271-758da900-a57b-11ea-9433-19c81e50cb63.png)

**Comment by pt-paulrahme** [comment]
Update: Looks like you can go into System Preferences and click "Allow Anyway:
![image](https://user-images.githubusercontent.com/62744502/83614408-129d1180-a57d-11ea-8c49-9227cac1d39c.png)
...then you get an "Open" button on the dialog:
![image](https://user-images.githubusercontent.com/62744502/83614454-1d57a680-a57d-11ea-969e-080a138b8b23.png)
and after this it shouldn't prompt you again.

**Comment by jeffWelling** [comment]
Any word on this yet?
Some enterprise environments forbid the use of the Allow Anyway button for security reasons, I hope the idea isn't to just ignore those environments entirely?

**Comment by shana** [comment]
This project is not maintained anymore. The replacement is Git for Unity, at https://github.com/spoiledcat/git-for-unity. If you have GitHub for Unity in your project, remove it first and then install the [Git for Unity](https://github.com/spoiledcat/git-for-unity) package, see the README in the link for instructions.

I'll figure out over there how to get the signing done for the library.
