### ISSUE TITLE
Cant access Github Window

### ISSUE THREAD

**Issue by 16097ag** [github-for-unity/Unity#1069]
### Description
After installing GitHub using the asset store on unity It was downloaded to my project and into my plugin folder. However the actual window never opened besides preferences and looking in my windows toolbar I cant see GitHub anywhere. I tried to deleting it and reinstalling as well as closing unity and reopening but that didn't help. I'm using Unity version 2018.3.6f1.

Steps to reproduce:
1. Open unity version 2018.3.6f1 and create a project
2. Open the asset store and download GitHub
3. Check too see if it works

**Comment by LiamKarlMitchell** [comment]
Same on 2020.1.0a16.1913
It worked the first time, but was stuck on Initializing Project spinner thing.

After I logged in I wanted to get that working so I saved, closed unity and reopened and now the Plugin is not loading.

**Comment by cdcv** [comment]
+1

**Comment by yash14700** [comment]
same here
