### ISSUE TITLE
Change usages of GUI.enabled to EditorGUI.Begin/End-DisableGroup

### ISSUE THREAD

**Issue by StanleyGoldman** [github-for-unity/Unity#107]
As @CapnRat commented [here](https://github.com/github-for-unity/Unity/pull/95#discussion_r125827605):

>Should get into the habit of using EditorGUI.Begin/EndDisabledGroup rather than setting GUI.enabled directly. Those utility methods handle nesting properly. (There's also EditorGUI.DisabledScope, for an IDisposable way of doing things.)

**Comment by MunchyYDL** [comment]
I will look at fixing those.

**Comment by StanleyGoldman** [comment]
Cool beans. Let us know if you need help.
You can find us in gitter or discord.
