### ISSUE TITLE
Cannot Login to GitHub

### ISSUE THREAD

**Issue by JayVanSchaick** [github-for-unity/Unity#1071]
### Prerequisites

[Here is my log file.](https://github.com/github-for-unity/Unity/files/3503938/github-unity.log)

### Description

I am unable to login to GitHub through the sign in window. It tells me "Login Failed".  

### Steps to Reproduce

1. [First Step] Download and install GitHubForUnity
2. [Second Step] Click on the "Sign In" button
3. [Third Step] Enter username and password

**Expected behavior:** To login to my GitHub account

**Actual behavior:** Error message "Login Failed".  

**Reproduces how often:** Every Time 

### Additional Information

[1.] I have a GitHub account that works (I tested it on GitHub).
[2.] The Command line does not work when selecting it in Unity windows. Just a blank screen comes up.
[3.] The GitHubForUnity window extracts every time the project is open.  
[4.] The setting options are not saving.
[5.] I have tried every fix I could from the other threads with similar problems.
[6.] I'm using windows 10 and Unity 2019.1.4

**Comment by DouglasUrner** [comment]
I have a similar set of problems. After installing GitHub for Unity version 1.4.0 on Windows 10 with Git version 2.20.1.windows.1 installed in C:\Program Files\Git. When I run git commands using the Git Bash command line they work. However, with GitHub for Unity I run into the following problems:

* Running **Window > GitHub Command Line** brings up a blank window with a black background titled **C:\WINDOWS\system32\cmd.exe**. There is no prompt and I can't type commands.
* I'm unable to sign in to GitHub. We are behind a firewall that intercepts HTTPS traffic. So I use **git config --global http.sslverify false** to work around the firewall. This works on the command  line and in Rider, Atom, and GitHub Desktop. With GitHub for Unity I get the message "Error: self signed certificate in certificate chain".

Log file: [github-unity.log](https://github.com/github-for-unity/Unity/files/3633218/github-unity.log)

**Comment by jbga** [comment]
I have a similar problem. 
GitHub for Unity version 1.4.0 on Ubuntu 18.04.4 LTS with Git version 2.17.1.
I have tried to sign in with credentials tested on github and also tried to sign in using the browser. In this last case it said that the token was invalid.
Log file: [github-unity.log](https://github.com/github-for-unity/Unity/files/4895893/github-unity.log)

**Comment by Marthinka** [comment]
I had the same issue but after I went into the settings tab and clicked "Find system git" followed by "Save" it worked just fine.

Perhaps the error message can be changed to make it clearer that people need to fix the settings before they can log in.

**Comment by 0x006E** [comment]
I had the same problem. I solved by clicking "Find system git" followed by going to Edit->Preferences->External Tools and setting external editor to vscode(in my case)

**Comment by janithcooray** [comment]
> I had the same problem. I solved by clicking "Find system git" followed by going to Edit->Preferences->External Tools and setting external editor to vscode(in my case)

This fixed my issue. but since I'm using Linux, Window > Github > "Settings" Tab inside the Github window > Click "Find system git" and "Save" then restart Unity.

**Comment by theresaway** [comment]
Same issue, but sign in says "Not found." any fix?
