### ISSUE TITLE
[Help] Login stoped working after upgrade to latest Unity and github Unity

### ISSUE THREAD

**Issue by Rubinhuang9239** [github-for-unity/Unity#1076]
### Description

Unity Github was working great, till I update unity to 2019.2.6f, and Unity Github 1.40.
I was on MacOS 10.14.6, Git version 2.21.0 (Apple Git-122)

**2-FA Login:**
1. Login with Unity Github UI with correct username and creds.
2. Input 2 factors token.

<img width="307" alt="Screen Shot 2019-09-22 at 1 36 37 PM" src="https://user-images.githubusercontent.com/8656768/65627633-c6d1ab80-df9d-11e9-96bf-efcc607c3906.png">

------------------------

**Login With Browser**
1. Login with username and creds .... good 👍🏻.
2. 2-FA token .... good 👍🏻.
3. Signin ognizations .... good 👍🏻. 
4. then shows an empty page .... stuck ❌:
url: `http://localhost:42424/callback?code=34218e9c1466274d...3&state=351b7094-cee8-4db1-8535-6f7795887...`
In console: 
<img width="858" alt="Screen Shot 2019-09-22 at 1 37 24 PM" src="https://user-images.githubusercontent.com/8656768/65627805-2760e880-df9e-11e9-8a7e-b03cf958f20b.png">

5. Back to Unity UI:
<img width="302" alt="Screen Shot 2019-09-22 at 1 37 14 PM" src="https://user-images.githubusercontent.com/8656768/65627968-7870dc80-df9e-11e9-9a20-038541f63f2a.png">

Any help is greatly appreciated!!

**Comment by shana** [comment]
@Rubinhuang9239 Hmmm yeah that's not good, I'll run some tests.

In the meantime, you can make it work by adding a personal auth token directly in the osx keychain, and git in Unity will use that without you having to login through it. The login is just a helper to get a personal access token into the keychain, but you can always set it up yourself and skip the login.

First, you need to create a personal auth token, following these instructions: https://help.github.com/en/articles/creating-a-personal-access-token-for-the-command-line. You'll want the "repo" and "user" scopes in it.

Then, open the terminal on Mac, and make sure that you have the osx keychain credential helper for git configured. GitHub for Unity does this for you so you should be all set to go, but you can double check by following these instructions: https://help.github.com/en/articles/caching-your-github-password-in-git

Once you have the token and you've checked that the helper is set as default, in the Terminal, go to your repository on the filesystem, and run `git fetch`. This will prompt for user and password. Fill out your GitHub handle for username, and the token you created as the password. These will be stored in the osx keychain, and GitHub for Unity will use them to do git operations.

**Comment by Rubinhuang9239** [comment]
@shana 
Thanks for your respond, I will try these steps soon.
