### ISSUE TITLE
Complete reset option?

### ISSUE THREAD

**Issue by jwvanderbeck** [github-for-unity/Unity#1078]
### Prerequisites

- Be sure to run with tracing enabled to capture runtime details in the log file
- Include the log file in the PR.
  - On Windows, the extension log file is at `%LOCALAPPDATA%\GitHubUnity\github-unity.log`
  - On macOS, the extension log file is at `~/Library/Logs/GitHubUnity/github-unity.log`
  - On linux, the extension log file is at `~/.local/share/GitHubUnity/github-unity.log`

### Description

I basically made a huge mess and need to reset everything.  I was trying out the new Unity Collab again which turned out to still be a hot mess.  So I removed Collab and installed Github for Unity, setup a reop and pushed to Github.  But then I realized that for some reason, probably Collab, there was a gitignore in my Assets directory so basically nothing got pushed.

I deleted that ignore file but Git had already been ignoring so I was kind of stuck.  I then deleted the repo from online and deleted .git from my project and wanted to just start over.

Mu hope was when I went back to Unity the GitHub for Unity plugin would see that no git repo existed anymore and would let me start over initializing a new one.

Unfortunately this doesn't seem to be the case as now its stuck in some bad state where it thinks there is still a repo when there isn't one and I can't find a way to "reset" it.
[github-unity.log](https://github.com/github-for-unity/Unity/files/3692095/github-unity.log)

**Comment by jwvanderbeck** [comment]
Ok just completely removed the plugin and re-added it.  It seems to have cleared everything and properly sees the project as having no repo and let's me initialize it.

So that's fixed.

**Comment by ericspt** [comment]
> Ok just completely removed the plugin and re-added it. It seems to have cleared everything and properly sees the project as having no repo and let's me initialize it.
> 
> So that's fixed.

People reading this, don't forget to delete .git as well for a complete reset.

So, delete the .git in the project folder + Github.meta and Github from Assets/Plugins. 

Deleting just the plugin won't do the trick.

**Comment by jwvanderbeck** [comment]
The problem in his case was the opposite.  I had deleted the .git directory, deleting the repo, but the plugin still thought it was connected to said repo.  To fix it I had to remove the plugin and re-add it.

It would be more user friendly though if there was just a reset option in the plugin or at the very least the plugin was smart enough to see that the local repo had been deleted.

**Comment by ericspt** [comment]
> The problem in his case was the opposite. I had deleted the .git directory, deleting the repo, but the plugin still thought it was connected to said repo. To fix it I had to remove the plugin and re-add it.
> 
> It would be more user friendly though if there was just a reset option in the plugin or at the very least the plugin was smart enough to see that the local repo had been deleted.

I fully agree.
