### ISSUE TITLE
First time using plugin, all files have been deleted after crash

### ISSUE THREAD

**Issue by Jordan-Bear** [github-for-unity/Unity#1080]
Hi, 

using your plugin (and git) for the first time, and have seem to have lost my entire project within three clicks.

To quickly go over what I did:

Imported your plugin

Created a new branch "liveChanges"
committed all files to master branch (I assumed this is how you save your work to a branch)
switched to livechanges to start editing things

at this point unity threw up an error that a file was missing and then crashed. When I rebooted, it couldn't even tell which version of unity the project had been created in. When I opened the project, all my files were gone- literally everything. Models, textures, c# scripts, everything.

Please can you advise how I can get my files back? If there is anything I can attach to this issue that will help please let me know- as I said, this is my first time using git, so I'm very new to this. If you can just even point me in the direction of where your plugin was attempting to move them to, that would be great- I just want my work back.

**Comment by Jordan-Bear** [comment]
Just looked through my project and the .git folder that's been created trying to understand how this works- it's ~700mb in size which sounds about right, and most of that size is coming from a folder 'LFS', which I seem to remember reading is how git stores large files. Everything in there is just incomprehensible numbers and letters, which is I'm assuming how git saves and restores the information for my project. 

Can anyone give me the magic sequence of buttons I have to press to make it turn that pile of numbers and letters back into my .blend files and scenes?

**Comment by shana** [comment]
With a .git folder that big, your files are in there somewhere, and you might just be on the wrong branch. What likely happened is that the branch you created was pointing at your empty project, then you commited your changes and switched to the new branch, which was still at the point where you had nothing in your project.

Your changes are probably all in master. Switch back to the master branch, and you should get them back.

If you prefer a more step by step check of the state of your repo, you'll need a command line with git in it, so install git for windows (I assume you're on windows?) first and then open a command line. Go to where your project is on the command line, and doublecheck which branch you're on with `git branch`.

Then run `git branch -l` to see what branches you have locally. That will likely list `master` and `liveChanges`. Then run `git log master` and `git log liveChanges` (basically `git log [branch]` for every local branch that was listed before). See which one has the commit that you did with your work. Switch to that branch with `git checkout [branchname]`

**Comment by shana** [comment]
@jordan-bear Also, might be useful to install a separate visual git client so you can see more of what's going on, the Unity client is somewhat limited. GitHub Desktop or GitKraken are good options. Sorry you got tripped up by the unity client on your first go, not the best first experience 😕

Apologies for any typos or curtness, typing on the phone,

**Comment by Jordan-Bear** [comment]
Thanks so much for the quick response!
Had to dash shortly after posting but I'll try your suggestions when I'm
back at the machine- I already have github desktop though, and after
dragging the . Git folder onto it, it immedietly comes up saying that it's
lost the folder, and says it was last seen at the location the folder is
currently in.
