### ISSUE TITLE
Login failed. Linux. DllNotFoundException

### ISSUE THREAD

**Issue by MarkoShiva** [github-for-unity/Unity#1091]
### Prerequisites

  - On linux, the extension log file is at `~/.local/share/GitHubUnity/github-unity.log
[github-unity.log](https://github.com/github-for-unity/Unity/files/4017220/github-unity.log)
`
Log is attached

### Description

Login failed in the Unity and in the browser. 

### Steps to Reproduce

1. Install your extension
2. Try to login

**Expected behavior:** [What you expect to happen]

Login succeed/

**Actual behavior:** [What actually happens]
Throw a error of dll not found.

**Reproduces how often:** [What percentage of the time does it reproduce?]
Always

### Additional Information
Error in console:
```
DllNotFoundException: libMonoPosixHelper.so
Mono.Unix.Native.Syscall..cctor () (at <db7fe3a37f9a4b359b9caec748d31b83>:0)
Rethrow as TypeInitializationException: The type initializer for 'Mono.Unix.Native.Syscall' threw an exception.
Mono.Unix.UnixPath.TryReadLink (System.String path) (at <db7fe3a37f9a4b359b9caec748d31b83>:0)
Mono.Unix.UnixPath.ReadSymbolicLink (System.String path) (at <db7fe3a37f9a4b359b9caec748d31b83>:0)
Mono.Unix.UnixPath.GetRealPath (System.String path) (at <db7fe3a37f9a4b359b9caec748d31b83>:0)
Mono.Unix.UnixPath.GetCompleteRealPath (System.String path) (at <db7fe3a37f9a4b359b9caec748d31b83>:0)
GitHub.Unity.Extensions.Resolve (GitHub.Unity.NPath path) (at C:/projects/unity/src/GitHub.Api/IO/NiceIO.cs:1214)
GitHub.Unity.ProcessEnvironment.Configure (System.Diagnostics.ProcessStartInfo psi, GitHub.Unity.NPath workingDirectory, System.Boolean dontSetupGit) (at C:/projects/unity/src/GitHub.Api/Process/ProcessEnvironment.cs:44)
GitHub.Unity.ProcessManager.RunCommandLineWindow (GitHub.Unity.NPath workingDirectory) (at C:/projects/unity/src/GitHub.Api/Process/ProcessManager.cs:104)
GitHub.Unity.Window.GitHub_CommandLine () (at C:/projects/unity/src/UnityExtension/Assets/Editor/GitHub.Unity/UI/Window.cs:71)
```

Any additional information, configuration or data that might be necessary to reproduce the issue.
Nothing special I run Archlinux and the issue happens every time with that extension.

[github-unity.log](https://github.com/github-for-unity/Unity/files/4017224/github-unity.log)

**Comment by MarkoShiva** [comment]
@leereilly @StanleyGoldman @donokuda 
Can anyone check this issue? Do you guys support at all Linux versions of Unity?
Waiting for response
Thanks

**Comment by kuylar** [comment]
I had the same problem. Have you tried setting the git path in settings? That solution worked for me.

**Comment by MarkoShiva** [comment]
> I had the same problem. Have you tried setting the git path in settings? That solution worked for me.

Where. Which OS. Which version of the extension? Setting settings by hand do not help. They do not package dll for linux.

**Comment by tijanirf** [comment]
> I had the same problem. Have you tried setting the git path in settings? That solution worked for me.

This solution works for me @MarkoShiva.

**Comment by MarkoShiva** [comment]
New version of unity 2020.1.5f addon works. However on 2019 version not.

**Comment by MarkoShiva** [comment]
I will close the issue but feel free to reopen it if again incompatibility with version of Unity for Linux appear.
