### ISSUE TITLE
Locked files locked for lock requester, release option not available

### ISSUE THREAD

**Issue by BlurEffect** [github-for-unity/Unity#1095]
### Description

Hi everbody,
I have added the Github for Unity plugin to one of my projects (which was already under source control) and while locking seems to work mostly fine, there still is a weird issue with it. My repository is not on GitHub but on Bitbucket within a corporate environment and I am using Unity 2019.3 (but I'm having the same issue with 2019.2). Requesting a lock works fine and it will show me the little icon next to the locked file and the lock will appear in the list of locks. However, when right-clicking the locked element, the "release" option is greyed out and I can only force unlock it, although I am the person that requested the lock. I assume, that I should be able to simply release the lock. In addition, when locking a vfx graph in Unity with your plugin (and possibly other elements?), I am not able to edit the graph since I am getting a "Asset is locked" notification instead of the graph being displayed. Can you please help me with this issue and provide some assistance? As mentioned above, it's a corporate environment with a proxy server and stuff but all the git stuff works fine on the command line.

### Steps to Reproduce

1. Open Unity project
2. Request lock on object
3. Try to release lock/edit locked element (for instance vfx graph)

**Expected behavior:** Since I locked the file, I should be able to still edit it and to release the lock

**Actual behavior:** Release option is greyed out (force release is working though) and element is locked for me although I requested the lock (at least I cannot edit a locked vfx graph, I didn't try this for many different types of objects)

**Reproduces how often:** Every time

### Additional Information

Here is the log file (opening the project, requesting a lock and eventually force releasing it):

[log.log](https://github.com/github-for-unity/Unity/files/4163950/log.log)

**Comment by Gatschknoedel** [comment]
Have you been able to resolve this issue? I unfortunately have the same problem with my project using Unity 2018.4.4f1
