### ISSUE TITLE
Can unity run on raspberry pi 4?

### ISSUE THREAD

**Issue by penneShells** [github-for-unity/Unity#1099]
Hello, i am trying to find a good game engine for the raspberry pi 4, and unity seems to be quite good, but i cant see anywhere if it works on linux arm and rapberry pi.
Thanks.

**Comment by BradenWoolley** [comment]
Unfortunately the Unity Engine requires x86 architecture. So a proper Linux PC will do but thus far it seems as though ARM is only supported for player builds, not the engine itself. You're probably better off trying the LÖVE engine for the Pi, Unity is a bit too much for the poor thing to run.

**Comment by penneShells** [comment]
Okay, thanks for the help!
