### ISSUE TITLE
[GitHub API] Deprecation notice for authentication via URL query parameter

### ISSUE THREAD

**Issue by nickserv** [github-for-unity/Unity#1102]
I ran GitHub for Unity normally and got the following email from GitHub:

> **[GitHub API] Deprecation notice for authentication via URL query parameters**
> 
> Hi @nickmccurdy,
> 
> On April 19th, 2020 at 07:36 (UTC) your personal access token (git @ nick-laptop) using GitHubUnity/1.4.0 was used as part of a query parameter to access an endpoint through the GitHub API:
> 
> https://api.github.com/user
> 
> Please use the Authorization HTTP header instead, as using the `access_token` query parameter is deprecated. If this token is being used by an app you don't have control over, be aware that it may stop working as a result of this deprecation.
> 
> Depending on your API usage, we'll be sending you this email reminder on a monthly basis for each token and User-Agent used in API calls made on your behalf.
> Just one URL that was accessed with a token and User-Agent combination will be listed in the email reminder, not all.
> 
> Visit https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param for more information about suggested workarounds and removal dates.
> 
> Thanks,
> The GitHub Team

**Comment by Zhal73** [comment]
Same problem here, I had this message today. Any suggestion?

**Comment by Draice** [comment]
Also happening for me. Could whoever owns this project update this to support the latest Github API, please and thanks!

**Comment by Combotron** [comment]
+1
