### ISSUE TITLE
Show Diff Shows Nothing

### ISSUE THREAD

**Issue by bilal-guvenc** [github-for-unity/Unity#1111]
### Prerequisites

- Be sure to run with tracing enabled to capture runtime details in the log file
- Include the log file in the PR.
  - On Windows, the extension log file is at `%LOCALAPPDATA%\GitHubUnity\
[github-unity.log](https://github.com/github-for-unity/Unity/files/4778393/github-unity.log)
github-unity.log`
  - On macOS, the extension log file is at `~/Library/Logs/GitHubUnity/github-unity.log`
  - On linux, the extension log file is at `~/.local/share/GitHubUnity/github-unity.log`

### Description

Show Diff Shows Nothing

### Steps to Reproduce

1. [right click a cs file and choose show diff in changes tab]
2. [wait]
3. [wait more :)]

**Expected behavior:** [diffs are shown]

**Actual behavior:** [reads history or reads locks]

**Reproduces how often:** [always]

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.
visual studio 2019 is connected to unity but it is closed currently

**Comment by huin** [comment]
I just had a problem that seems to be the same as this. I then checked which diff program that Unity itself had configured, and it didn't have one. So I installed WinMerge, restarted Unity, and Unity picked it up as the default. Asking Github for Unity to show diffs then worked, displaying the diff with WinMerge.

Regardless of if that resolves this problem for others, I think that a helpful error message would be beneficial here to prompt people to install and select a diff program for Unity - the silent failure was confusing.
