### ISSUE TITLE
Error reverting commit

### ISSUE THREAD

**Issue by HernandoNJ** [github-for-unity/Unity#1118]
When trying to make a commit, sometimes appears the next message 
![image](https://user-images.githubusercontent.com/40243888/89910064-62b7d600-dbb5-11ea-96a8-e0fa582aa729.png)

And without doing any change, some files appear to be changed
![image](https://user-images.githubusercontent.com/40243888/89910119-75caa600-dbb5-11ea-91e8-bc4873d8daed.png)

Attaching editor log file

[Editor.log](https://github.com/github-for-unity/Unity/files/5057537/Editor.log)

**Comment by Glacier1010** [comment]
Do you have anything named SourceAssetDB?
If you do try maybe deleting it

**Comment by HernandoNJ** [comment]
Please remove, delete this issue
