### ISSUE TITLE
No Github option in window dropdown

### ISSUE THREAD

**Issue by Woolton** [github-for-unity/Unity#1119]
On Windows. No "GitHubUnity" folder was generated upon installing the package like the Unity youtube tutorial claimed would occur.

### Description

 No GitHubUnity folder exists, Github is not an option on the Window Dropdown.

### Steps to Reproduce

import github unity package

**Expected behavior:** Window > Github > github window opens in editor

**Actual behavior:** Window > Github option nonexistant.

**Reproduces how often:** 100%
![image](https://user-images.githubusercontent.com/36093760/90202281-48474d80-ddab-11ea-919a-8099803c120a.png)
![image](https://user-images.githubusercontent.com/36093760/90202309-59905a00-ddab-11ea-99da-f0216a0a8140.png)

**Comment by resonant-jovian** [comment]
Same for me

**Comment by vpeter1119** [comment]
I also have the same issue with any new project I'm trying to create in any any editor version. It works fine in previous projects, but not in new ones and can't figure out a way to solve it.

**Comment by ThanksSkeleton** [comment]
I encountered the same symptoms - and was able to solve it. 

I found there is a quirk with Unity's extension model - if your project's scripts cannot compile, it will not compile/run extension scripts. 

By ensuring that all of my project's scripts compile, the extension loaded successfully.
