### ISSUE TITLE
Cannot sign in

### ISSUE THREAD

**Issue by AmaliJD** [github-for-unity/Unity#1120]
### Description

When I sign in, I get an error saying

HttpError: write ERROTO
101057795:error:04091068:rsa
routines:INT_RSA_VERIFY:bad
signature:openssl\crypto\rsa\rsa_sign.c:278:

When I try "sign in with your browser", the page lands on localhost:42424/callback?code=cb82056795d7e7cdfc3f&state=f039d91c-ac3c-4192-bf37-42ad7edd9de6

I have other issues such as pushes not being shown in the repo and whatnot, but for now I'll assumed they all stem from this initial problem of not being able to sign in, so i need to fix that first.

### Steps to Reproduce

1. Click "sign in" in the GitHub window
2. Enter correct credentials

**Expected behavior:** Sign in succesful

**Actual behavior:** Error message

**Reproduces how often:** Every time

### Additional Information

not exactly sure what logs I need to show, here's what's in github-unity.log after trying to login about 3 times

200821-14:11:31.296  INFO [ 1] <Global>                            Initializing GitHubForUnity:'v1.4.0' Unity:'v2019.3.1f1'
200821-14:14:29.310  WARN [46] <UsageTracker>                      Error sending usage:"System.Exception" Message:"System.Exception: Post Usage failed: Error: write EPROTO 101057795:error:04091068:rsa routines:INT_RSA_VERIFY:bad signature:openssl\crypto\rsa\rsa_sign.c:278:
101057795:error:1408D07B:SSL routines:ssl3_get_key_exchange:bad signature:openssl\ssl\s3_clnt.c:2032:

  at GitHub.Unity.MetricsService.PostUsage (System.Collections.Generic.List`1[T] model) [0x000db] in C:\projects\unity\script\src\MetricsService.cs:59 
  at GitHub.Unity.UsageTrackerSync.SendUsage () [0x000f5] in C:\projects\unity\src\GitHub.Api\Metrics\UsageTracker.cs:111 "
200821-14:14:44.201  INFO [ 1] <Global>                            Trace Logging Enabled
200821-14:14:46.940 TRACE [68] <ProcessWrapper>                    Running 'C:\Users\hp\Documents\Unity\2019.3.1f1\Editor\Data\Tools\nodejs\node.exe "C:\Users\hp\AppData\Local\GitHubUnity\octorun\src\bin\app.js" login'
200821-14:23:08.654 TRACE [ 1] <GitLocksCache>                     needsInvalidation isInitialized:True timedOut:True
200821-14:23:08.654 TRACE [71] <ProcessWrapper>                    Running 'C:\Program Files\Git\cmd\git.exe -c i18n.logoutputencoding=utf8 -c core.quotepath=false --no-optional-locks status -b -u --porcelain'
200821-14:23:09.389 TRACE [71] <ProcessWrapper>                    Running 'C:\Program Files\Git\cmd\git.exe -c i18n.logoutputencoding=utf8 -c core.quotepath=false --no-optional-locks status -b -u --porcelain'
200821-14:23:12.529 TRACE [82] <ProcessWrapper>                    Running 'C:\Users\hp\Documents\Unity\2019.3.1f1\Editor\Data\Tools\nodejs\node.exe "C:\Users\hp\AppData\Local\GitHubUnity\octorun\src\bin\app.js" login'
200821-14:23:46.683 TRACE [83] <ProcessWrapper>                    Running 'C:\Users\hp\Documents\Unity\2019.3.1f1\Editor\Data\Tools\nodejs\node.exe "C:\Users\hp\AppData\Local\GitHubUnity\octorun\src\bin\app.js" login'

[github-unity.log](https://github.com/github-for-unity/Unity/files/5110683/github-unity.log)

**Comment by Glacier1010** [comment]
Have you tried to re downloading Unity Hub and your Browser?

**Comment by QuantDeveloperUSA** [comment]
Same issue. Following this post

**Comment by Tobias-Bonsack** [comment]
Same issue

**Comment by AgrMayank** [comment]
Do any other people have the same issue?
- Facing this in Unity 2020.1.17f1
- Sign In via browser isn't working
- Sign In via Personal Token isn't working as well
- Open Github Command Line option is closing prompt after a split second

**Comment by Lex1con** [comment]
Same issue

**Comment by yitnekiV** [comment]
Same issue

**Comment by bmateus** [comment]
Same issue here - on Unity 2020.3.24f1

**Comment by nrchan** [comment]
same here

**Comment by Mrjojosa** [comment]
same issue - Unity 2020.3.28f1
