### ISSUE TITLE
Memory Leaks in IOS

### ISSUE THREAD

**Issue by pixforger** [github-for-unity/Unity#1122]
### Description

Memory Leaks in IOS

### Steps to Reproduce

1. create a new test project with two new scene
2. create an emty Canvas and add a Unity.ui button
3. on button interaction, navigate to 2nd scene
4. export IOS project in debug mode
5. Ran the app in Iphone 8 - IOS 13.3
6. open debug navigator and select memory tab

<img width="849" alt="image" src="https://user-images.githubusercontent.com/3796409/91491317-de867380-e881-11ea-821e-db65ddb7292c.png">

7. transfer the profile in instruments 

<img width="1343" alt="image" src="https://user-images.githubusercontent.com/3796409/91491339-e6461800-e881-11ea-96e1-374a27d581fc.png">

**Expected behavior:** No memory leak

**Actual behavior:** memory leaks

**Reproduces how often:** on every interaction within the app

### Additional Information
Unity 2020.1.2f1 (pro)
IPhone 8 
IOS 13.3

**Comment by shana** [comment]
This is a Unity issue, not a GitHub for Unity issue.
