### ISSUE TITLE
GitHub for Unity with the New Input System (Input System 1.0.0)

### ISSUE THREAD

**Issue by heimhofc** [github-for-unity/Unity#1123]
### Prerequisites
The log file: 
<img width="1384" alt="Unity Error logfile" src="https://user-images.githubusercontent.com/69513078/91570755-6f268780-e946-11ea-9ebb-f8b294b2d1d4.png">

### Description

These errors come up when I try to use GitHub for Unity (V1.4, Unity Version 2019.4.9f) with the new input system (Input System 1.0.0). I had no issues with the old input system.

This error first comes up:
![Unity Error 02](https://user-images.githubusercontent.com/69513078/91566928-a3994400-e944-11ea-9e5c-34c9a921acdc.png)

Then this error repeats constantly and spams the console:
![Unity Error 01](https://user-images.githubusercontent.com/69513078/91566918-a005bd00-e944-11ea-9b78-5647ababceaa.png)

### Steps to Reproduce

1. Create new unity project (Version 2019.4.9f)
2. Switch to new input system
3. setup GitHub for Unity including the remote repository
4. create a new local branch
5. close and reopen project

**Expected behavior:** GitHub works normally

**Actual behavior:** Console is getting spammed with the following errors:
- ArgumentException: You can only call GUI functions from inside OnGUI. (only once)
- Exception: Style.Draw may not be called with GUIContent that is null. (keeps repeating)

**Reproduces how often:** every time

### Additional Information
I had the issue with my project when I set up GitHub for Unity, but it reproduces also with a basically empty project.

**Comment by shana** [comment]
Ah, it's likely not the input system, just things getting cached in the wrong place. I'm not likely to do fixes to this project, but if this is still happening in the Unity fork over at https://github.com/Unity-Technologies/Git-for-Unity, I can fix it there. It's basically the same minus the "login to github" part, in package form, with a lot of fixes on top (this might have already been fixed there, I can't remember).

You can try and grab the [latest release](https://github.com/Unity-Technologies/Git-for-Unity/releases) from there, just download the first tgz on the asset list (`com.unity.git-X.X.X.tgz`), and in the Package Manager window in Unity, click on the + on the top left and select `Add package from tarball` to install the package in your project.

**Comment by Garfounkel** [comment]
I had a different but similar issue, lately GitHubForUnity has been completely acting out for me after upgrading Unity to 2020 LTS (any operation would result in a NullReferenceException). Doing what @shana suggested in the previous comment solved my issue.  If you try that, just remember to remove the previous GitHubForUnity installation first (remove Assets/Plugins/GitHub/).

@shana From my understanding this repo is not maintained anymore but https://github.com/Unity-Technologies/Git-for-Unity is, even though it's still in preview. It might be worth updating the readme to redirect people over there directly?
