### ISSUE TITLE
Github Client Window gets stuck when comitting changes

### ISSUE THREAD

**Issue by dinukapj** [github-for-unity/Unity#1124]
Github client is stuck and doesn't commit changes to master. The inspector is greyed out but the Unity Engine is working/responsive. The GitHub client window is greyed out and disabled. Engine needs to be exited and reopened to continue. Not sure how to recreate though.

Screenshot: https://i.ibb.co/TgWN47L/Screen-Shot-2020-08-30-at-7-25-22-pm.png

**Comment by wristshot0** [comment]
This version is horrifically buggy. We are experiencing the same issue; however there is no need to restart. Unity. It appears to resolve when you go to another tab and return, after which you can push. Your commit summary will be grayed out, but this doesn't seem to have an actual effect.

**Comment by shana** [comment]
This project is no longer active. Try the Unity-owned fork over at https://github.com/Unity-Technologies/Git-for-Unity instead, it's been refactored as a source package for the Package Manager, and has a bunch of fixes on top.

From the [release page](https://github.com/Unity-Technologies/Git-for-Unity/releases), download the first tgz on the asset list, `com.unity.git-X.X.X-preview.tgz`, and in the Unity Package Manager window, click on the top left + and select `Add package from tarball` to install the package.
