### ISSUE TITLE
can't open my project in Unity2020.1.2

### ISSUE THREAD

**Issue by Icassell** [github-for-unity/Unity#1125]
### Description

There is Unity 2018.2 Unity 2019.2 Unity2020.1.2 in my conputer.
I suddenly can't open my project in Unity2020.1.2,but others is okay.

Here is the log file:
[Licensing::Module] Channel doesn't exist: "LicenseClient-otaku"

### Steps to Reproduce

1. [First Step]Run Unity 2020.1.2 (from Unity Hub or .exe)
2. [Second Step] nothing happend

**Comment by shana** [comment]
Sorry, this is a Unity licensing problem, it's unrelated to this project.
