### ISSUE TITLE
Error in PackageManager in Unity2020.1.2

### ISSUE THREAD

**Issue by Icassell** [github-for-unity/Unity#1126]
### Description
Download Asset form AssetStore,then switch to UnityEditor,Here is Console Log

ArgumentException: An item with the same key has already been added. Key: 
System.Collections.Generic.Dictionary`2[TKey,TValue].TryInsert (TKey key, TValue value, System.Collections.Generic.InsertionBehavior behavior) (at <fb001e01371b4adca20013e0ac763896>:0)
System.Collections.Generic.Dictionary`2[TKey,TValue].Add (TKey key, TValue value) (at <fb001e01371b4adca20013e0ac763896>:0)
UnityEditor.AsyncHTTPClient.get_responseHeader () (at <11c7b17497094e71bfc803fb49f1b37d>:0)
UnityEditor.PackageManager.UI.AssetStoreRestAPI+AssetStoreRestAPIInternal+<>c__DisplayClass16_0.<GetProductDetail>b__0 (System.Collections.Generic.Dictionary`2[TKey,TValue] result) (at <11c7b17497094e71bfc803fb49f1b37d>:0)
UnityEditor.PackageManager.UI.AssetStoreRestAPI+AssetStoreRestAPIInternal+<>c__DisplayClass19_0.<HandleHttpRequest>b__1 (UnityEditor.IAsyncHTTPClient httpClient) (at <11c7b17497094e71bfc803fb49f1b37d>:0)
UnityEditor.AsyncHTTPClient.Done (UnityEditor.AsyncHTTPClient+State status, System.Int32 i_ResponseCode) (at <11c7b17497094e71bfc803fb49f1b37d>:0)

### Steps to Reproduce

1. Restart Unity&Restart Computer
2. Clean Local Data

None of the above methods worked

**Comment by ghost** [comment]
I also have experienced this issue. This appears to happen whenever a new asset is added. If one continues to commit, and it will eventually grab all new elements. Results in lots of extra commits, but that's not the worst thing in the world. Annoying but manageable.
