### ISSUE TITLE
Maximising game window, playing the game, and minimising it again causes unity to reset the editor layout.

### ISSUE THREAD

**Issue by Ceebox** [github-for-unity/Unity#1130]
### Prerequisites

- Be sure to run with tracing enabled to capture runtime details in the log file
- Include the log file in the PR.
  - On Windows, the extension log file is at `%LOCALAPPDATA%\GitHubUnity\github-unity.log`
  - On macOS, the extension log file is at `~/Library/Logs/GitHubUnity/github-unity.log`
  - On linux, the extension log file is at `~/.local/share/GitHubUnity/github-unity.log`

### Description

When I maximise my game window and then return to normal, my editor layout is reset to default.

### Steps to Reproduce

1. Maximise game window
2. Play game
3. Un maximise it.

**Expected behavior:** Editor should return to normal

**Actual behavior:** I am forced to reset to default.

**Reproduces how often:** Happens 100% of the time.

### Additional Information

Running Unity 2019.4 LTS. Updated version from 8f to 12f and the bug persists.

**Comment by UnderYourCloset** [comment]
Same here, using Unity 2020.3 LTS. Still happens. Deleted all my layouts and now I need to recreate them.
