### ISSUE TITLE
Login Failed Error in both 2019 and 2020 on Ubuntu 20.04

### ISSUE THREAD

**Issue by skinny-pete** [github-for-unity/Unity#1131]
[github-unity.log](https://github.com/github-for-unity/Unity/files/5510668/github-unity.log)

### Description

Login Failed error message when trying to log in, I get Error validating token if I try to sign in with browser. This occurs in both Unity 2019 and 2020. This occurs in all projects including completely blank new ones.

### Steps to Reproduce

1. Attempt Login of any type

**Expected behavior:** Log in to GitHub
**Actual behavior:** Failed to log in with error message

**Reproduces how often:** Every Time

**Comment by zhouyadong1983** [comment]
me too

**Comment by Qoyyuum** [comment]
Hi @skinny-pete , according to your log, it seems it can't detect that you have git installed.

```
201109-12:52:27.342  WARN [101] <IApplicationManager>               We could not find Git in the system.
```

**Comment by MMO-Indie** [comment]
https://gyazo.com/49d57eb2ecdb63761f2127c2c5a39fbb

works in 2019.4.17f1 just login by browser

**Comment by OmarWKH** [comment]
I had the same issue and fixed it by using firefox instead of edge/chrome :/

**Comment by QuantDeveloperUSA** [comment]
Same issue still today

**Comment by GozdeBuse** [comment]
I had same issue. I solved it following these steps:
On GitHub window I opened settings tab,
Under save repository, I clicked Find system Git button,
Then I clicked Save button,
And when I tried to log in again, it worked.

Hope it helps, 
And sorry for my bad English.
