### ISSUE TITLE
"Not Found" on signing in

### ISSUE THREAD

**Issue by omanuke** [github-for-unity/Unity#1137]
### Description
When I sign in from dialog, error message "Not Found" appears.
Username and password is correct.

What's wrong?

using package: github-for-unity-1.4.0.6503.unitypackage
Unity version: Unity 2019.4.12f1
![image](https://user-images.githubusercontent.com/1901757/103187005-107a1600-4906-11eb-9e6c-0900a1a45521.png)

**Comment by Akryllax** [comment]
By any chance, do you have 2 step verification on? In my case I had to click on "Sign in through web".

**Comment by SpyrosD3v25** [comment]
i had the same error

**Comment by bobo123g** [comment]
I have the same error.

**Comment by Meepy10** [comment]
Same here

**Comment by unoti** [comment]
Same problem here. The "Sign in through web" button was there at first, but now it is not...

**Comment by zongo811** [comment]
Me too. "Sign in with your browser" doesn't work either.

**Comment by ZanePZudans** [comment]
Same Issue. What is the latest build of Unity this plugin actually works with?

**Comment by ghost** [comment]
Same here

**Comment by 4xMafole** [comment]
Yer! I think the problem still persist. Same here.

**Comment by darnoldi** [comment]
same problem

**Comment by Hecedu** [comment]
Exact same problem.

**Comment by mrstruijk** [comment]
Same problem.

Edit, however, the 'Sign in through web' button was available and did work. Hard to see though!
![Hard to see though!](https://user-images.githubusercontent.com/35394193/132508645-11099648-2136-464c-9a35-7f5261f9653e.png)

**Comment by remton** [comment]
i have the same issue

**Comment by Mordochor** [comment]
I also have this issue. Sign in with your browser shows just a blank page.

**Comment by MuhammadMujtabaAhmed** [comment]
> I also have this issue. Sign in with your browser shows just a blank page.

same issue

**Comment by PangeranWiguan** [comment]
> I also have this issue. Sign in with your browser shows just a blank page.

Yes, just show a blank page here as well.
When I view the source of that page, it's really blank, HTML-less.

**Comment by Hecedu** [comment]
Since Unity has not addressed this issue there are two possible solutions, use git from the command line or use the git hub addon in Visual Studio Code. Both will allow you to do exactly the same thing.
This is a band-aid for a feature that doesn't work properly.

**Comment by ghost** [comment]
Same here

**Comment by cequella** [comment]
Same here

**Comment by 2boxx** [comment]
same. cant log in with username or with "sign in with browser"

I either get "not found" or "invalid token".
Also, the browser tab that opens doesn't display anything, only a localhost URL and a blank page

**Comment by FabienWeibelZeilt** [comment]
Same problem. localhost URL is a blank page too. On the first attempt, the page showed up. Then it failed everytime

**Comment by Redrawn2** [comment]
> same. cant log in with username or with "sign in with browser"
> 
> I either get "not found" or "invalid token". Also, the browser tab that opens doesn't display anything, only a localhost URL and a blank page

Exact same problem here (and had it for a few weeks now).

Visual Studio and VS Code both still work, so for everyone still stuck with this: Try using the VS GitHUB extension to push/pull. You can still commit to the local stash in Unity (at least this still works for me) and then execute a sync in VS. Both views should sync up after the transaction.

**Comment by YuzenPro** [comment]
Same here

**Comment by MicahWoodrowPhillips** [comment]
Same here.  Sucks.  This would really be nice.

Edit:  On using the browser link, after being confronted with the blank HTML page and going back to unity, I get an error: "Error Validating Token".

Also, the page is not calling out to github; it's pointing to a local URI:
http://localhost:42424/callback?code=c8ca6573bb08d91389ab&state=f3bd1061-9bc3-4ebc-acdf-7dd42def50d7

I'm guessing this is the issue?

**Comment by stevensrmiller** [comment]
I'm getting this exact problem too. Only gives me the web link to sign in. Seemed to send me to the github page once, but I got the "error validating toke" error and it always sends me to http://localhost after that. 

Finding bug reports very similar to this that go back for years.

**Comment by lualucky** [comment]
Having the same issue. I'm on Unity 2019.4.16f1. Two factor authentication is not enabled. Using GitHub for Unity version 1.4.0.

**Comment by eyelog** [comment]
I have the same problem.
But I actually don't need to be autorized to use this plugin.
My way:
1. Create the repo on github
2. Initialize the git in your project
3. Copy the git path into "origin"
4. Be sure that, your ssh applyed in your github settings
5. Commit and push as well.

**Comment by rachelcorey** [comment]
I'm having this issue as well. 

So this issue has been happening for over a year, and no word from Unity on when/if it will be fixed?

**Comment by stevensrmiller** [comment]
> no word from Unity

I think maybe this is more github's responsibility.

**Comment by mrietschel** [comment]
i have the same problem, logging in through unity: "Not found", trying with the browser results in a blank page as well.

**Comment by Hecedu** [comment]
> > no word from Unity
> 
> I think maybe this is more github's responsibility.

Well, in 2020 GitHub announced their intent to update their authentication process to require token-based authentication on all platforms. This new measure was implemented and is required since around August 2021.
It's was up to Unity to develop a solution that supports the new authorization flow. But alas, it's been almost 2 years and as you can see they still haven't done so.

**Comment by azorkai** [comment]
Same

**Comment by jambestwick** [comment]
same problem

**Comment by Akryllax** [comment]
@omanuke I'd suggest you please close this issue, this issue is over a year old, and many revisions of the client have happened meanwhile, close it to avoid necroposting from different versions :)

**Comment by DylanAVC** [comment]
the localhost URI has no code lol

**Comment by samuelchou** [comment]
Same problem, plus the browser went to localhost uri as well.

**Comment by Hecedu** [comment]
> @omanuke I'd suggest you please close this issue, this issue is over a year old, and many revisions of the client have happened meanwhile, close it to avoid necroposting from different versions :)

Shouldn't issues be closed either when they are resolved or they have been inactive for a long time? Even though a number of revisions to the client have happened, the exact same issue listed in the OP still stands and users are still posting reports (it is also the current open issue with the highest number of user interaction). 
At this point it is worth mentioning that I've seen user @chantzish post a pull request with tentative a fix to the issue that has not yet been merged. Maybe it would be a better idea to close the issue when said pull request has been merged and tested?

**Comment by WingsGames** [comment]
Same here, after logging out, I cant log back in.

**Comment by valkyrieBae** [comment]
Also having this issue

**Comment by eristocrates** [comment]
having the same issue as everyone else

**Comment by marcovalla** [comment]
Same issue. Can't use this tool from the Asset Store

**Comment by Vaelthur** [comment]
Same here unfortunately; Reading the comments i've tried both login w/ token (via browser) and w/ credentials bc I currently have 2FA disabled, but no luck at all

Edit: 
I found this solution in another thread and it worked perfectly -> [here](https://github.com/github-for-unity/Unity/issues/1152#issuecomment-1012389620)

**Comment by Remusqs1** [comment]
> same. cant log in with username or with "sign in with browser"
> 
> I either get "not found" or "invalid token". Also, the browser tab that opens doesn't display anything, only a localhost URL and a blank page

One year later this is still happening in the last version of unity LST (2021.3.8f1)

**Comment by spider853** [comment]
same issue,
Can't login from user/password,
When clicking sign in online, redirects to localhost:... and inside unity I get errors like auth error, or token=gh
