### ISSUE TITLE
Removing this plugin

### ISSUE THREAD

**Issue by duriumm** [github-for-unity/Unity#1142]
How do i remove this plugin? It causes more harm than good and has destroyed my project.
Removing the files just makes them reappear again on starting unity.

**Comment by AmethySlime** [comment]
I have been wondering the same thing as it has started causing 1000's of errors every second the editor is open and not in play mode. It doesn't show up in my package manager and it is causing me some stress.

**Comment by prashant959** [comment]
How to see code in get hub

**Comment by qatoqat** [comment]
Based on the unity package installer, the files are added into the project folder path `Assets/Plugins/GitHub/Editor`
Simply, you can remove the `GitHub` folder in the `Assets/Plugins` folder to uninstall.

**Comment by ghost** [comment]
Same, this plugin is crashing my proyect.

**Comment by shana** [comment]
This project is not maintained anymore. The replacement is Git for Unity, at https://github.com/spoiledcat/git-for-unity. If you have GitHub for Unity in your project, remove it first and then install the [Git for Unity](https://github.com/spoiledcat/git-for-unity) package, see the README in the link for instructions.
