### ISSUE TITLE
Scripts not debugging/running in unity 2020.6.

### ISSUE THREAD

**Issue by PranavBharadwaj1** [github-for-unity/Unity#1144]
-->

### Steps to Reproduce

1. Download Visual Studio Code and install all necessary plugins.
2. Log a message in the console with Debug.Log method.

**Expected behavior:** Message appear in console.

**Actual behavior:** Nothing happens.

### Additional Information

I am on windows and new to unity. I have tried reinstalling unity 3 times and I still have the same problem.
Any help would be appreciated.

**Comment by twobob** [comment]
Look in the unity Console.
![image](https://user-images.githubusercontent.com/915232/123657136-6f263b00-d828-11eb-8bb9-96efbf0c06fc.png)

https://docs.unity3d.com/ScriptReference/Debug.Log.html

> Note that Unity also adds Debug.Log messages to the Editor and Player log files. See https://docs.unity3d.com/Manual/LogFiles.html for more information about accessing these files on different platforms.

please close this issue
