### ISSUE TITLE
Can I know the shortcut way to develop poker android game by unity 

### ISSUE THREAD

**Issue by vnxz** [github-for-unity/Unity#1146]
I start to learn unity .
I want to develop a poker card android multiplayer game
Please let me know the format of this game
what are  pre requirements in knowledge

**Comment by twobob** [comment]
This is not a git-for-unity issue.  Here is such a resource.  https://github.com/CragonGame/CasinosClient
Please close this issue.

**Comment by vnxz** [comment]
closed , thanks
