### ISSUE TITLE
Login Issues

### ISSUE THREAD

**Issue by Danickar** [github-for-unity/Unity#1152]
### Prerequisites

- Be sure to run with tracing enabled to capture runtime details in the log file
- Include the log file in the PR.
  - On Windows, the extension log file is at `%LOCALAPPDATA%\GitHubUnity\github-unity.log`
  - On macOS, the extension log file is at `~/Library/Logs/GitHubUnity/github-unity.log`
  - On linux, the extension log file is at `~/.local/share/GitHubUnity/github-unity.log`

### Description

When my students try to login they get an error message "Error validating token." I know the internet filter isn't blocking GitHub because the students can login to the GitHub website and the GitHub desktop app.

### Steps to Reproduce

1. Click on Sign In for GitHub for Unity
2. Click Sign in with your browser
3. After the browser opens and does its thing, going back to Unity has the error message.

**Expected behavior:** [What you expect to happen]
GitHub signs in so students can access repositories directly in Unity.

**Actual behavior:** [What actually happens]
Does not sign in with Error Validating Token

**Reproduces how often:** [What percentage of the time does it reproduce?]
It reproduces 100% for my students.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

We are using Unity LTS 2020.3.14 with Unity GitHub 1.4
[github-unity.log](https://github.com/github-for-unity/Unity/files/7145820/github-unity.log)

**Comment by CarrierChristopher21** [comment]
i got the same issue

**Comment by mrdaljama** [comment]
I also got the same issue with Unity LTS 2020.3.3f1 and Unity GitHub 1.4

**Comment by AlexGalindoFreire** [comment]
I also had the same issue on Unity 2021.1.20f1

**Comment by AlecMuchnok** [comment]
Same issue on Unity 2019.3.3f1.  I recently got an email from GitHub about changing my personal authentication token.  I'm not a Git expert, so I just did what it said, but I think it messed up my account for GitHub for Unity.  When I click the normal sign in button, I get an error that says "Not Found" and when I click sign in with browser, I get the same error as above.  This is regardless of whether I use my password or authentication token as the password.  I've been able to work around it by signing in using the command line with my authentication token.

**Comment by yuran09** [comment]
I have the same error when I dont put the required credentials

**Comment by 0xEquinox** [comment]
Same problem

**Comment by darkfoxtokoyami** [comment]
I have the same "Not Found" issue.  Signing in with a browser doesn't work either (tried Firefox and Chrome).  It just hangs after I auth with github and says "Error Validating Token."  I couldn't work around this with the github console because it would immediately close as soon as it opened.

**Comment by Crazyafk** [comment]
Yeah happened to me 2021.1.13f1
Shame this project is dead, does anyone know of a working alternative?

**Comment by kevduc** [comment]
Same here

**Comment by demolen** [comment]
same here

**Comment by kevduc** [comment]
> Yeah happened to me 2021.1.13f1
> Shame this project is dead, does anyone know of a working alternative?

I ended up not logging in and setting up the remote and publishing the first time directly with VSCode (I guess you could also do it from the command line). Now I can do everything fine from the plugin.

**Comment by jrdndj** [comment]
happens to me too. And in turn whenever I wish to push to my repository, I always get an error message "Device not configured". Repo details are all correct except for this sign in bug. Im using github desktop too so I know the local settings are properly configured as wel. Is this somehow related too to why I am having trouble pushing my changes from local to remote?

**Comment by StudioAlbert** [comment]
Issue confirmed : last version of github for unity (1.4.0) and Unity 2020.3.21f1 (LTS)
I can not login (with Username / Password or with Browser)

I finally found something : the paths to git programm (Settings\Path to git + Settings\Path to git LFS) were not set properly. I push the button "Find system Git" it solves connection issues and i could push my project.

**Comment by bilalgrden** [comment]
same here

**Comment by NoCultist** [comment]
:/ Same here. Can't seem to find a way to make it sign in. 
Win10 Unity 2020.3.20f1
Tried setting paths automatically and by hand and using bundled git, yet my attempts were fruitless.
Logging through a browser also does not work with any browser.

**Comment by BenCraystonStudent** [comment]
Same issue.

**Comment by kennethdemaio** [comment]
Same issue

**Comment by TurtleSeal** [comment]
Any fixes? I pressed "find system git" but that didn't solve my problem...

**Comment by penseurai** [comment]
Tried all of the recommendations and nothing really works. It's just totally broken for signing in - something that is kinda a fundamental ability of being able to use the plugin.

**Comment by 05Alston** [comment]
Here's how I'm currently using it.
1. Initialize a repository with Github desktop and add unity libraries to it.
2. then open the project and import GitHub for unity.

![Screenshot 2021-11-20 205907](https://user-images.githubusercontent.com/89850018/142732036-020b655c-2feb-48c1-9a64-bf7e9691daca.png)
3. It shows up like this. Even though I can't sign in here, I can push/pull and commit to my repository.

**Comment by chantzish** [comment]
I've submited a pull request with a fix https://github.com/github-for-unity/Unity/pull/1160 but it doesn't look like they are going to merge it anytime soon so you can just fix it manually.

replace line 16:
`type: "oauth"`
with:
`type: "token"`

in `%userprofile%\AppData\Local\GitHubUnity\octorun\src\api.js`

**Comment by TurtleSeal** [comment]
I switched to plastic scm

**Comment by jillazalat** [comment]
> I've submited a pull request with a fix #1160 but it doesn't look like they are going to merge it anytime soon so you can just fix it manually.
> 
> replace line 16: `type: "oauth"` with: `type: "token"`
> 
> in `%userprofile%\AppData\Local\GitHubUnity\octorun\src\api.js`

This worked for me, thank you!

**Comment by Miredly** [comment]
> I've submited a pull request with a fix #1160 but it doesn't look like they are going to merge it anytime soon so you can just fix it manually.
> 
> replace line 16: `type: "oauth"` with: `type: "token"`
> 
> in `%userprofile%\AppData\Local\GitHubUnity\octorun\src\api.js`

This also worked for me, thanks!

**Comment by BensonCoolfi** [comment]
> I've submited a pull request with a fix #1160 but it doesn't look like they are going to merge it anytime soon so you can just fix it manually.
> 
> replace line 16: `type: "oauth"` with: `type: "token"`
> 
> in `%userprofile%\AppData\Local\GitHubUnity\octorun\src\api.js`

worked for me too. thank you so much

**Comment by DougCruz** [comment]
> I've submited a pull request with a fix #1160 but it doesn't look like they are going to merge it anytime soon so you can just fix it manually.
> 
> replace line 16: `type: "oauth"` with: `type: "token"`
> 
> in `%userprofile%\AppData\Local\GitHubUnity\octorun\src\api.js`

THANK YOU. this worked perfectly!!!

**Comment by GRODRAK** [comment]
> Issue confirmed : last version of github for unity (1.4.0) and Unity 2020.3.21f1 (LTS) I can not login (with Username / Password or with Browser)
> 
> I finally found something : the paths to git programm (Settings\Path to git + Settings\Path to git LFS) were not set properly. I push the button "Find system Git" it solves connection issues and i could push my project.

This solved my issue!Thank you

**Comment by Ross-Patterson** [comment]
> I've submited a pull request with a fix #1160 but it doesn't look like they are going to merge it anytime soon so you can just fix it manually.
> 
> replace line 16: `type: "oauth"` with: `type: "token"`
> 
> in `%userprofile%\AppData\Local\GitHubUnity\octorun\src\api.js`

Worked perfectly.

For anyone on Mac, the file location is: Users\Username\Library\Application Support\GitHubUnity\octorun\src\api.js

**Comment by Shrammer1** [comment]
> I've submited a pull request with a fix #1160 but it doesn't look like they are going to merge it anytime soon so you can just fix it manually.
> 
> replace line 16: `type: "oauth"` with: `type: "token"`
> 
> in `%userprofile%\AppData\Local\GitHubUnity\octorun\src\api.js`

This worked for me as well.

**Comment by AndyPorsche** [comment]
> 

You've saved us after almost 3 hours of searching for a solution!

**Comment by AndyPorsche** [comment]
> I've submited a pull request with a fix #1160 but it doesn't look like they are going to merge it anytime soon so you can just fix it manually.
> 
> replace line 16: `type: "oauth"` with: `type: "token"`
> 
> in `%userprofile%\AppData\Local\GitHubUnity\octorun\src\api.js`

You've saved us after 3 hours of searching!

**Comment by RaYVen1337** [comment]
> I've submited a pull request with a fix #1160 but it doesn't look like they are going to merge it anytime soon so you can just fix it manually.
> 
> replace line 16: `type: "oauth"` with: `type: "token"`
> 
> in `%userprofile%\AppData\Local\GitHubUnity\octorun\src\api.js`

Still only working like this for me, Thanks!

**Comment by icariantk** [comment]
> I've submited a pull request with a fix #1160 but it doesn't look like they are going to merge it anytime soon so you can just fix it manually.
> 
> replace line 16: `type: "oauth"` with: `type: "token"`
> 
> in `%userprofile%\AppData\Local\GitHubUnity\octorun\src\api.js`

Still need to do that today.

**Comment by aliceakesson** [comment]
> I've submited a pull request with a fix #1160 but it doesn't look like they are going to merge it anytime soon so you can just fix it manually.
> 
> replace line 16: `type: "oauth"` with: `type: "token"`
> 
> in `%userprofile%\AppData\Local\GitHubUnity\octorun\src\api.js`

Worked perfectly, thank you so much!

**Comment by SuperDizor** [comment]
Thank you! Worked for me

**Comment by lordhaywire** [comment]
Worked for me too!

**Comment by mediajolt001** [comment]
Works for me!

**Comment by jeffmaley** [comment]
This worked

**Comment by ChiHoFung** [comment]
Worked for me, thank you.

**Comment by AutoKhal** [comment]
thanks mate! switching oauth to token worked for me as well

**Comment by Lounode** [comment]
thanks!!! it worked~!

**Comment by MonaTZ** [comment]
Thanks!! Worked for me too!!!!

**Comment by DanielVidarHolm** [comment]
> I've submited a pull request with a fix #1160 but it doesn't look like they are going to merge it anytime soon so you can just fix it manually.
> 
> replace line 16: `type: "oauth"` with: `type: "token"`
> 
> in `%userprofile%\AppData\Local\GitHubUnity\octorun\src\api.js`

Yup that worked! Thank you

**Comment by Remusqs1** [comment]
> I've submited a pull request with a fix #1160 but it doesn't look like they are going to merge it anytime soon so you can just fix it manually.
> 
> replace line 16: `type: "oauth"` with: `type: "token"`
> 
> in `%userprofile%\AppData\Local\GitHubUnity\octorun\src\api.js`

Are you GOD?? Thanks a lot for your answer, it worked well. It is incredible that the Unity team has not solved this or accepted the merge

**Comment by lojithv** [comment]
> I've submited a pull request with a fix #1160 but it doesn't look like they are going to merge it anytime soon so you can just fix it manually.
> 
> replace line 16: `type: "oauth"` with: `type: "token"`
> 
> in `%userprofile%\AppData\Local\GitHubUnity\octorun\src\api.js`

Thanks :) It worked

**Comment by shana** [comment]
This project is not maintained anymore. The replacement is Git for Unity, at https://github.com/spoiledcat/git-for-unity. If you have GitHub for Unity in your project, remove it first and then install the [Git for Unity](https://github.com/spoiledcat/git-for-unity) package, see the README in the link for instructions.

**Comment by jrdndj** [comment]
thanks for this. by the way where do I find instructions so I can remove Git from my unity?
