### ISSUE TITLE
aubout Gitblit server

### ISSUE THREAD

**Issue by xillscar** [github-for-unity/Unity#1154]
hi everyone, I have a Gitblit server that I built
How can I use this to connect and access my own Gitblit server?

**Comment by shana** [comment]
This project is not maintained anymore. The replacement is Git for Unity, at https://github.com/spoiledcat/git-for-unity. If you have GitHub for Unity in your project, remove it first and then install the [Git for Unity](https://github.com/spoiledcat/git-for-unity) package, see the README in the link for instructions.
