### ISSUE TITLE
 Unity 2020.3.21f1: Doesn't like my account

### ISSUE THREAD

**Issue by gracioustimmy** [github-for-unity/Unity#1156]
[github-unity.log](https://github.com/github-for-unity/Unity/files/7490475/github-unity.log)
### Prerequisites
Install Unity 2020.3.21f1.
Install github for unity.
### Description

It keeps asking me to log in, even after I DID log in. Also, when I try to log in through the sign in above the repository stuff, it says "not found".

### Steps to Reproduce

1. Log in.
2. Go to another window.
3. Come back.

**Expected behavior:** Nothing.

**Actual behavior:** Another log-in window, even though I already did.

**Reproduces how often:** Alot.

**Comment by NoCultist** [comment]
Had the same problem, solved it by setting up a repository from Github Desktop and then restarting the Unity project. The plugin is just unable to sign in but if you sign in from Github Desktop it somehow works.

**Comment by penseurai** [comment]
Tried from Github Desktop on Windows and it doesn't really resolve the issue. I have icons next to everything, but it still won't let me sign in. Maybe that's a sign to just move on :)

**Comment by chantzish** [comment]
I've submited a pull request with a fix https://github.com/github-for-unity/Unity/pull/1160 but it doesn't look like they are going to merge it anytime soon so you can just fix it manually.

replace line 16:
`type: "oauth"`
with:
`type: "token"`

in `%userprofile%\AppData\Local\GitHubUnity\octorun\src\api.js`

**Comment by shana** [comment]
This project is not maintained anymore. The replacement is Git for Unity, at https://github.com/spoiledcat/git-for-unity. If you have GitHub for Unity in your project, remove it first and then install the [Git for Unity](https://github.com/spoiledcat/git-for-unity) package, see the README in the link for instructions.
