### ISSUE TITLE
I get an error when I sign in (unity 2020.3.14f1 personal)

### ISSUE THREAD

**Issue by B33bo** [github-for-unity/Unity#1157]
### Prerequisites

The log file says 
211113-14:57:06.441  INFO [ 1] <Global>                            Initializing GitHubForUnity:'v1.4.0' Unity:'v2020.3.14f1'

### Description

When I type my username & password I get "HttpError: write EPROTO 101057795:error:1408D07B:SSLroutines:ssl3_get_key_excgabfe:badsignature:openssl\ssl\s3_cint.c:2032:"

when I sign in with browser I get an empty webpage with address "http://localhost:42424/callback?code=02a5c1d86ad274cb9723&state=fa7ed7ff-6c3e-4c23-be09-ec638357e338"

and inside the (ms edge) console it says "Failed to load resource: the server responded with a status of 400 (Bad Request)"

### Steps to Reproduce

1. go to https://unity.github.com/ and press the download button
2. try sign in

**Expected behavior:** sign in

**Actual behavior:** error

**Reproduces how often:** whenever I try to log in

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.
Unity 2020.3.14f1 Personal
![image](https://user-images.githubusercontent.com/61664638/141648914-6cbfaecb-f131-4d55-9ef0-f95085a30768.png)

**Comment by B33bo** [comment]
by 'download button', I mean 'Download GitHub for Unity 1.4.0'

**Comment by mkniller** [comment]
I am getting the same behavior except I am seeing this error:
![image](https://user-images.githubusercontent.com/8039354/142276924-2c1bcebc-02de-4ccc-ada0-8798391f037e.png)

**Comment by penseurai** [comment]
Same. Doesn't work for me - getting Error validating token

**Comment by B33bo** [comment]
I think the devs have given up on this project :(

**Comment by WickyPayne** [comment]
same issue here cant login to GitHub

Both using credentials or via web authentication.

Unity 2020.3.25.f1
 
github-unity.log
```
211224-12:19:53.771  INFO [ 1] <Global>                            Initializing GitHubForUnity:'v1.4.0' Unity:'v2020.3.25f1'
211224-12:22:53.731  WARN [43] <UsageTracker>                      Error sending usage:"System.Exception" Message:"System.Exception: Post Usage failed: Error: write EPROTO 101057795:error:04091068:rsa routines:INT_RSA_VERIFY:bad signature:openssl\crypto\rsa\rsa_sign.c:278:
101057795:error:1408D07B:SSL routines:ssl3_get_key_exchange:bad signature:openssl\ssl\s3_clnt.c:2032:

  at GitHub.Unity.MetricsService.PostUsage (System.Collections.Generic.List`1[T] model) [0x000db] in C:\projects\unity\script\src\MetricsService.cs:59 
  at GitHub.Unity.UsageTrackerSync.SendUsage () [0x000f5] in C:\projects\unity\src\GitHub.Api\Metrics\UsageTracker.cs:111 "

```

**Comment by chantzish** [comment]
I've submited a pull request with a fix https://github.com/github-for-unity/Unity/pull/1160 but it doesn't look like they are going to merge it anytime soon so you can just fix it manually.

replace line 16:
`type: "oauth"`
with:
`type: "token"`

in `%userprofile%\AppData\Local\GitHubUnity\octorun\src\api.js`

**Comment by venetsia** [comment]
It does not work for me either. I get the "Error validating token" as well.

**Comment by jmgawecki** [comment]
Hi. I am also getting an error of this type. When trying to log in with the username and the password, I am getting "Not Found"
When logging in with the browser, I am getting an empty page and "Error Validating Token"

I am working from Unity for Mac Silicon on Macbook 13 pro M1. Thanks for the help.

**Comment by shana** [comment]
This project is not maintained anymore. The replacement is Git for Unity, at https://github.com/spoiledcat/git-for-unity. If you have GitHub for Unity in your project, remove it first and then install the [Git for Unity](https://github.com/spoiledcat/git-for-unity) package, see the README in the link for instructions.
