### ISSUE TITLE
Do not install this plugin

### ISSUE THREAD

**Issue by RandomCatGit** [github-for-unity/Unity#1158]
I was hoping to get a seamless github integration but it is not as advertised.

1. Login does not work (tried password and auth key)
2. Popup for login keeps on opening
3. Cannot close unity (had to force close with TaskManager)
4. GitHub Desktop is the way to go

Don't waste your time installing this. There is no option to uninstall this either, You have to close unity and find the plugin in folder Assets/Plugin/GitHub and delete it after closing unity.

**Comment by AKANexus** [comment]
Yeah, I've been having the same issues (using Unity 2020.3.22f1). Not sure if there are workarounds, but I agree that, for now, Github Desktop is a good alternative.

**Comment by ghost** [comment]
Well, the plugin hasn't been updated since mid-2019, so I'm not surprised. It won't let me log in or initialize a new repo from the plugin, so it's useless.

**Comment by ghost** [comment]
someone needs to fork and make a fixed version

**Comment by bguyl** [comment]
Unity made a fork here: https://github.com/Unity-Technologies/Git-for-Unity

You need to:

- Download [com.unity.git-2.1.28-preview.tgz](https://github.com/Unity-Technologies/Git-for-Unity/releases)
- Put it somewhere in the folder that contain your project, (i.e. `<your project name>/ExternalPackages/com.unity.git-2.1.28-preview.tgz`)
- From the Package Manager, click `+` > `Add package from tarball` and select the file

However, I do not recommend having it installed in this state, it refreshes the AssetDatabase every second, and it's pretty annoying

**Comment by ghost** [comment]
Oh cool

**Comment by chantzish** [comment]
I've submited a pull request with a fix https://github.com/github-for-unity/Unity/pull/1160 but it doesn't look like they are going to merge it anytime soon so you can just fix it manually.

replace line 16:
`type: "oauth"`
with:
`type: "token"`

in `%userprofile%\AppData\Local\GitHubUnity\octorun\src\api.js`

**Comment by szunami** [comment]
Thanks a ton!

**Comment by shana** [comment]
This project is not maintained anymore, and neither is the Unity-Technologies fork. The replacement is Git for Unity, at https://github.com/spoiledcat/git-for-unity. If you have GitHub for Unity in your project, remove it first and then install the [Git for Unity](https://github.com/spoiledcat/git-for-unity) package, see the README in the link for instructions.
