### ISSUE TITLE
The remote end hung up unexpectedly

### ISSUE THREAD

**Issue by SenshiSentou** [github-for-unity/Unity#1159]
### Description

The problem is two-fold. After migrating to a new machine (a MacOS transfer through Time Machine), the following happens:

- Not all changes are shown in the Editor window (I suspect none after the migration, but I'm not certain)
- Nothing gets committed. After selected all files and hitting "Commit" the progress bar shows "staging files", then ends with nothing happening.

The log shows `211210-07:57:07.366 TRACE [156] <ProcessWrapper>                    fatal: the remote end hung up unexpectedly`, which seems like a reasonable cause.

### Additional Information

[github-unity.log](https://github.com/github-for-unity/Unity/files/7690714/github-unity.log)
.

**Comment by shana** [comment]
This project is not maintained anymore. The replacement is Git for Unity, at https://github.com/spoiledcat/git-for-unity. If you have GitHub for Unity in your project, remove it first and then install the [Git for Unity](https://github.com/spoiledcat/git-for-unity) package, see the README in the link for instructions.
