### ISSUE TITLE
Every time I open unity files change in github?

### ISSUE THREAD

**Issue by Gavin-Hawk** [github-for-unity/Unity#1161]
Hello!

I've been working on a project today, I just downloaded unity and github on a newish laptop and I'm running into a few issues. First is with unity where no matter if it is closed it always says there is already a version open, I'm looking at unity specific forums for that.
Example:
![image](https://user-images.githubusercontent.com/56935803/153009324-9898c2be-8aa3-4164-bcfc-3e08b729ccfc.png)

But what I think is a effect of this issue, but not sure, is every time I boot up unity a bunch of files change. Sometimes it is pretty drastic although only in size.
![image](https://user-images.githubusercontent.com/56935803/153009264-ebc409e0-c3a5-46ee-8fc2-f52af833093e.png)
All it ever says is, "this binary file has changed". I'm really confused and I realize this is far above my skill level.

Thank you in advance!
Gavin

**Comment by shana** [comment]
This project is not maintained anymore. The replacement is Git for Unity, at https://github.com/spoiledcat/git-for-unity. If you have GitHub for Unity in your project, remove it first and then install the [Git for Unity](https://github.com/spoiledcat/git-for-unity) package, see the README in the link for instructions.
