### ISSUE TITLE
Mouse cursor spins every second while Github for Unity is installed (potential editor crash)

### ISSUE THREAD

**Issue by MojoMouse** [github-for-unity/Unity#1163]
### Prerequisites

- Be sure to run with tracing enabled to capture runtime details in the log file - **Instructions unclear, unable to comply**
- Include the log file in the PR.
[github-unity.log](https://github.com/github-for-unity/Unity/files/8145983/github-unity.log)

### Description
Github for Unity uses excessive memory and processing cycles. Resulting in repetitive cursor spinning and potentially editor crashes.

A couple weeks back I noticed that my mouse cursor would spin for a brief moment every second like clockwork. It only happened when the unity editor was focused, and was initially just a minor distraction. Earlier today I had multiple editor crashes with an unextraordinary project loaded. I went through the process of recreating my project step-by-step from a fresh project and when I imported GitHub for Unity the cursor started spinning again.

I notice that when I have the Github window open and the Editor is focused the "Listing changed files" bar fills up in time with the cursor spinning.

### Steps to Reproduce

1. Create a new Unity project with the 2D template
2. Create a sphere primitive in the scene
3. In the package manager, uninstall all of the default packages except for Unity UI(1.0.0), VS Editor (1.2.4) and VSC Editor (2.0.14)
4. Import GitHub for Unity (1.4.0)

**Expected behavior:**
The mouse cursor does not spin when nothing is happening and the memory usage does not steadily climb over time.

**Actual behavior:**
The mouse cursor repeatedly spins for a brief moment every second and the memory usage climbs until a crash occurs.

**Reproduces how often:**
About three times within the past 6 hours

### Additional Information
Windows 11 intel core 17 with nvidia geforce rtx Unity 2021.2.7f1 Personal <DX11>

Annoyingly enough, when I discovered the issue: Github for Unity did not appear in my package manager to be uninstalled and I had to delete the folder manually.

**Comment by JasonMiesionczek** [comment]
This is happening to me as well, Unity 2021.3.1f1 Github for Unity version 1.4.06503

**Comment by IceMiaoMiao** [comment]
How can we solve this problem?

**Comment by sachinkhatripro** [comment]
I have got the same problem as well on the latest unity editor version 8f1. It was also resulting in jerky scene play. Changing the timings didn't have any effect. So had to remove the plugin.

**Comment by shana** [comment]
This project is not maintained anymore. The replacement is Git for Unity, at https://github.com/spoiledcat/git-for-unity. If you have GitHub for Unity in your project, remove it first and then install the [Git for Unity](https://github.com/spoiledcat/git-for-unity) package, see the README in the link for instructions.
