### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by webislands** [github-for-unity/Unity#1164]
sorry is not login and work

**Comment by larinius** [comment]
Unity 2020.3.30f1 LTS - login not working, login with browser link - auth error.
Probably this one of the never working unity “features”.

UPS: fixed using this: https://github.com/github-for-unity/Unity/issues/1152

**Comment by shana** [comment]
This project is not maintained anymore. The replacement is Git for Unity, at https://github.com/spoiledcat/git-for-unity. If you have GitHub for Unity in your project, remove it first and then install the [Git for Unity](https://github.com/spoiledcat/git-for-unity) package, see the README in the link for instructions.
