### ISSUE TITLE
Visually see scene changes and which assets they were performed on

### ISSUE THREAD

**Issue by justinlulejian** [github-for-unity/Unity#1165]
### Description

[Context ](https://gamedev.stackexchange.com/questions/138068/how-can-i-visually-see-changes-made-to-a-scene-since-the-last-git-commit)

I couldn't find another enhancement filed with this request. One of the more common review slowdowns for me is that it's not easy to tell what assets in a .unity scene have changed when viewing the file on GitHub. So currently I load up the project, poke around in the scene until I deduce what changed. If rather my co-contributor could upload these graphs of changes it would make the changes much easier. It would also make resolving merge conflicts with confidence much easier if I could quickly see what I changed and decide whether to revert or accept the change.

So ideally if:

1) When encountering a merge conflict on a .unity ( or .prefab) file occurred, a graphic diff would show up like in the above SO post 
2) One could generate these diff on demand of these files between previous and current commits (for pasting in PR requests proactively)

This would be a great feature that Unity itself should, but has neglected to implement.

**Comment by shana** [comment]
This project is not maintained anymore. The replacement is Git for Unity, at https://github.com/spoiledcat/git-for-unity. If you have GitHub for Unity in your project, remove it first and then install the [Git for Unity](https://github.com/spoiledcat/git-for-unity) package, see the README in the link for instructions.
