### ISSUE TITLE
Can't push 

### ISSUE THREAD

**Issue by ShellCodingGH** [github-for-unity/Unity#1166]
Hi, 
I tried to push but I got this error message "fatal: could not read Username for 'https://github.com': Device not configured". I followed [this link](https://github.com/github-for-unity/Unity/blob/master/docs/using/quick-guide.md#authentication)
But I didn't do `brew install git git-lfs` on my terminal, because it always says `-bash: brew: command not found`
How can I push successfully?

Thanks for reading this message.

**Expected behavior:** Github for Unity can push successfully, and changes can be seen in the github website repository

**Actual behavior:** 
<img width="700" alt="Screenshot 2022-03-29 at 8 08 43 AM" src="https://user-images.githubusercontent.com/49096303/160507294-fd24edbf-369f-48fd-aae1-4fc78e54fb58.png">

**Comment by shana** [comment]
This project is not maintained anymore. The replacement is Git for Unity, at https://github.com/spoiledcat/git-for-unity. If you have GitHub for Unity in your project, remove it first and then install the [Git for Unity](https://github.com/spoiledcat/git-for-unity) package, see the README in the link for instructions.
