### ISSUE TITLE
Why is this still a thing?

### ISSUE THREAD

**Issue by AldeRoberge** [github-for-unity/Unity#1169]
Googling 'GitHub for Unity' reveals this repo, which hasn't been updated in years.

This gives false hopes to new users.

Please archive this repo and remove the website https://unity.github.com/ or redirect to GitHub Desktop or Plastic SCM.

**Comment by SeanBuckmaster** [comment]
how do i use unity now past version 18? 
this site is great for the old version, but i've upgraded.

**Comment by amigax** [comment]
agreed, I was here before they started, took years of waiting for it mature, and it simply wont work even after all this time. I think its more a problem with unity making UNBELIEVABLY bloated projects and github limitations on them. There needs to be a modern solution to backing up large projects. Dropbox is still king which is kind of a joke considering the man hours spent on this.

**Comment by shana** [comment]
This project is not maintained anymore. The replacement is Git for Unity, at https://github.com/spoiledcat/git-for-unity. If you have GitHub for Unity in your project, remove it first and then install the [Git for Unity](https://github.com/spoiledcat/git-for-unity) package, see the README in the link for instructions.
