### ISSUE TITLE
Uninstall package

### ISSUE THREAD

**Issue by atcarlso** [github-for-unity/Unity#1177]
I apologize if this is a dumb question, but how do you uninstall this package (from a project)? I added it to my project but the sign-in doesn't work and it'll just be better to use the GitHub client anyway. Thanks for any info!

**Comment by INeatFreak** [comment]
Open the package manager in editor and go to "In Project" section, find this package and click uninstall.

Or you can do it manually by opening unity project folder, finding "Packages/manifest.json" file and delete this entry and save.

**Comment by atcarlso** [comment]
I checked in both of those areas and did not see anything resembling Unity GitHub, so I thought my project didn't have it actually, but it does.

Under the "Window" menu if I click "GitHub" it shows the Unity Github panel in the Inspector area and that's the same panel I saw when I first installed the package. I actually see a little info note in the Console when I first load the project about Unity GitHub. Oh well, it's not really a big deal, I just ignore it anyway I guess.

**Comment by s4shrish** [comment]
It's possible that it's just imported into your assets folder as a plugin. Check that then, and if found delete it.

**Comment by shana** [comment]
This project is not maintained anymore. The replacement is Git for Unity, at https://github.com/spoiledcat/git-for-unity. If you have GitHub for Unity in your project, remove it first and then install the [Git for Unity](https://github.com/spoiledcat/git-for-unity) package, see the README in the link for instructions.
