### ISSUE TITLE
Unity will not refresh after switching branches in Gitbash.

### ISSUE THREAD

**Issue by LilMike808** [github-for-unity/Unity#1178]
Step 1: Create dev branch then make changes (C# script) while on dev branch in Unity then save scene.
Step 2: Switch to master/main branch in Gitbash, go back to Unity and the project will not refresh to reflect now being on the master/main branch.

Expected behavior: Unity automatically refreshes to reflect the switch from dev to master/main branch which shows lack of C#script created while in Dev branch.

Actual behavior: Unity incapable of refreshing to reflect switching branches in Gitbash. 

Frequency 98%

**Comment by LilMike808** [comment]
I apologize as I am brand new to Unity and coding in general. I just signed up for a game dev course. Unity did refresh a little before it didn't. The issue seemed to happen at random and is now consistent. I have followed course instructions to the 'T'.

**Comment by LilMike808** [comment]
I also keep deleting and recreating my 'version control' GitHub crash course repository. I can recreate a repository if need be up until the point in course where this issue occurs (creating and switching branches).

**Comment by shana** [comment]
Sorry, this project is not maintained anymore. The replacement is Git for Unity, at https://github.com/spoiledcat/git-for-unity. If you have GitHub for Unity in your project, remove it first and then install [Git for Unity](https://github.com/spoiledcat/git-for-unity), see the README in the link for instructions.
