### ISSUE TITLE
GitHub for Unity no longer in Asset Store?

### ISSUE THREAD

**Issue by JVimes** [github-for-unity/Unity#1179]
The "Download from Unity Asset Store" link on [unity.github.com](https://unity.github.com/) redirects to their front page. I also can't find GitHub for Unity by [searching the asset store](https://assetstore.unity.com/?q=GitHub).

**Comment by heyodai** [comment]
Echoing this. The link from the official page seems to be broken: https://unity.github.com/

EDIT: It looks like this repo hasn't been updated since 2019. I think it's safe to say this project is no longer maintained.

**Comment by shana** [comment]
Yes, this project is dead. The replacement is Git for Unity, at https://github.com/spoiledcat/git-for-unity. If you have GitHub for Unity in your project, remove it first and then install [Git for Unity](https://github.com/spoiledcat/git-for-unity), see the README in the link for instructions.

**Comment by JVimes** [comment]
Thank you much. It would be good to update unity.github.com with that message and link.

**Comment by SamuelEarl** [comment]
I am just starting out with Unity, but it looks like Unity has moved away from Git and is encouraging people to use [Unity Version Control](https://unity.com/solutions/git).
