### ISSUE TITLE
Non-ASCII character logs and file names are garbled in the history view and changes view.

### ISSUE THREAD

**Issue by shiena** [github-for-unity/Unity#124]
history from https://github.com/unity3d-jp/piranhan

![image](https://user-images.githubusercontent.com/1295639/28117592-02b85dda-6749-11e7-943e-c7a113f06414.png)

The reason is that `Process::OutputDataReceived` character-encodes with `Encoding.Default`, so the encoding output from the command does not match the encoding.

That is here.
https://github.com/Unity-Technologies/mono/blob/a449454f2128b2c0bb62d5ce3b8e22ab6b71db39/mcs/class/System/System.Diagnostics/Process.cs#L1424

**call hierarchy**
```
BeginOutputReadLine
-> ProcessAsyncReader
-> ProcessAsyncReader::AddInput
-> Encoding::Default::GetString
```

Since `Process::StandardOutput::ReadLine` uses `Process::StartInfo::StandardOutputEncoding`, combining `git -c i18n.logoutputencoding=utf8 log` and `Encoding.UTF8` will not garbled. However, since this is a synchronization process, Unity freezes until the command is finished.

Also, I have submitted a pull request on Unity's problem.
https://github.com/Unity-Technologies/mono/pull/582

For `Encoding.Default`,
* Japanese Windows codepage is 932
* OSX is the same as `Encoding.ASCII`

**Comment by StanleyGoldman** [comment]
Thanks @shiena for such a thorough bug report

**Comment by StanleyGoldman** [comment]
I suspect this is the cause for #35

**Comment by shiena** [comment]
I compared Unity 2017's Scripting Runtime Version .NET 3.5 with .NET 4.6.
.NET 3.5 is the same result as previous Unity, but .NET 4.6 is perfect!

https://gist.github.com/shiena/0dcd5e44197fcd4dc03efe67d6622ffc

![image](https://user-images.githubusercontent.com/1295639/28236786-5d54e8bc-696a-11e7-8f83-36a5707388bc.png)
