### ISSUE TITLE
Index.lock created and will prevent git operation

### ISSUE THREAD

**Issue by guitarrapc** [github-for-unity/Unity#125]
### Prerequisites

No `%LOCALAPPDATA%\GitHubUnity\github-unity.log` logs found.

### Description

Github for Unity will create index.lock for not managed file and will prevent itself and other Git tool from Commit/Push and others.

### Steps to Reproduce

1. Clone any repo which include Github for Unity. (Or install Github for Unity)
2. Make Unity path under any directory, like REPONAME\Hoge.Unity\(Unity Assets)
3. Create any git tracking file right under repo, like REPONAME\test.txt
4. Open Unity and show Github for Unity Window. 
5. Select Changed, History, Branches or any tabs for many time. Sometime index.lock is created and never removed, I think there are some race condition that I could not reproduce with simple way.
6. All git tools are locked include Github for Unity

At stage 4 there are no index.lock file.

![image](https://user-images.githubusercontent.com/3856350/28118529-5859f5de-674c-11e7-8733-63ddde2d6a6e.png)

At stage 5 there are index.lock file and will never remove until close Unity itself.

![image](https://user-images.githubusercontent.com/3856350/28118783-6fd7ccc6-674d-11e7-9f61-2b2d229e3917.png)

**Expected behavior:** [What you expect to happen]

index.lock file should immediately removed after index is required. Do not place it permanently until App lifetime.

**Actual behavior:** [What actually happens]

index.lock will remain while Unity is running.

**Reproduces how often:** [What percentage of the time does it reproduce?]

1st time to import Github for Unity unitypackage into Unity.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by StanleyGoldman** [comment]
Thanks for the bug report, I will look to reproduce it.

**Comment by StanleyGoldman** [comment]
Hey @guitarrapc. I think your issue will be near impossible to reproduce consistently, but I do believe it is resolved. In the previous build some events were triggering git operations very often and too quickly. In the latest build this is much more under control and future builds should continue this trend.

Try out the new build and let me know how it works for you. I'm going to close this issue, but if you see this happen again, don't hesitate to open it back up.

**Comment by guitarrapc** [comment]
Thank you @StanleyGoldman !
