### ISSUE TITLE
Support Flat List View for History and Changes window

### ISSUE THREAD

**Issue by guitarrapc** [github-for-unity/Unity#126]
### Prerequisites

No `%LOCALAPPDATA%\GitHubUnity\github-unity.log` existing.

### Description

Currently Github for Unity only support Tree view of files within History window and Changes Windows, but I'd rather prefer Flat List View on most cases. It's because, 

1. Directory Tree is sometime meaningless information and just showing path is enough.
1. Too may line for limited window area. You know `History > Commit Details` cannot change it's size currently.

### Steps to Reproduce

1. Make git tracking file change or create/remove files.
2. Show Changes Tab. You may find it offers only Directory Tree view.
3. Show History Tab and select any commit history. You may find file change will be shown as Directory Tree inside `Commit details` window but it's Window size is too small for tree view.

**Expected behavior:** [What you expect to happen]

It's appreciated if there are toggle or drop down choice to select from,

- Tree view
- Flat List View (Single Column)
- Optional : Flat List View (Multiple Column), may not needed?

Here's some sample from SourceTree.

![image](https://user-images.githubusercontent.com/3856350/28119384-a73cdb64-674f-11e7-8266-43b7b5fabffc.png)

Single Column look like this.

![image](https://user-images.githubusercontent.com/3856350/28119450-de8f4264-674f-11e7-8417-44050864f73f.png)

Multiple Column looks like this.

![image](https://user-images.githubusercontent.com/3856350/28119462-e9971eb6-674f-11e7-928a-500ff71843cf.png)

Tree View looks like this, as like Github for Unity.

![image](https://user-images.githubusercontent.com/3856350/28119485-fdaf0c9c-674f-11e7-8ddf-fbf69b383187.png)

**Actual behavior:** [What actually happens]

No option to select view.

**Reproduces how often:** [What percentage of the time does it reproduce?]

Default behavior.

### Additional Information

This is just a Feature request but may very helpful when Large set of items or files under too deep directory are changed.

**Comment by shana** [comment]
Thanks for the suggestion! I'm currently in the process of rewriting the tree rendering for performance reasons so this comes right on time, I'll see if I can get both types of view going in it.
