### ISSUE TITLE
Support File/git operation through Changes window

### ISSUE THREAD

**Issue by guitarrapc** [github-for-unity/Unity#127]
### Description

Support file/git operation in Changes Windows will offer full git Experience that I don't need to use other 3rd party tool or CLI at all.

### Steps to Reproduce

1. Add file.
2. Could not operate any with Changes window.
 
- Remove it
    - No, you need to remove it within Project window, or Explorer/Finder for non-unity item which even track in Github for Unity.
- add to .gitignore
    - No, you need manually operate `.gitignore`.
- Add to Staging
    - Staging will support in https://github.com/github-for-unity/Unity/issues/52
- Add to Track file type in Git LFS,
    - No, you need manually operate  `.gitattributes`.

**Expected behavior:** [What you expect to happen]

Show any context menu to operate with right click or any shortcut.

**Actual behavior:** [What actually happens]

No context menu is acceptable.

**Reproduces how often:** [What percentage of the time does it reproduce?]

Default behavior.

### Additional Information

May be too much request at this alpha version. Just a Feature request to offer full git experience.

**Comment by StanleyGoldman** [comment]
There are some good requests here. Thanks again.

**Comment by mpOzelot** [comment]
I've picked this up by coincidence actually! Was looking for a way to "revert" from the changes window. 

I've got the UI working so far, but haven't figured out the git side of things yet.
![image](https://user-images.githubusercontent.com/8388744/31166837-6a7db332-a8f0-11e7-8a27-81eb4afb0b80.png)
