### ISSUE TITLE
Odd sorting of folders in ChangesTreeView

### ISSUE THREAD

**Issue by StanleyGoldman** [github-for-unity/Unity#131]
Using this python script https://gist.github.com/StanleyGoldman/c84e31e174a91e1ff28770feaaf8da29 to generate data

![](http://i.imgur.com/JE216pK.png)

**Comment by StanleyGoldman** [comment]
The sort order is also not maintained after a restart.

![](http://i.imgur.com/MCc0iVy.png)

**Comment by meaghanlewis** [comment]
@StanleyGoldman does the picture from the last comment show the correct sort order?

**Comment by StanleyGoldman** [comment]
No the last comment is definitely not correct, but `meta` files are a thing..

**Comment by StanleyGoldman** [comment]
This is no longer an issue
