### ISSUE TITLE
Support "Create PR" from Branch tab

### ISSUE THREAD

**Issue by guitarrapc** [github-for-unity/Unity#135]
### Description

As of PR base development, a.k.a. Github flow is very common for Github development, offering `create PR` shortcut at Branch tab is very useful.

### Steps to Reproduce

1. Create Local Branch
2. Make any commit and push to remote.
3. Now I do like to create PR within `Github for Unity > Branch Tab` but can't. I need move to Github.com and create PR.

**Expected behavior:** [What you expect to happen]

Make PR from Github for Unity's Branch tab.

**Actual behavior:** [What actually happens]

Required to create PR from Github.com

**Reproduces how often:** [What percentage of the time does it reproduce?]

Default behavior.

### Additional Information

This is one of the great user experience that SourceTree offers. I really enjoy this functionality and is also want in Unity.

![image](https://user-images.githubusercontent.com/3856350/28180347-cf961ada-683f-11e7-8e26-66619964d8a0.png)

**Comment by StanleyGoldman** [comment]
We definitely want this, but there is soooo much to do before i can say we are there.
We will get there...

**Comment by guitarrapc** [comment]
Yes, I know it. Just a note is fine at this moment.
