### ISSUE TITLE
I am getting this error on command line

### ISSUE THREAD

**Issue by ahmetzeybek** [github-for-unity/Unity#142]
Remote "origin" does not support the LFS locking API. Consider disabling it with:
  $ git config lfs.https://github.com/ahmetzeybek/Unity.git/info/lfs.locksverify false
Git credentials for https://github.com/ahmetzeybek/Unity.git not found.
error: failed to push some refs to 'https://github.com/ahmetzeybek/Unity.git'

I attached my log file, and i am getting "Couldn't push brach" error, please someone help me plese

[github-unity.zip](https://github.com/github-for-unity/Unity/files/1148996/github-unity.zip)

**Comment by ahmetzeybek** [comment]
Solved...

**Comment by StanleyGoldman** [comment]
Hey @ghost, sorry I couldn't help. The team was on vacation.
Glad you figured it out though. 👍

**Comment by tarazhong** [comment]
Hi, i got exactly the same problem with the same errors, could you tell me how did you do ?

**Comment by StanleyGoldman** [comment]
Hi @tarazhong if you upload your log file to a different issue. I can confirm what your problem is.
