### ISSUE TITLE
GitHub for Unity throws exception in Unity 2017.1F3 with .Net 4.6 scripting backend

### ISSUE THREAD

**Issue by astaror** [github-for-unity/Unity#145]
### Description

When changing scripting backend in Unity 2017.1F3 to .Net 4.6 and restarting Unity GitHub For Unity throws an exception and not working.
When changing back to .Net 3.5 GitHub for Unity working fine again.

### Steps to Reproduce

1. Change scripting backend to .Net 4.6
2. Restart Unity

**Expected behavior:** GitHub for Unity working fine

**Actual behavior:** GitHub for Unity throws an exception and not working

**Reproduces how often:** Always

### Additional Information

Screenshot in attachments
![gitforunity2017](https://user-images.githubusercontent.com/4757541/28275817-c006e370-6b1d-11e7-92ba-9841016b3ec0.png)

### Log file
170717-18:29:28  INFO [ 1] <Global>                            Initializing GitHub for Unity version 0.15.0.0
170717-18:29:37  INFO [ 1] <Global>                            Trace Logging Enabled
170717-18:29:37 TRACE [ 1] <UserSettings>                      SaveToCache: C:\Users\user\AppData\Local\GitHubUnity\settings.json
170717-18:29:45 TRACE [ 1] <RepositoryManager>                 Stop
170717-18:29:45 TRACE [ 1] <RepositoryWatcher>                 Stopping watcher
170717-18:29:45  WARN [ 1] <RepositoryWatcher>                 Watcher already stopped

**Comment by shana** [comment]
@astaror Thanks for the report! Sorry for the delay in replying, we were away last week.

I suspect that the 4.6 backend is naming assemblies in a different way that doesn't match our `InternalsVisibleTo` directive, should be an easy fix.

**Comment by gaben33** [comment]
This has been open for about a month.  Last comment said it should be an easy fix.  Unity Collab preview ends in half a month, this fix would be a lifesaver for many.

**Comment by shana** [comment]
So this is a Unity Mono bug, it's being tracked in https://fogbugz.unity3d.com/default.asp?945353_q5i0lvir4egtnmc1

I suspect the fix is going to take a while, debugging the mono runtime is always tricky. We'll try and come up with a workaround while they're hacking on it.

**Comment by StanleyGoldman** [comment]
We will release a fix soon...

![img](https://i.imgur.com/OfSL0Fg.png)
