### ISSUE TITLE
Need progress reporting in the UI

### ISSUE THREAD

**Issue by shana** [github-for-unity/Unity#148]
We need a way to show progress reporting in the UI.

There are three types of progress reporting that I can see:

1. progress of background tasks, like fetching
2. progress of critical tasks, like pushing
3. UI loading and busy state

## Background tasks

Before, we were updating the busy status in the Unity task bar, which got lost in the task system rewrite, we should reintroduce it.

The problem with that is that the task bar is not connected visually with the user action: User clicks on Fetch in the top right area of the GitHub pane (which could be docked anywhere in the Editor), busy status occurs on the bottom right corner of Unity. I'm not sure it should be our main way of reporting progress of background tasks.

Given that most of the user actions occur from button clicks on the toolbar at the top of the pane, it would be nice to have an area close by that would show progress report for those tasks. As an example, in VS (and GHfVS) there's a subtle progress indicator bar at the top of the pane:

![progress-indicator-11](https://user-images.githubusercontent.com/310137/28717091-a7e82200-73a0-11e7-8f37-8b815276460a.gif)

## Critical tasks

Unity has a blocking progress dialog. We had this hooked up to critical tasks before, but it isn't in the new task system since the refactor. We should hook it up again.

## Almost-but-not-quite-critical tasks, UI busy state and loading

There are critical tasks that may not necessarily require blocking Unity, but they do require blocking our UI until they're completed. We can incrementally block the UI by:

- disabling specific buttons
- disabling views
- disabling the toolbar
- disabling everything

This will keep the users from shooting themselves in the foot (and we're already doing some of this), but it doesn't convey information about how long the task is going to take. We could overlay an animation on top of the view UI (below the toolbar) to show that something is happening (spinner animation anyone?). If we have a discrete animated bar on top as described above in the background tasks section, we could just use that as well - although I'm not sure that will be enough of a visual clue that something is happening and please wait for it?

-----

Thoughts, comments, suggestions?

/cc @donokuda @CapnRat @StanleyGoldman

**Comment by thorade** [comment]
A console that shows the git output as suggested in #50 would also help.

**Comment by linojon** [comment]
I have an unreliable network connection (DSL), especially for uploads. I need to know if/when pushes timeout and fail. In lieu of a UI solution, what can i do in the meantime to check the status? Is there a terminal command or something i can use? i check the github-unity.log file and see multiple "Connection to github.com closed by remote host."

**Comment by shana** [comment]
@linojon A push should report failure if it times out. I guess it isn't in your case?

**Comment by linojon** [comment]
Turns out it did, eventually, pop up a message. I do not know if it was pushing all that time, retrying, or just sitting there. With terminal "git push" and even Unity Collab, i can see the file count and progression. Thanks.

**Comment by shana** [comment]
Partially fixed in #771, need to surface the details of the git operation up to the UI (currently it says "pushing..." but not the specific progress reporting from git.
