### ISSUE TITLE
Exception Authenticating on Mac with master

### ISSUE THREAD

**Issue by ungb** [github-for-unity/Unity#168]
### Prerequisites

- Be sure to run with tracing enabled to capture runtime details in the log file
- Include the log file in the PR.
  - On Windows, the extension log file is at `%LOCALAPPDATA%\GitHubUnity\github-unity.log`
  - On macOS, the extension log file is at `~/.local/share/GitHubUnity/github-unity.log`

### Description

Can't login to github or initialize repo off master branch.  

### Steps to Reproduce

1. Build unitypackage from Master branch. Commit that was tested: `fd2a568a` on mac
2. Open Unity, Create a new project
3. Double click the unitypackage to install github.  
4. after install click initial repository

**Expected behavior:** [What you expect to happen]
Should Initialize repository 

**Actual behavior:** [What actually happens]
Get error:

```
ArgumentNullException: Failed Null Check on 'executableFileName'
Parameter name: executableFileName
GitHub.Unity.Guard.ArgumentNotNull (System.Object value, System.String name) (at C:/jenkins/workspace/Unity/Unity/src/GitHub.Api/Helpers/Guard.cs:27)
GitHub.Unity.ProcessManager.Configure[GitInitTask] (GitHub.Unity.GitInitTask processTask, System.String executableFileName, System.String arguments, GitHub.Unity.NPath workingDirectory, Boolean withInput) (at C:/jenkins/workspace/Unity/Unity/src/GitHub.Api/OutputProcessors/ProcessManager.cs:36)
GitHub.Unity.ProcessManager.Configure[GitInitTask] (GitHub.Unity.GitInitTask processTask, Boolean withInput) (at C:/jenkins/workspace/Unity/Unity/src/GitHub.Api/OutputProcessors/ProcessManager.cs:27)
GitHub.Unity.ProcessTaskExtensions.Configure[GitInitTask] (GitHub.Unity.GitInitTask task, IProcessManager processManager, Boolean withInput) (at C:/jenkins/workspace/Unity/Unity/src/GitHub.Api/NewTaskSystem/ProcessTask.cs:17)
GitHub.Unity.GitClient.Init (IOutputProcessor`1 processor) (at C:/jenkins/workspace/Unity/Unity/src/GitHub.Api/Git/GitClient.cs:151)
GitHub.Unity.ApplicationManagerBase.InitializeRepository () (at C:/jenkins/workspace/Unity/Unity/src/GitHub.Api/Application/ApplicationManagerBase.cs:91)
GitHub.Unity.HistoryView.DoOfferToInitializeRepositoryGUI () (at C:/jenkins/workspace/Unity/Unity/src/UnityExtension/Assets/Editor/GitHub.Unity/UI/HistoryView.cs:289)
GitHub.Unity.HistoryView.OnGUI () (at C:/jenkins/workspace/Unity/Unity/src/UnityExtension/Assets/Editor/GitHub.Unity/UI/HistoryView.cs:201)
GitHub.Unity.Window.OnUI () (at C:/jenkins/workspace/Unity/Unity/src/UnityExtension/Assets/Editor/GitHub.Unity/UI/Window.cs:125)
GitHub.Unity.BaseWindow.OnGUI () (at C:/jenkins/workspace/Unity/Unity/src/UnityExtension/Assets/Editor/GitHub.Unity/UI/Subview.cs:83)
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:222)


```
**NOTE: this seems to work fine on windows.  **

**Reproduces how often:** [What percentage of the time does it reproduce?]
100% of the time

### Additional Information

NOTE: built the unitypackage off jenkins off of a machine on windows, could it be that you can't build on windows and use the same executable on mac?

Build machine info:
Windows 64bit
Unity 5.6.2f1

Mac info that was installed on:
Mac 10.12.5
Unity 5.6.3f1
 

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by StanleyGoldman** [comment]
Hmm, I'm testing right now with a debug build of the current master on my mac. Although I dont get the error you are seeing, I'm not able to initialize the repository either. I'm going to try the commit you mentioned `fd2a568a` and see if it does me any differently

**Comment by StanleyGoldman** [comment]
Okay, so checking out that changeset I got something similar to what I had before.

Do you have git installed & configured on your mac?

**Comment by ungb** [comment]
Yes I do.

**Comment by StanleyGoldman** [comment]
Hey @ungb would you mind trying the latest release. It should resolve quite a few of your issues.

**Comment by StanleyGoldman** [comment]
Now that I think about it, I believe this was fixed by #173.
I'm going to close this for now.

**Comment by StanleyGoldman** [comment]
Hey @rdurnin we've had a few resurgences of this problem recently that I'm trying to track down.

If you have some time, I'd like to interactively debug this with you.
Can you catch me on gitter or discord?

**Comment by rdurnin** [comment]
Hey Stanley, and I would appreciate that. I will message you after I arrive
at work this morning.

r
