### ISSUE TITLE
Project window lock icons are too big on retina

### ISSUE THREAD

**Issue by StanleyGoldman** [github-for-unity/Unity#17]
Icons are kinda enormous on retina displays:

![image](https://cloud.githubusercontent.com/assets/310137/25408451/51c0d9ca-2a0e-11e7-8d6c-dbac59d07659.png)

Unity peeps tell me we can give Unity a sprite sheet texture instead of a single image and Unity will figure out which is the correct one to use based on the display dip. I'll try to get more information on this and update this issue.

**Comment by CapnRat** [comment]
@StanleyGoldman I can take a look at this.
