### ISSUE TITLE
Authentication validation on startup is often incorrect and drops credentials

### ISSUE THREAD

**Issue by StanleyGoldman** [github-for-unity/Unity#177]
It might just be an impression I'm getting, but I seem to lose my credentials way too often.

**Comment by missramos13** [comment]
What credentials are you losing

**Comment by StanleyGoldman** [comment]
I think the interaction between GitHub Desktop and GitHub for Unity on my machine are causing one not to recognize the credentials set by the other.

**Comment by missramos13** [comment]
That's a good thing if you think about it

**Comment by StanleyGoldman** [comment]
Lol, I'm not sure if you are trolling me but...

Since both GitHub for Unity both GitHub Desktop and GitHub Extension for Visual Studio use wincred for authentication.

If you authenticate in GitHub Desktop/Visual Studio with the same user as you have authenticated in GitHub for Unity. The expectation is that you remained logged into all three applications.

If you authenticate with a different user, then you will be logged out of the other two applications.

**Comment by StanleyGoldman** [comment]
Windows credentials as created by GitHub for Unity
![img](http://i.imgur.com/Dsa3XH2.png)

Windows credentials as created by GitHub wincred helper
![img](http://i.imgur.com/ABPpP01.png)

Windows credentials as created by GitHub Extension for Visual Studio
![img](http://i.imgur.com/BM6WizY.png)
