### ISSUE TITLE
Remote URL blank after publish

### ISSUE THREAD

**Issue by mardab** [github-for-unity/Unity#185]
tried this 6 times already, with 2 different copies of unity, but upon start lowest status bar consists of "initializing github for unity log file [...]" for hours. I decided to ignore it and proceeded to log in and link up my (currently empty) project to gitub repo, after pasting link to .git and clicking "save repository" plugin's settings UI becomes inactive, then entire unity slows down witin minutes. No matter what I change in my config, this is 6th time it does exactly that.

**Comment by StanleyGoldman** [comment]
Hey @mardab thanks for testing our stuff sorry the bugs are frustrating.
I'd like to try debugging your issue myself. Are you on gitter at all?

**Comment by StanleyGoldman** [comment]
I'm also re-reading your bug now to make sure I didn't miss anything and I caught something.

> tried this 6 times already, with 2 different copies of unity, but upon start lowest status bar consists of "initializing github for unity log file [...]" for hours. I decided to ignore it

It's normal for Unity to display the last debug log message in the status bar. It doesn't mean that something is still happening, but I understand how that can seem confusing, I'm going to change the message to `Initialized` so maybe the next person does not feel like they are waiting for something.

> link up my (currently empty) project to gitub repo, after pasting link to .git and clicking "save repository" plugin's settings UI becomes inactive

I think you are making a mistake in the workflow here..

If i understand correctly, if you have an empty repo already on GitHub. You should clone it locally to your computer and create a project in that folder with Unity.

Alternatively you can create a new project with Unity, Initialize the repository with GitHub for Unity and publish the repository GitHub for Unity.

Find me on Gitter or Discord and I will walk you through it.

**Comment by mardab** [comment]
which discord server?
