### ISSUE TITLE
Noticable lag in changes view between 0.15 and 0.16

### ISSUE THREAD

**Issue by aindriu80** [github-for-unity/Unity#191]
I just installed the Unity plugin After Dark.  When I try to make a commit and select some files the whole unity slows down.  Something wrong ?

**Comment by StanleyGoldman** [comment]
How many files are we talking about?

**Comment by StanleyGoldman** [comment]
The reason I say that is, I felt like there was a slight slowdown in the changes view between release `0.15` and `0.16`. I get the impression there is a slight jitter in the commit message as I type.

Is 0.16 the first release of GitHub for Unity that you've tried?

**Comment by aindriu80** [comment]
I imported all when asked from github extension. My own files only consist of 1 .cs and 2 images. Once I enter my github details unity becomes unresponsive. I had to ctrl alt delete to terminate.

I had used a previous version of the plugin and just followed the steps clicking next and it worked fine (except for push). That was a similar sized project ( very small)
________________________________

**Comment by aindriu80** [comment]
I tried an previous version and it was more responsive but missing most features. I was trying other versions but it says it is already installed - how do you remove?

**Comment by StanleyGoldman** [comment]
To uninstall GitHub for Unity, you have to close Unity first, then you will be able to delete the files.

**Comment by StanleyGoldman** [comment]
And thanks for the report, it was something i noticed as well.
I wasn't sure if it was just me needing 💤 though.

**Comment by aindriu80** [comment]
Do you know the last stable build ? I see most of them are alpha.
Which folder do you deleted ?
![2017-08-15 13_37_20-voxelinvaders](https://user-images.githubusercontent.com/8885837/29316222-01233d2e-81bf-11e7-9a45-44bc07f1934a.png)

**Comment by StanleyGoldman** [comment]
To remove GitHub for Unity, you want to delete:
1. `.\Assets\Editor\GitHub\`
2. `.\Assets\Editor\GitHub.meta`

**Comment by StanleyGoldman** [comment]
Our software is still alpha, so we don't have a really stable build yet.
We hope to get more stable and be in beta soon.

**Comment by aindriu80** [comment]
Thanks, I deleted folder and .meta as above and when I loaded back up Github was gone & everything working.  Nice and Easy.

Then I copied the folder and files I had in a previous Unity project and Github was back. Its quicker than the latest Alpha build and doesn't slow down all of Unity but when I am in the changes section of Github its pretty slow and I don't know why.  The project is pretty small but it seems to be trying to load a lot of files.  It doesn't push but previously worked well apart from that.

![2017-08-15 15_29_32-](https://user-images.githubusercontent.com/8885837/29320441-1b95246e-81cf-11e7-913f-7be1f78c77ce.png)

**Comment by aindriu80** [comment]
Do I import these files at the start ?
Maybe thats what is slowing everything down ?

![2017-08-15 17_34_29-unity 2017 1 0f3 personal 64bit - untitled - voxelinvaders - pc mac linux s](https://user-images.githubusercontent.com/8885837/29325566-177d421a-81e0-11e7-8196-2b2ed71eb4f5.png)

**Comment by StanleyGoldman** [comment]
I thought you were asking which folder to delete if you wanted to upgrade/downgrade the plugin. That was what those instructions were for.

We expect that users import all the files from the plugin. That is not what is slowing things down. There is a bug in the latest release that is slowing things down.

**Comment by aindriu80** [comment]
Thanks StanleyGolman !

**Comment by StanleyGoldman** [comment]
![image](https://user-images.githubusercontent.com/417571/33463900-fd231304-d60d-11e7-9157-5dab967fa1b8.png)

**Comment by StanleyGoldman** [comment]
Will be resolved by `0.26`
