### ISSUE TITLE
Add support for GitHub Enterprise

### ISSUE THREAD

**Issue by StanleyGoldman** [github-for-unity/Unity#2]
Copied from https://github.com/github-beta/unity-preview/issues/26

**Comment by CounterSeal** [comment]
Hello. Has there been any update on this?

**Comment by StanleyGoldman** [comment]
Hey @CounterSeal so far not yet, but thanks for asking. It helps to know what people are waiting for.

We have a pull request going in that is going to help with the authentication flows and patterns (#300).
That lays the ground work for GHE authentication. We can get GHE working soon after that.

**Comment by CounterSeal** [comment]
Cool, thanks for the update! Github Enterprise with SSH is kind of a deal breaker for us; the addition of those would be a major plus for us to further explore GH for Unity.

**Comment by GouletBah** [comment]
Any word on this?

**Comment by StanleyGoldman** [comment]
Hey @GouletBah I just got back from 🌴.
As soon as we start this I'll link a pull request to this issue.
We don't have much left to do!
We have these few big things which are a bit tricky, but that is all that we have left.
Hang in there please.

**Comment by CarmenPalMar** [comment]
I also second the idea that this would be amazing!

**Comment by StanleyGoldman** [comment]
I just released `v1.2.0-beta1`. This adds support for web authentication and GitHub Enterprise to GitHub for Unity.

I need your help in testing it out. Please give it a shot and let me know how it goes.
Upload any logs if you have issues.

https://github.com/github-for-unity/Unity/releases/tag/v1.2.0-beta1

cc: @CounterSeal @GouletBah @CarmenPalMar @knsh14

**Comment by StanleyGoldman** [comment]
Also cc: @brntbeer @fhernand @naikrovek cause you guys 👍 the original issue
