### ISSUE TITLE
Fix Create branch function to disallow branch that starts or end with '/'

### ISSUE THREAD

**Issue by StanleyGoldman** [github-for-unity/Unity#20]
If the branch name starts or ends with "/" it is invalid.

**Comment by thorade** [comment]
There are some more forbidden characters, e.g. any of  `~ ^ : \` and some more!
https://stackoverflow.com/questions/3651860/which-characters-are-illegal-within-a-branch-name

**Comment by StanleyGoldman** [comment]
I'm pretty sure we got most of that covered. Here in [Utility.cs#L31](https://github.com/github-for-unity/Unity/blob/b9289f491353c27166cd672aa800c48dae73db4f/src/UnityExtension/Assets/Editor/GitHub.Unity/Misc/Utility.cs#L31), please feel free to double check me.

What we aren't checking for is specifically starting or ending with `/`
