### ISSUE TITLE
Frozen settings view

### ISSUE THREAD

**Issue by smholsen** [github-for-unity/Unity#218]
### Description
Settings view is all disabled. 

### Steps to Reproduce
Sorry, but I do not have steps to reproduce.. I suspect a crash during initialization.

**Reproduces how often:** [What percentage of the time does it reproduce?]
First time using.

**Comment by FollowCD** [comment]
I met this problem today, I first build a 3D empty project with Unity 5.6.2f1 on Win10,  then I import the github for unity 0.16 version into the project ,then I initialization and succeed, then I login in the git and create a new repository on github , when i paste the url and press "save repository", then ,the setting view Frozened and in history view I can't pull or push ,only publish

**Comment by FollowCD** [comment]
And when I close the github tabel, then reopen it , there was nothing in Reopsitory Configuration, I thought it might be network error , but i can access github with chrome freely

**Comment by FollowCD** [comment]
that would be great!  i'm waiting for your upgrades

**Comment by FollowCD** [comment]
the 0.18.0 version solved this problem! tks! @StanleyGoldman

**Comment by StanleyGoldman** [comment]
Nice!
