### ISSUE TITLE
Changes view performance problems

### ISSUE THREAD

**Issue by StanleyGoldman** [github-for-unity/Unity#23]
As described in https://github.com/github-beta/unity-preview/issues/29, the Changes view can't handle more than 1500 files (probably less on less performant machines), so we have some improvements to make on this area.

**Comment by shiena** [comment]
Commit details view also has perfomance problems.
For example, this commit has changed 313 files. github-for-unity will be slower if you open it in the commit detail view.
https://github.com/unity3d-jp/piranhan/commit/7bbfaa9027456661c5a069e04b92ef2ff582e8af

**Comment by meaghanlewis** [comment]
@StanleyGoldman this is an issue we can close out when we release the latest version, right?

**Comment by StanleyGoldman** [comment]
![image](https://user-images.githubusercontent.com/417571/33799624-77dfce48-dcfd-11e7-841c-b54b9420ea25.png)

**Comment by StanleyGoldman** [comment]
![](https://i.imgur.com/DW2n6S2.gif)

**Comment by meaghanlewis** [comment]
this looks great 🎉 🎉 🎉

**Comment by StanleyGoldman** [comment]
The `0.26` release solves these issues
