### ISSUE TITLE
Extension should be installed in Assets/Plugins/GitHub folder

### ISSUE THREAD

**Issue by shana** [github-for-unity/Unity#243]
Related to https://github.com/github-beta/unity-preview/issues/19. We're currently installing into `Editor\GitHub`, which causes two problems:

1. There's a high probability that another plugin will have an Editor folder in the root. This can cause conflicts with meta files between both plugins
2. It's hard to encapsulate the extension inside a common folder in the current structure. If it's in `GitHub`, then we can have whatever we need in there and not worry about side effects or things spilling out (like meta files or gitignore files.

**Update**: Putting it in `Assets/Plugins` instead

**Comment by ericdrobinson** [comment]
If you haven't seen this yet, I would highly recommend taking a look at the "[Where to Install Your Assets (for Scripting Packages/Editor Extensions)](https://forum.unity3d.com/threads/where-to-install-your-assets-for-scripting-packages-editor-extensions.292674/)" thread in the Unity forums.

Seeing as how you are delivering nothing more than DLLs (beyond the _PlatformResources_), I would suggest that you move the main installation folder to the following location:

>_Assets/Plugins/GitHub_

Some reasoning:

1) You should not need the _Editor_ folder in the tree as everything is shipped as DLLs. The _Editor_ folder is for scripts (and, with recent versions of Unity, some _Resources_ content). DLL content is _only_ included in a build if it is referenced by runtime scripts or content.
1) Adding it to the _Assets/Plugins_ folder is a fairly standard approach. Many compliant extensions do this (some _have_ to for the [script compilation order benefits](https://docs.unity3d.com/Manual/ScriptCompileOrderFolders.html)).
1) It communicates the fact that the GitHub content is, indeed, a Plugin (extension).

**Comment by shana** [comment]
@ericdrobinson Thanks for the pointer, that makes sense and I had completely forgotten about the little compilation order detail. We'll move things around.

**Comment by thorade** [comment]
Note: One also has to update the .gitignore file!
