### ISSUE TITLE
could not push branch

### ISSUE THREAD

**Issue by DrEthan77** [github-for-unity/Unity#245]
I have recently tried getting this extension to work but I have been stopped by this bug.

       
[unity log.txt](https://github.com/github-for-unity/Unity/files/1262072/unity.log.txt)

whenever I try to push my stuff to the server, it fails.

Also, i have no idea if I installed everything correctly or not XD, it would be great if someone could make a video about installation and getting it all set up with someone else being able to push and pull stuff with you, that would be amazing.

**Comment by StanleyGoldman** [comment]
Hey @DrEthan77 thanks for testing our stuff out.

I will read that log file in a bit.

**Comment by DrEthan77** [comment]
Btw I am using Unity 2017 if you need the exact version I can get that, windows 10 and the newest version of this extension, version 18 I think.

**Comment by DrEthan77** [comment]
actually here is the full log just in case
[full unity log.txt](https://github.com/github-for-unity/Unity/files/1265168/full.unity.log.txt)

**Comment by StanleyGoldman** [comment]
Hmm... first off the second set of logs has a different error than the first set..
And both of these errors are coming from the git process.

Something about your git is misconfigured.
I see you are on discord, catch me or @shana on there and we will help you debug your shell.

**Comment by DrEthan77** [comment]
oh whoops XD i didn't think i did anything in between posting logs but i guess i did, i will try to recreate how i did it before.

**Comment by DrEthan77** [comment]
Ok so when i click on a commit i want to push it gives me that error again. so here it is
[New Text Document.txt](https://github.com/github-for-unity/Unity/files/1267311/New.Text.Document.txt)

**Comment by DrEthan77** [comment]
For now, i will just use GitHub for desktop instead of this extension...

**Comment by StanleyGoldman** [comment]
I sent you a few messages on discord.

**Comment by StanleyGoldman** [comment]
Hey @DrEthan77 what time zone are you in?

**Comment by StanleyGoldman** [comment]
I've been trying to catch you on discord.

**Comment by DrEthan77** [comment]
I am in mountain time zone

**Comment by StanleyGoldman** [comment]
Hey @DrEthan77 I'm on Discord today if you are around.

**Comment by StanleyGoldman** [comment]
Actually @DrEthan77 If you could confirm for me what your credential manager is.
Just run: `git config credential.helper` and let me know what the output is.

**Comment by DrEthan77** [comment]
wincred

**Comment by StanleyGoldman** [comment]
After doing some debugging with @DrEthan77 this issue is the same as #278

**Comment by StanleyGoldman** [comment]
I'm gonna close this issue out and track it there
