### ISSUE TITLE
Create a dedicated view to initialize the project

### ISSUE THREAD

**Issue by StanleyGoldman** [github-for-unity/Unity#251]
We need a dedicated view to handle project initialization and possibly the "first time git initialization".
It should provide the following features.

- A form to handle the git username and email.
  - Users may not have a this data on their machines already
  - This form should allow for validation errors
- A form that presents their git installation path
  - Users may want to change this path
  - This form should allow for validation errors
- A final button to initialize the project

The final work is being done in: 
- #261 
- [branch: initialize-view-with-configuration](https://github.com/github-for-unity/Unity/tree/fixes/initialize-view-with-configuration)

**Comment by StanleyGoldman** [comment]
@donokuda I'm going to need your magic here. I'm starting a branch and I'm going to start fleshing out the functionality

**Comment by donokuda** [comment]
@StanleyGoldman 👍 I've assigned myself and will start work on this later this afternoon or tomorrow!
