### ISSUE TITLE
Parent-child file selection in Changes view not working properly

### ISSUE THREAD

**Issue by shana** [github-for-unity/Unity#258]
Users should be able to select a file and deselect its meta file if they want to, but currently the UI is showing the parent file as deselected when the meta file is deselected, which is wrong. It looks like the information of what is selected is correct though, given that selecting the meta file again shows the parent as also being selected, so it's possible that the bug is when rendering the checkbox...

![parent-child-selection-not-working-properly](https://user-images.githubusercontent.com/310137/29932636-1b78138a-8e75-11e7-9134-7321fcfdc1c6.gif)

**Comment by StanleyGoldman** [comment]
As per comments in #542 this is no longer a relevant bug.
