### ISSUE TITLE
Cannot revert commits on Mac

### ISSUE THREAD

**Issue by meaghanlewis** [github-for-unity/Unity#269]
### Description
I am unable to revert commits on Mac. Tested with versions 0.18 and 0.19.

### Steps to Reproduce

1. Make a commit in a GitHub repo
2. Go to History
3. Right click on your commit in the list

**Expected behavior:** 
The revert option should be shown on right click as it does in Windows.

**Actual behavior:** 
Nothing happens on right click

**Reproduces how often:** 
100%

**Comment by shiena** [comment]
@meaghanlewis @StanleyGoldman 
I can revert on mac with version 0.19.
Strangely, Using control-clicking works fine with trackpad on macbook, tap with two fingers does not work.
<img width="319" alt="revert-menu-on-mac" src="https://user-images.githubusercontent.com/1295639/30001818-591e27cc-90d4-11e7-9021-a9f6ea815240.png">

**Comment by StanleyGoldman** [comment]
Good catch!

**Comment by meaghanlewis** [comment]
Closing this in favor of: https://github.com/github-for-unity/Unity/issues/684
