### ISSUE TITLE
Warn user if they attempt to commit a locked file

### ISSUE THREAD

**Issue by StanleyGoldman** [github-for-unity/Unity#27]

**Comment by rgjones33** [comment]
Does file (Unity scene for example ) locking work yet?

**Comment by StanleyGoldman** [comment]
@rgjones33 yes, locking files works in general. Right click the asset in the Asset Window, you will see the locking options.

**Comment by StanleyGoldman** [comment]
@rgjones33 Open a new issue and we can talk about that there...
