### ISSUE TITLE
GetConfig "credential.helper" returns "Process finished"; Can't Push

### ISSUE THREAD

**Issue by gdany95** [github-for-unity/Unity#278]
After some investigation the root cause is the return of `GitClient.GetConfig("credential.helper", ...)`.

https://github.com/github-for-unity/Unity/blob/e2814de101f64491ba5c46526592c1a8b335a0a1/src/GitHub.Api/Application/ApplicationManagerBase.cs#L66-L71

Outputs the following

```
170912-19:34:17 TRACE [ 1] <GitCredentialManager>              Loading Credential Helper
170912-19:34:18 TRACE [ 1] <GitCredentialManager>              Loaded Credential Helper: Process finished
```

Meanwhile, on my machine I get the following output

```
170912-13:47:25 TRACE [ 1] <IApplicationManager>               Windows CredentialHelper: wincred
170912-13:47:25 TRACE [ 1] <IApplicationManager>               Restarted 
```

If the user then attempts to authenticate, the following proceeds.
- GH4U believes `Process` is the credential manager
- If they successfully authenticate, GH4U believes they are authenticated when they are not because credentials cannot be saved and the process is not transactional
- If they successfully auithenticate, they cannot sign out, because we first attempt to clear credentials of the `Process` credential manager

[github-unity.txt](https://github.com/github-for-unity/Unity/files/1296813/github-unity.txt)

**Original text**:
> Creating my first project and trying to push it to GitHub does not work. It just opens a dialog saying "Could not push branch". The project is created in the GitHub repository. I'm using Windows 7 with Unity 5.6.3f1
> 
> **Expected behavior:** Push the initial commit to Git
> 
> **Actual behavior:** Push fails
> 
> **Reproduces how often:**Every time
> [github-unity.txt](https://github.com/github-for-unity/Unity/files/1277863/github-unity.txt)

**Comment by StanleyGoldman** [comment]
Hey @gdany95 sorry I haven't responded sooner.
I was crazy busy last week.

If you have some time, I'd like to interactively debug this with you.
Can you catch me on gitter or discord?

**Comment by StanleyGoldman** [comment]
Hey @gdany95 I need more of the git log than what you sent.
Can you send me the full thing?

**Comment by gdany95** [comment]
What is your id on Discord ? 

    On Monday, September 11, 2017 6:00 PM, Stanley Goldman <notifications@github.com> wrote:
 

 Hey @gdany95 I need more of the git log than what you sent.
Can you send me the full thing?—

**Comment by StanleyGoldman** [comment]
Ack sorry, I didn't see this message.
There is a discord channel.

https://discord.gg/5zH8hVx

**Comment by StanleyGoldman** [comment]
I had @gdany95 run a build of #296. Which captures the following log output:
```
170912-19:34:17 TRACE [ 1] <GitCredentialManager>              Loading Credential Helper
170912-19:34:18 TRACE [ 1] <GitCredentialManager>              Loaded Credential Helper: Process finished
```

**Comment by StanleyGoldman** [comment]
Updated the title and body of the issue

**Comment by StanleyGoldman** [comment]
After some debugging with @DrEthan77 we were able to determine another clue.

If you open a git enabled console with Unity
![img](https://i.imgur.com/mz9hBTd.png)

Run `git config credential.helper`
![img](https://i.imgur.com/kKKjMQa.png)

Meanwhile if you try the same in a regular console on the same machine
![img](https://i.imgur.com/w41Eg2q.png)

@gdany95 let me know if you are able to reproduce this

**Comment by StanleyGoldman** [comment]
"Curiouser and curiouser"

**Comment by StanleyGoldman** [comment]
Hey @gdany95 and @DrEthan77

Can you guys reproduce either the authentication or push bugs and send us:
- the `editor.log` from Unity
  - You can find it at `C:\Users\[Username]\AppData\Local\Unity\Editor\Editor.log`
- a screenshot of your System Information page so we be sure about what version of Windows you guys are running

Thanks

**Comment by gdany95** [comment]
[github-unity.txt](https://github.com/github-for-unity/Unity/files/1303294/github-unity.txt)

![sys](https://user-images.githubusercontent.com/25885195/30434622-6fbcf4c8-9970-11e7-9ef4-b757cce5945b.png)

**Comment by StanleyGoldman** [comment]
I'm able to reproduce this now.

@gdany95 and @DrEthan77 do either of you have "Git for Windows" installed on your machines?

**Comment by StanleyGoldman** [comment]
Using Windows 10 in a virtual machine that is fully patched.
I installed Unity 5.5.4 and let the Visual Studio dependency be installed.
Manually created the settings to capture trace logging.
Brand new project in Unity. Install the plugin. Observed the following log:

```
170914-09:17:06  INFO [ 1] <Global>                            Initializing GitHub for Unity version 0.21.0
170914-09:17:06 TRACE [ 1] <IApplicationManager>               Run - CurrentDirectory C:\Users\StanleyGoldman\Documents\New Unity Project
170914-09:17:06 TRACE [ 1] <GitInstaller>                      SetupIfNeeded
170914-09:17:06 TRACE [ 1] <GitInstaller>                      SetupGitIfNeeded
170914-09:17:06 TRACE [ 1] <GitInstaller>                      C:\Users\StanleyGoldman\AppData\Local\GitHubUnity\PortableGit_f02737a78695063deace08e96d5042710d3e32db\cmd\git.exe not installed yet
170914-09:17:06 TRACE [ 1] <GitInstaller>                      Extracting "Assets\Plugins\GitHub\Editor\PlatformResources\windows\git.zip" to "C:\Users\STANLE~1\AppData\Local\Temp\github-unity-portable_391657362\git"
170914-09:18:56 TRACE [ 1] <GitInstaller>                      Moving "C:\Users\STANLE~1\AppData\Local\Temp\github-unity-portable_391657362\git" to "C:\Users\StanleyGoldman\AppData\Local\GitHubUnity\PortableGit_f02737a78695063deace08e96d5042710d3e32db"
170914-09:18:56 TRACE [ 1] <GitInstaller>                      SetupGitLfsIfNeeded
170914-09:18:56 TRACE [ 1] <GitInstaller>                      C:\Users\StanleyGoldman\AppData\Local\GitHubUnity\PortableGit_f02737a78695063deace08e96d5042710d3e32db\mingw32\libexec\git-core\git-lfs.exe not installed yet
170914-09:18:56 TRACE [ 1] <GitInstaller>                      Extracting "Assets\Plugins\GitHub\Editor\PlatformResources\windows\git-lfs.zip" to "C:\Users\STANLE~1\AppData\Local\Temp\github-unity-portable_391657362\git-lfs"
170914-09:18:56 TRACE [ 1] <GitInstaller>                      Copying "C:\Users\STANLE~1\AppData\Local\Temp\github-unity-portable_391657362\git-lfs\git-lfs.exe" to "C:\Users\StanleyGoldman\AppData\Local\GitHubUnity\PortableGit_f02737a78695063deace08e96d5042710d3e32db\mingw32\libexec\git-core\git-lfs.exe"
170914-09:18:57 TRACE [ 1] <IApplicationManager>               Setup performed using new path
170914-09:18:57 TRACE [ 1] <IApplicationManager>               Environment.GitExecutablePath "C:\Users\StanleyGoldman\AppData\Local\GitHubUnity\PortableGit_f02737a78695063deace08e96d5042710d3e32db\cmd\git.exe" Exists:True
170914-09:18:57 TRACE [ 1] <GitClient>                         GetConfig
170914-09:18:57 TRACE [ 1] <GitConfigGetTask>                  Starting Concurrent 1 git config get GitHub.Unity.GitConfigGetTask C:\Users\StanleyGoldman\AppData\Local\GitHubUnity\PortableGit_f02737a78695063deace08e96d5042710d3e32db\cmd\git.exe config --get --system credential.helper
170914-09:18:57 TRACE [ 1] <ActionTask>                        Starting Concurrent 2 ActionTask(Task) GitHub.Unity.ActionTask
170914-09:18:57 TRACE [ 3] <GitConfigGetTask>                  Executing 1 git config get GitHub.Unity.GitConfigGetTask C:\Users\StanleyGoldman\AppData\Local\GitHubUnity\PortableGit_f02737a78695063deace08e96d5042710d3e32db\cmd\git.exe config --get --system credential.helper
170914-09:18:57 TRACE [ 4] <ActionTask>                        Executing 2 ActionTask(Task) GitHub.Unity.ActionTask
170914-09:18:57 TRACE [ 3] <GitConfigGetTask>                  Executing 1 git config get GitHub.Unity.GitConfigGetTask C:\Users\StanleyGoldman\AppData\Local\GitHubUnity\PortableGit_f02737a78695063deace08e96d5042710d3e32db\cmd\git.exe config --get --system credential.helper
170914-09:18:57 TRACE [ 4] <ActionTask>                        Finished 2 ActionTask(Task) GitHub.Unity.ActionTask
170914-09:18:57 TRACE [ 3] <ProcessWrapper>                    LineReceived: "[NULL]"
170914-09:18:57 TRACE [ 3] <GitConfigGetTask>                  Finished 1 git config get GitHub.Unity.GitConfigGetTask C:\Users\StanleyGoldman\AppData\Local\GitHubUnity\PortableGit_f02737a78695063deace08e96d5042710d3e32db\cmd\git.exe config --get --system credential.helper
170914-09:18:57 TRACE [ 3] <GitConfigGetTask>                  Finished 1 git config get GitHub.Unity.GitConfigGetTask C:\Users\StanleyGoldman\AppData\Local\GitHubUnity\PortableGit_f02737a78695063deace08e96d5042710d3e32db\cmd\git.exe config --get --system credential.helper Process finished
170914-09:18:57 TRACE [ 5] <ProcessWrapper>                    ErrorData: "[NULL]"
170914-09:18:57 TRACE [ 6] <ActionTask>                        Starting Concurrent 3 Then GitHub.Unity.ActionTask
```

**Comment by StanleyGoldman** [comment]
And I've located the bug...

https://github.com/github-for-unity/Unity/blob/5bdccf8a45bc7d74029e0222a539ec9aea7337c5/src/GitHub.Api/NewTaskSystem/ProcessTask.cs#L282-L300
