### ISSUE TITLE
How to uninstall?

### ISSUE THREAD

**Issue by rico345100** [github-for-unity/Unity#283]
### Description
There is no description how to remove this extension from Unity. Also I couldn't found any related feature to remove.

How do I remove this?

**Comment by thorade** [comment]
Unity treats it like a normal asset of your project, so you should be able to just delete the folder.

Either from the Explorer, the extension is stored at 
`%USERPROFILE%\Documents\Unity Projects\YourProject\Assets\Plugins`
just delete the GitHub folder and the GitHub.meta file.

Or from within Unity as shown below:
![asset_delete](https://user-images.githubusercontent.com/314571/30107665-bfba6e82-92ff-11e7-8a08-361de2bf6baf.png)

**Comment by shana** [comment]
@rico345100 As @thorade explained, you can just delete the folder where the extension is. If you're on Windows, Unity may complain that files are being used and can't delete them. In that case, you can right click on the folder in the Project window and select ***Show in Explorer***, which will open an explorer window in the location where the extension is. Then quit Unity and delete the ***GitHub*** folder from the explorer window, that will be enough to uninstall the extension from that project.
