### ISSUE TITLE
Publishing a repository from Unity does not capture description

### ISSUE THREAD

**Issue by meaghanlewis** [github-for-unity/Unity#301]
### Description

I noticed that when I publish a new repository in Unity with a name and description, the description of the repository does not get pushed to .com.

### Steps to Reproduce

1. Create a new project. Import the GitHub extension
2. Create initial commit
3. Publish repo with name and description
<img width="305" alt="screen shot 2017-09-11 at 2 03 48 pm" src="https://user-images.githubusercontent.com/10103121/30297074-53e1ce26-96fb-11e7-864f-b9cd42f67336.png">

**Expected behavior:** 
Description is persisted and can be seen on .com

**Actual behavior:**
<img width="724" alt="screen shot 2017-09-11 at 2 05 56 pm" src="https://user-images.githubusercontent.com/10103121/30297071-51a62030-96fb-11e7-96ed-ff7e0913ee73.png">

**Comment by StanleyGoldman** [comment]
Thanks @meaghanlewis. Fixed in the next release.
