### ISSUE TITLE
Authenticate menu option should disappear after successfully authenticating with GitHub

### ISSUE THREAD

**Issue by meaghanlewis** [github-for-unity/Unity#306]
### Description
The GitHub menu always shows the Authenticate option.

### Steps to Reproduce

1. Go to GitHub > Authenticate
2. Sign in with GitHub
3. Go to GitHub > Authenticate again

**Expected behavior:** 
The Authenticate option should not be shown in the GitHub menu.

![authenticate option](https://user-images.githubusercontent.com/10103121/30338431-88f38aa0-97a0-11e7-9505-d9c8a45cefbc.png)

**Comment by shana** [comment]
So this menu item is kinda temporary for debugging purposes while we're in alpha, to simplify access to the UI. It's not really meant to be around for the release version - the "real" menu lives in the GitHub toolbar and changes depending on your logged in status.
