### ISSUE TITLE
FAQ for contirbutions

### ISSUE THREAD

**Issue by AkashGutha** [github-for-unity/Unity#314]
I think we should have a FAQ section for contributions. 

This will help new contributors without having them to raise new issues.

**Comment by AkashGutha** [comment]
The issues I had doing a fresh pull are:
1. No Octokit references
2. No sfw references and many usch. 
Total of 50 Build errors of the unable to find refs.

This leads to the unity scene having extra issues.

**Comment by StanleyGoldman** [comment]
Hi @AkashGutha.
You are right, things are a bit hard to get started with right now. We have had many people try, so we were not sure where the sticking points would be. So thanks for taking the plunge.

Since you are new to this project, you would be the best first source of FAQs. Start a pull request and we can all add to it.

Now, in regards to your first FAQ.

> The issues I had doing a fresh pull are:
> 
>     No Octokit references
>     No sfw references and many usch.
>     Total of 50 Build errors of the unable to find refs.
> 
> This leads to the unity scene having extra issues.

Those libraries are in fact included. I believe the problem is you do not have Git LFS installed.
https://git-lfs.github.com/

After you install git lfs, the next time you clone a lfs repo, you will not have this problem.
Reclone the repo, or you can fix the current clone by running `git lfs checkout`.

**Comment by StanleyGoldman** [comment]
We did **_try_** to write _**some**_ documentation...
Check these links out and maybe then can answer some questions for you...

https://github.com/github-for-unity/Unity/blob/master/docs/contributing/how-to-build.md
https://github.com/github-for-unity/Unity/blob/master/CONTRIBUTING.md#how-can-i-contribute

Now that I look at it again, the How to Build document **_does_** mention that you need Git LFS.
Maybe we should organize it differently? Let us know.

**Comment by StanleyGoldman** [comment]
Also, you can usually find us to chat on Gitter and Discord.

https://discordapp.com/invite/5zH8hVx

https://gitter.im/github-for-unity/Unity

**Comment by AkashGutha** [comment]
Oh. That was my mistake. I was looking at installation guide. I had mono 5.x.x installed.

Yea. The installation guide has ``` git lfs ```  mentioned.
 It would be good if it is mentioned in the build guide too.

**Comment by StanleyGoldman** [comment]
I don't think it's your fault. The stuff is confusing.

As long as you have Git LFS installed, `git clone` and `git lfs clone` will do the same thing. The only difference is `git lfs clone` is faster.

**Comment by AkashGutha** [comment]
I'm constantly getting this issue while doing a ```git lfs checkout``` 

<img width="1280" alt="screen shot 2017-09-15 at 12 53 34 pm" src="https://user-images.githubusercontent.com/10159531/30475097-4adfc258-9a23-11e7-8009-21f373065fd1.png">

**Comment by StanleyGoldman** [comment]
That's strange. I'm gonna talk to the platform team about that.
What version of git and git lfs do you have installed?

run: `git --version` & `git lfs version`

**Comment by AkashGutha** [comment]
Here 
<img width="740" alt="screen shot 2017-09-15 at 6 01 18 pm" src="https://user-images.githubusercontent.com/10159531/30482271-eab4bf92-9a3f-11e7-82f4-f64bb4cab07e.png">

**Comment by StanleyGoldman** [comment]
Hey @AkashGutha find me on discord.

https://discordapp.com/invite/5zH8hVx

**Comment by shana** [comment]
We already have documentation about how to clone and build the project.
