### ISSUE TITLE
Global .gitconfig with name/email is required

### ISSUE THREAD

**Issue by thorade** [github-for-unity/Unity#315]
### Prerequisites

- Be sure to run with tracing enabled to capture runtime details in the log file
- Include the log file in the PR.
  - On Windows, the extension log file is at `%LOCALAPPDATA%\GitHubUnity\github-unity.log`
[github-unity-log.txt](https://github.com/github-for-unity/Unity/files/1302222/github-unity-log.txt)

### Description

Hitting the commit button deletes the commit message, but no commit shows up in the history.

### Steps to Reproduce

1. Did a fresh clone of a unity/github testing repository, it was uploaded from PC1 and cloned on PC2 using Sourcetree.
2. Open the repo/project in Unity, import github for unity v0.20
3. gh4u thinks some files have been deleted and created, e.g. the .gitignore file. Some other git tools show it like that when a file has been renamed!?
4. Select the deleted and the created gitignore file and try to commit, but no commit shows up in the history

**Comment by thorade** [comment]
Part 2: I then used Sourcetree to commit and it worked. Afterwards, I triued to use gh4u to push the updated branch and it fails, might be the same issue as #278. (Also, yet another colleague also runs into that issue).

Here is the new log:
[github-unity-log.txt](https://github.com/github-for-unity/Unity/files/1302254/github-unity-log.txt)

And the editor log:
[Editor-log.txt](https://github.com/github-for-unity/Unity/files/1302294/Editor-log.txt)

Similar as in #278, running `git config credential.helper` from the Unity->github->Commandline does not return anything. Running the same command from the normal Win10 cmd returns: command git not found or misspelled (or similar, translated from German).

Here is a screenshot of the system information:
![win10_pro_sys](https://user-images.githubusercontent.com/314571/30419475-c05fa9b4-9936-11e7-8f90-cf823d35b091.png)

**Comment by StanleyGoldman** [comment]
Hey @thorade thanks for helping out.

So it seems like you are running into two different issues. The first it seems that the machine that cannot commit may not have git user and email configured globally. This is a problem we have to solve with some UI work on our part. We hope to solve that soon.

The other problem that you are experiencing is one that I'm really interested in at the moment.
As you noticed, we are having trouble determining the git credential manager that is configured on your machine.

Would you happen to have some time today so we can do some live debugging? We have not been able to reproduce that second issue ourselves...

**Comment by thorade** [comment]
Yes, I would have time right now, but I have to leave in ~1 hour.
What should I do? Register with discord?

**Comment by StanleyGoldman** [comment]
Yea, sign up on discord if you can.

https://discordapp.com/invite/5zH8hVx

**Comment by thorade** [comment]
Regarding the global git config: This machine does not have a global git, just the embedded/portable git that comes with Sourcetree and the one that comes with your plugin.

**Comment by StanleyGoldman** [comment]
Thanks for the confirmation about the global git config.
I will make this issue about the requirement of a global git config.
Since your other issue is #278 exactly, we can track that progress there.
