### ISSUE TITLE
Unable to manage branches after re-opening GitHub window

### ISSUE THREAD

**Issue by meaghanlewis** [github-for-unity/Unity#343]
### Description
I'm unable to view/create/delete my branches in a couple different scenarios. The workaround I've found when I get into these scenarios is to restart Unity completely, but that's not ideal.

#### Scenario 1
1. Create new project, initialize repo, publish
2. In GitHub window, go to `Branches` tab
3. See if you can view/create/delete branches

#### Scenario 2
1. Start Unity
2. If GitHub window was open before, it will be open again and you can manage branches fine.
3. Close GitHub window
4. Re-open GitHub window
5. See if you can view/create/delete branches

**Expected behavior for both scenarios**:
Can manage my branches
![screen shot 2017-09-21 at 10 35 57 am](https://user-images.githubusercontent.com/10103121/30711075-7040fb0a-9ebc-11e7-8a75-835960914365.png)

**Actual behavior**:
![branch situation](https://user-images.githubusercontent.com/10103121/30710664-25326cd0-9ebb-11e7-9dc7-2c3f7cc749c4.gif)

### Additional Information
This behaves the same in both Windows and Mac with the latest build `0.21.1`. I don't see any helpful information in the logs :(

I only ended up trying to close and open the tab because I'm not able to see my newly created branch without trying to "jiggle the handle" as Stanley would say.

**Comment by StanleyGoldman** [comment]
>"jiggle the handle" as Stanley would say

The things you get quoted for...

**Comment by StanleyGoldman** [comment]
Related #344 

I'm hoping @shana tree changes will fix both of these issues
