### ISSUE TITLE
Master branch does not appear in branches list after initialization

### ISSUE THREAD

**Issue by StanleyGoldman** [github-for-unity/Unity#344]
1. Initialize Repo
1. Goto Branches View
1. Observe master branch is not present in "Local Branches"
1. Close & Reopen Unity
1. Goto Branches View
1. Observe master branch is present in "Local Branches"

**Comment by StanleyGoldman** [comment]
I thought this was being caused in #324 but I see it in master

**Comment by thorade** [comment]
Possibly the same issue: If I update the package to the latest version in a project that already is a git repo and that has multiple branches, then right after the update the branches are not visible until I close and restart Unity.

**Comment by StanleyGoldman** [comment]
Hey @thorade thanks for the confirmation. Yea it sound like the same problem to me.
