### ISSUE TITLE
Initialise Git repository that's not in the root folder?

### ISSUE THREAD

**Issue by twomedia** [github-for-unity/Unity#346]
Is it possible to initialise this plugin to use a git repository located in a sub-directory and not the root of the project? (E.G. the scripts folder)

**Comment by StanleyGoldman** [comment]
Hey @twomedia, that is an interesting idea. It would pose a few technical problems with how we have things currently. We will have to consider it.

Can you expand on your use case? I could guess, but it's better if you explain how you would see it working.

**Comment by twomedia** [comment]
Hi @StanleyGoldman 

Currently we are using Unity Collab as it works great for scene merging; The downside is it's terrible at script merging (Always replacing someones work or corrupting files). We currently have a solution where Unity Collab ignores changes to the Scripts folder and it is tracked by Git instead. Being able to manage this git repository inside unity would be a great.

**Comment by rossborchers** [comment]
Hey just to add to this, we use [Projeny](https://github.com/modesttree/projeny). It stores content and scripts outside of the assets directory and composes projects with junctions. Reusable code exists in a different directory to the project code... etc. 
It would be great to have the ability to initialize the repository at an arbitrary path.
