### ISSUE TITLE
.editorconfig

### ISSUE THREAD

**Issue by dangphuocthao** [github-for-unity/Unity#347]
### Prerequisites

- Be sure to run with tracing enabled to capture runtime details in the log file
- Include the log file in the PR.
  - On Windows, the extension log file is at `%LOCALAPPDATA%\GitHubUnity\github-unity.log`
  - On macOS, the extension log file is at `~/Library/Application Support/GitHubUnity/github-unity.log`

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by dangphuocthao** [comment]
.editorconfig

**Comment by StanleyGoldman** [comment]
Hey @dangphuocthao I think you made this in error, I'm going to close it.
