### ISSUE TITLE
Remove *.DAE files from git lfs tracking

### ISSUE THREAD

**Issue by thorade** [github-for-unity/Unity#349]
### Description
Initializing a repo with the plugin creates a `.gitattributes` file with git-lfs related settings for a couple of file formats.
Most of the 3D formats are binary, but DAE is not, it is text, and I would like to see meaningful diffs for it, but currently I only get `Git LFS file not shown` instead of a diff.

### Steps to Reproduce
1. upload some DAE file
2. change dae file and push changes
3. try to see a diff showing the changes

### Additional Information
Maybe that is the intended behavior?
Or the wrong repo to report this?

**Comment by mpOzelot** [comment]
Maybe the user should be able to choose filters before init?

**Comment by shana** [comment]
This is totally the correct repo, thanks for filing this issue! I confess I took a huge list of media formats and dumped it into the .gitattributes file without investigating whether they were all binary or large.

What is the average size of a DAE file? If it tends to be more than 100MB on average, then it kinda needs to be in LFS because github has a limitation on the size of files you can push. If not, then DAEs should not be in .gitattributes.

**Comment by shana** [comment]
Also wrt configuring filters, yeah that's a thing we want to add as well, we'll be creating a separate issue to track that feature soon.

**Comment by thorade** [comment]
We are using Unity for architecture visualization, so the requirements are also not representative I guess.
My DAE files are between 5MB for a simple test case up to 50MB for a multi-storey building.
Does LFS distinguish between binary and text files? Can I store a text file on LFS and still see a diff?

**Comment by shana** [comment]
@thorade Right now, LFS makes no distinction between binary and text and doesn't support diffing, it just treats everything as a blob. This is a known limitation and will hopefully be fixed soon. In the meantime, git should be able to handle those sizes well enough. We'll take out DAE from the list of files to be tracked by lfs by default for the next release.

Until we have support for configuring the filters via the UI, though, you'll need to untrack that filetype manually by either running `git lfs untrack '*.dae'` or by removing the line from `.gitattributes` manually.

**Comment by StanleyGoldman** [comment]
Maybe I can get a hacktoberfest contributor to take care of this one...
