### ISSUE TITLE
Changed View not rendering tree view correctly after a script is compiled

### ISSUE THREAD

**Issue by mpOzelot** [github-for-unity/Unity#357]
### Description

In the UnityExtention project, the tree disappears after compiling a script.

### Steps to Reproduce

1. Open UnityExtention project
2. GitHub -> Show Window
3. Select the Changed tab
4. Open a script file and trigger a compile by modifying something and then saving
5. Go back to Unity

**Expected behavior:**
The Changed view should update the Tree View and display the changes

**Actual behavior:**
The Tree View shows the text "No changes found"

**Reproduces how often:**
Always (5.6.3p1)

### Additional Information
Switching to the History tab and back fixes it

**Comment by StanleyGoldman** [comment]
Good catch, I should have this one fixed soon!
