### ISSUE TITLE
Move strings for labels and prompts in code to resource

### ISSUE THREAD

**Issue by StanleyGoldman** [github-for-unity/Unity#36]
There are many strings that should be moved to a resource all over the application.

**Comment by AkashGutha** [comment]
I'll do this. 👍 
I've checked #12.

So shall we move this to a JSON file and Load it using a resource loader?

Or just make a Resources class with Static constant strings ??

**Comment by StanleyGoldman** [comment]
Hmm. @shana what would be best here?

**Comment by AkashGutha** [comment]
Oh. I didn't see localization was also in the pipeline. I think having a JSON file and then a LocalizedStringLoader would do the trick.

We can also do a resx file. the only caveat I see is portability.
But resx files are easier to use in a .NET env

**Comment by Frozenfire92** [comment]
This is a pretty common practice in Unity development. Having a static class containing string variables (or Properties for localization down the road). It will make maintenance and updating these much easier

@AkashGutha are you still doing this?

**Comment by AkashGutha** [comment]
@Frozenfire92 nope. you can work on this.
