### ISSUE TITLE
Portable Installation

### ISSUE THREAD

**Issue by GalHorowitz** [github-for-unity/Unity#365]
I have a computer which Unity can't be installed on. Fortunately, you can install Unity directly onto a USB drive, by changing the installation directory. But if I want to use Github for Unity, I cannot do that, because the installation of portable git and other files under the GithubUnity folder. It would be much appreciated if there would be any way to change the location of the directory, allowing me to continue with my workflow.
Thank You!

**Comment by StanleyGoldman** [comment]
Hey @GalHorowitz thanks for wanting to use our stuff. Sorry it won't work in your use case.
It's an interesting idea. We can see about making the plugin more portable at some point in the future.

**Comment by GalHorowitz** [comment]
Hmm OK. Anyway, with the current implementation, if I open a project with the extenstion installed, and the directory does not exist, will it create it?

**Comment by StanleyGoldman** [comment]
Yea, it definitely try to put stuff in your `AppData` folder... assuming you are on Windows...

Is it like a school computer that is going to get wiped out regularly?

**Comment by GalHorowitz** [comment]
Exactly.

**Comment by StanleyGoldman** [comment]
LOL, how did I guess?

Okay, but the school computer won't stop us from writing to that folder?
It's just going to lose your authentication and some of your minor settings..

**Comment by GalHorowitz** [comment]
I was just wondering if the extenstion was going to die when the directory gets removed. If not, then great, I can use this.

**Comment by StanleyGoldman** [comment]
Okay, so you should be good.
Every time you use the plugin, it will setup all the stuff in those folders like new.
The worst problem is you will have to authenticate again.

I think we can close this issue...
