### ISSUE TITLE
Visual Studio Settings file using style guide

### ISSUE THREAD

**Issue by mpOzelot** [github-for-unity/Unity#374]
### Description
I have created a VS [settings file](https://drive.google.com/file/d/0B8VR-TtdAacnWnRwaktQamhNcXc/view?usp=sharing) consistent to the style guide presented in https://github.com/github-for-unity/Unity/blob/master/docs/contributing/styleguide.md

Where should I put this file, and an explanation on how to import it in VS?

### Additional Information
The file only contains Text Editor settings for C#.
This file was created in VS 2015, but it should work in any version above that.

**Comment by shana** [comment]
Hey @mpOzelot!

So except for the indentation settings, most of these settings seem to be related to how VS is configured to work, and not how the code is styled. I don't personally have `BraceCompletion` on in my VS (my fingers automatically type them and it gets really annoying when the editor does it too), I have `HideAdvancedMembers=false`, and I definitely have `ShowErrors=false`, for instance. I imagine if I put my vssettings in the repo and told people to import it, I'd get some pissed off people. Also, this file, when imported, changes how VS works for all projects, not just for the current one, which is not something that we should be doing on our project.

The tab and indentation settings are definitely useful, if people want to make that their default VS configuration. I just don't know if that's a useful thing to have in our repository... Thoughts anyone?

/cc @StanleyGoldman @CapnRat @MunchyYDL (random pinging of people I know have feels on code editor customization)

**Comment by mpOzelot** [comment]
Hey @shana,

> I imagine if I put my vssettings in the repo and told people to import it, I'd get some pissed off people.

didn't realize the brace completion settings were also exported, thanks for pointing that out.
I did notice that it is possible to only export formatting settings though, but I am not sure that's a solution either.
![image](https://user-images.githubusercontent.com/8388744/31719361-7466ab50-b413-11e7-8e92-dc146a6227c6.png)

> Also, this file, when imported, changes how VS works for all projects

That's a pretty big issue indeed, I'm not even sure if there are project specific settings...
