### ISSUE TITLE
Document SubView Virtual methods

### ISSUE THREAD

**Issue by StanleyGoldman** [github-for-unity/Unity#380]
Based on [comments](https://github.com/github-for-unity/Unity/pull/376#issuecomment-338268293) by @shana 

>documenting the virtual method is probably a good thing to do... "When overriding, double check that the parent view or window calls your override"

**Comment by Bubblemelon** [comment]
Hello @StanleyGoldman, has this been resolved? Would it be possible if I could help make changes to the documentation?

**Comment by StanleyGoldman** [comment]
Hey @Bubblemelon I haven't tried to do this one yet.
You are more than welcome to start, and I'll help if needed.
