### ISSUE TITLE
Refactor Repository Initialize method to not repeatedly call git commands

### ISSUE THREAD

**Issue by shana** [github-for-unity/Unity#409]
As per https://github.com/github-for-unity/Unity/pull/390/files#r148985932, the Repository Initialize method shouldn't be calling git commands every time it runs, because it's going to run every time play mode is entered, which is really not something we want to do.

It probably needs to be something that happens when someone checks for the cache and the cache requests the data because it's either 1) too old, 2) has no data, 3) initialRun is true in ApplicationCache object, or in some way check that after the first run we update data.

Maybe it makes sense for the cache objects to check that flag to see if they need to ask for new data when the views ask for data?

Maybe we should store a timestamp of when Unity first started up so the cache objects can check whether the cached data is older than data and request updated data when the views ask for data? 

Maybe some other solution makes sense here.

**Comment by StanleyGoldman** [comment]
https://github.com/github-for-unity/Unity/blob/ad226ddadaa621216a96583218fdf8afcbbf1d7a/src/GitHub.Api/Git/Repository.cs#L62-L65
