### ISSUE TITLE
Cannot update path to git

### ISSUE THREAD

**Issue by meaghanlewis** [github-for-unity/Unity#437]
### Description
I updated the Path to Git with a version of Git that I didn't want to use. Now I'm unable to change the git path back to what it was previously.

![cannot update git installation](https://user-images.githubusercontent.com/10103121/32787318-1e0f93c2-c90b-11e7-95d8-b544f144cb46.gif)

### Steps to Reproduce

1. Go to Settings tab
2. Update Path to Git. Save
3. Update Path to Git again. Save

**Expected behavior:** [What you expect to happen]
I can update my git path successfully

**Actual behavior:** [What actually happens]
Cannot update the git path and the Settings tab becomes unusable after saving with a new path because all the fields are disabled. Switching away from the tab changes the git path value to what it was previously set to.

Don't see anything helpful in the logs, just this `171114-07:16:07 TRACE [ 1] <GitPathView>                       Validating Git Path:/usr/local/bin/git` but the new git version never appears to finish validating or updating

**Comment by meaghanlewis** [comment]
**Note:** a workaround to switch the git version on mac is going to `~/.config/GitHubUnity/settings.json` and updating the git install path.

**Comment by parkgs** [comment]
I have a mac and would like to try looking into this issue - do you have any recommendations on where to start looking within the source code? I have already been able to build/reproduce the issue

**Comment by meaghanlewis** [comment]
Closing this out as it was a dupe of #656 and fixed in #659
