### ISSUE TITLE
The command `git lfs install` should be run on update of LFS

### ISSUE THREAD

**Issue by StanleyGoldman** [github-for-unity/Unity#443]
1. Based on a conversation with @technoweenie we need to run `git lfs install` anytime we update LFS.
2. We are currently only running `git lfs install` when the user initializes a new project. If the person is attempting to clone a project as their first usage of GitHub for Unity we will never have run that command
   1. Although if the person was trying to clone a repo for the first time with GitHub for Unity there is a slight chicken before the egg problem there... How could they clone an LFS enabled repo with LFS not correctly enabled.

**Comment by technoweenie** [comment]
For a bit of additional context, `git lfs install` configures the `filter.lfs.[smudge | clean | process]` git config keys, which rarely change. However, this functionality was added a year ago in LFS v1.5.0 and Git v2.11, so I don't think any GH Unity user will be affected.

**Comment by StanleyGoldman** [comment]
I just noticed the part about `git lfs update` is it okay to run `git lfs install` instead?

**Comment by technoweenie** [comment]
Yup. They used to be different, but are basically the same thing at this point (and should probably be merged so `update` can be deprecated later).

**Comment by shana** [comment]
We're now running `lfs install` on every first run of Unity. Ideally we should do all `firstRun` initialization steps every time git or lfs is updated.
