### ISSUE TITLE
Make it easier to ignore the plugin in existing repos

### ISSUE THREAD

**Issue by nickmccurdy** [github-for-unity/Unity#456]
### Description

I wasn't sure what to put in my `.gitignore` at first to avoid committing plugin files, since the readme only vaguely mentions that it should be done. I then experimented with initializing a new git repository with the plugin and noticed that it creates a [`.gitignore`](https://github.com/github-for-unity/Unity/blob/master/src/GitHub.Api/Resources/.gitignore) with `/Assets/Plugins/GitHub.meta` and `/Assets/Plugins/GitHub/`.

As a workaround, I'm creating a new Unity project and copying the generated files to my existing project. It would be great to either document this in the readme or provide a way to rerun the portion of the initializer that creates files on existing repositories (it could be limited to the `.gitignore` but some of the other generated files like `.gitattributes` seem to be useful).

### Additional Information

- Unity 2017.2
- GitHub for Unity 0.22-alpha
- Glory to Arstotzka!

**Comment by StanleyGoldman** [comment]
@nickmccurdy. We meet again.

We are planning on a project checkup feature that will help you get best practices into your project.

In the mean times if you need the files again check here... https://github.com/github-for-unity/Unity/tree/master/src/GitHub.Api/Resources

Glory to Arstotzka!

**Comment by FurkanKambay** [comment]
@StanleyGoldman @shana 
I see that you removed the lines that ignore the plugin from the `.gitignore` in [#643 / 9b32fc8].
I was wondering if it's possible to avoid having to create any files at all. We can turn this plugin into a Unity package right? (Like [InputSystem](/Unity-Technologies/InputSystem)) That would be way better IMO.

Glory to Arstotzka!

[#643 / 9b32fc8]: https://github.com/github-for-unity/Unity/pull/643/commits/9b32fc8dd51ab183a92054685deb4e117e18faf7

**Comment by shana** [comment]
#1070 has the needed changes to turn the plugin into a package!
