### ISSUE TITLE
null GUIContent resulting in warning spam

### ISSUE THREAD

**Issue by AngryAnt** [github-for-unity/Unity#472]
[github-unity.log](https://github.com/github-for-unity/Unity/files/1510114/github-unity.log)

### Description

Any interaction with the GitHub for Unity window spams the log with warnings, rendering the log useless.

### Steps to Reproduce

1. Added plugin to project
2. Launched window via Window menu
3. Interacted with window GUI

**Expected behavior:** Empty log

**Actual behavior:** Spam of warning:

GUIContent is null. Use GUIContent.none.
UnityEngine.GUILayout:Label(GUIContent, GUIStyle, GUILayoutOption[])
GitHub.Unity.Window:DoHeaderGUI() (at C:/Users/Spade/Projects/GitHub/Unity/src/UnityExtension/Assets/Editor/GitHub.Unity/UI/Window.cs:306)
GitHub.Unity.Window:OnUI() (at C:/Users/Spade/Projects/GitHub/Unity/src/UnityExtension/Assets/Editor/GitHub.Unity/UI/Window.cs:158)
GitHub.Unity.BaseWindow:OnGUI() (at C:/Users/Spade/Projects/GitHub/Unity/src/UnityExtension/Assets/Editor/GitHub.Unity/UI/BaseWindow.cs:87)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

**Reproduces how often:** Once. On first launch after install. After Unity Editor relaunch the header renders as expected and the log is empty.

**Comment by StanleyGoldman** [comment]
Fixed by #500
