### ISSUE TITLE
Bad design practice: Top level menu

### ISSUE THREAD

**Issue by AngryAnt** [github-for-unity/Unity#473]
[github-unity.log](https://github.com/github-for-unity/Unity/files/1510143/github-unity.log)

### Description

GitHub for Unity adds a full top-level menu to the Unity menu bar.

The project hardly defies categorisation sufficiently to warrant exemption from the design practice intended to keep some measure of order in the menus.

### Steps to Reproduce

1. Install the plugin

**Expected behavior:** Plugin functionality following best practices design-wise, granting user access to functionality where expected. Example locations being the preferences window, the Window menu, and the Assets menu.

**Actual behavior:** A top level menu is added.

**Reproduces how often:** 100

**Comment by shana** [comment]
The top level menu is an alpha debug menu, not something that we're going to ship once we hit beta.
