### ISSUE TITLE
Update history view to show the correct commits in each branch

### ISSUE THREAD

**Issue by meaghanlewis** [github-for-unity/Unity#481]
### Description
The history view doesn't show the right commits for each branch.

### Steps to Reproduce

1. Make a change and commit on master
2. Switch to a new branch
3. Make a change and commit to this new branch
4. Go back to master

**Expected behavior:** 
Looking in the history view, the commit on the new branch should not appear in master

**Actual behavior:**
Looking in the history view, the commit on the new branch is carried over to master

**Workaround:**
Shutting down and re-opening Unity seems to fix this.

**Reproduces how often:**
100 %

### Build:
`github-for-unity-0.23.0.3170-a66bd286.unitypackage` from
https://github.com/github-for-unity/Unity/releases/tag/untagged-128514e09193583decb6

**Comment by StanleyGoldman** [comment]
Closed by #482
