### ISSUE TITLE
Authentication fails with 2017.2/2017.3 and .NET 4.6 Mode

### ISSUE THREAD

**Issue by ThomasAunvik** [github-for-unity/Unity#503]
### Description
I have 2FA, but i cannot login to my account. My username and password is definetly correct. Using Unity 2017.2.0f3.

I have yet tried without 2FA.

_Edit: Using .NET 4.6_

### Steps to Reproduce

1. Install Package from v0.22.1-alpha
_1.5. Turn on .NET 4.6_
2. Try to login with the correct username and password. (user must have 2FA)
3. Report this issue.

**Expected behavior:** To Login

**Actual behavior:** Login Failed

**Reproduces how often:** 100%

### Additional Information
https://gist.github.com/ThomasAunvik/27d14fe97fbc9f751dc85f64805a0059

**Comment by StanleyGoldman** [comment]
Hey @ThomasAunvik thanks for trying our stuff.
Strange question, I'm assuming you have other plugins installed...
Are you able to reproduce this in a blank project?

**Comment by StanleyGoldman** [comment]
Also, what OS are you on?

**Comment by ThomasAunvik** [comment]
Alright, this worked on an empty project. Including 2FA. Im on Windows 10 Pro .
My other conclusion it might not work when you have already a git made in the project.

**Comment by StanleyGoldman** [comment]
Hmm.. Did you have other plugins installed?

**Comment by ThomasAunvik** [comment]
Alright, after importing my assets into the empty project (no git), still not working.
The only plugins i have are:
- CNControls
- DiscordRPC
- Github
- Photon Unity Networking
- Photon Chat API
- Websocket (not sure why that is there)

**Comment by StanleyGoldman** [comment]
So it seems we are going to have a conflict with one of them.

Would you mind doing the legwork of taking the process of elimination?
Let me know which one exactly screws us up.

**Comment by ThomasAunvik** [comment]
Well, after i removed the plugins and all assets. (Just copied my project folder to the new one). Still not working.

**Comment by StanleyGoldman** [comment]
Hmm.. Okay, well it sounds like something might already be polluted in the environment that way.
It sounded like a purer test the first way you did.

No worries, I am working on a few things at the moment, but I will check this out soon.

**Comment by ThomasAunvik** [comment]
Alright, it seems to be something withing the ProjectSettings\ folder in my project which screwed it up. Looking through the differences.

**Comment by StanleyGoldman** [comment]
Cool. Let me know what you can find.
I need the help... 😅

**Comment by ThomasAunvik** [comment]
AHA, found it. It was beacuse i was on: .NET 4.6 Experimental.

On .NET 4.6 Experimental Login:
https://gist.github.com/ThomasAunvik/2831b7d009015938a801ca05d06e0d13
On .Net 3.5 Stable Login:
https://gist.github.com/ThomasAunvik/cc609a422b0799dfce20db60d7ec2306

**Comment by StanleyGoldman** [comment]
Ooo... now you are onto something.
Thanks @ThomasAunvik

**Comment by meaghanlewis** [comment]
I was able to reproduce this authentication issue with 2017.2.0f3. Authentication is successful with  2017.1.0f3

**Comment by ledvinam** [comment]
Hi. In 2017.3p1 the same issue. Will this be resolved anytime soon?

**Comment by ThomasAunvik** [comment]
Already assigned as high priority here: https://github.com/github-for-unity/Unity/projects/1

**Comment by StanleyGoldman** [comment]
Hey guys, sorry I've been quiet on this.

The best person to fix this bug is on vacation and I was hoping I could sneak away from this one and wait for them to come back, but I will definitely look at it tomorrow and see if it is something I can fix.

If not they will be back next week and should be able to fix it shortly after.

**Comment by shana** [comment]
Hey y'all! I'm back from 🌴 and will look into this asap! 👀

**Comment by StanleyGoldman** [comment]
Like I said, she would fix it quicker than I could.
This should be released in `0.26.1` soon.

**Comment by StanleyGoldman** [comment]
@ThomasAunvik @ledvinam 
Actually we may need some help testing this one.
Come and find me on gittter or discord and I will send you a build to test.

**Comment by ThomasAunvik** [comment]
Discord Username?

**Comment by StanleyGoldman** [comment]
https://gitter.im/github-for-unity/Unity?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge

https://discord.gg/5zH8hVx
