### ISSUE TITLE
Unity dies on relaunching.

### ISSUE THREAD

**Issue by ThomasAunvik** [github-for-unity/Unity#504]
### Description

After installing Unity and trying to login (#503), and then shut down unity and then launch unity project, unity freezes, no response. Did remove github before, and then it worked again. Reinstalled it, and it broke again.

No response at all.
![image](https://user-images.githubusercontent.com/9968151/33582222-7922f1b0-d954-11e7-8840-2f114b51b929.png)

### Steps to Reproduce

1. Install: v0.22.1-alpha
1.5: Optional: Try to login (#503)
2. Close Unity
3. Open Unity
4. Wait 2-10 seconds.

**Expected behavior:** Not to freeze

**Actual behavior:** Freeze

**Reproduces how often:** 100%

### Additional Information
https://gist.github.com/ThomasAunvik/3378baf73e677830ef682c8ebc357e01

**Comment by StanleyGoldman** [comment]
Hey @ThomasAunvik based on what we know so far, the issue seems to be primarily covered in #503.
So I'm going to close this out for now. After we resolve #503 and this is still a problem, we can open this back up.
