### ISSUE TITLE
Go to Profile option throws NullReferenceException

### ISSUE THREAD

**Issue by meaghanlewis** [github-for-unity/Unity#535]
### Description
Right after initializing a repository, I choose the option `Go to Profile` and the browser opens up to my GitHub profile. Any time after that when I choose that option, my GitHub profile does not open and a **NullReferenceException** is thrown and can be viewed in the Unity console.

### Steps to Reproduce

1. Initialize new repo
2. Select `Go to Profile`
3. Do some other stuff
4. Select the option again

**Expected behavior:** 
The GitHub profile opens up in a new browser tab.

**Actual behavior:**
The GitHub profile does not open.

**Reproduces how often:** 
100

### Error thrown in the Unity console
`NullReferenceException: Object reference not set to an instance of an object
GitHub.Unity.Window.GoToProfile (System.Object obj) (at C:/Users/Spade/Projects/GitHub/Unity/src/UnityExtension/Assets/Editor/GitHub.Unity/UI/Window.cs:398)
UnityEditor.GenericMenu.CatchMenu (System.Object userData, System.String[] options, Int32 selected) (at /Users/builduser/buildslave/unity/build/artifacts/generated/common/editor/GenericMenuBindings.gen.cs:125)`

**Comment by StanleyGoldman** [comment]
```
NullReferenceException: Object reference not set to an instance of an object
GitHub.Unity.Window.GoToProfile (System.Object obj) (at C:/Users/Spade/Projects/GitHub/Unity/src/UnityExtension/Assets/Editor/GitHub.Unity/UI/Window.cs:484)
UnityEditor.GenericMenu.CatchMenu (System.Object userData, System.String[] options, Int32 selected) (at C:/buildslave/unity/build/artifacts/generated/common/editor/GenericMenuBindings.gen.cs:125)
```
