### ISSUE TITLE
If a pull is required before a push, push is silently failing

### ISSUE THREAD

**Issue by StanleyGoldman** [github-for-unity/Unity#54]
Initially reported here: https://github.com/github-beta/unity-preview/issues/21

Push isn't reporting if a pull is required before the push, and silently exits with no information.

**Comment by StanleyGoldman** [comment]
After some testing, I was unable to reproduce this bug.
The error is caught, and a popup occurs.

**Comment by thorade** [comment]
I also tried to reproduce this right now, and yes, there is a popup, but the message is not very informative, it just says "Could not push branch". A better message would tell the user to first pull, then push. 

GitExtensions detects that case, too, and has a message: "You need to pull first, then push, do you want to pull now? (With radio button to select merge, rebase, just fetch)" and below two buttons Yes, No. 

Another idea could be to frequently fetch in the background and put a little number behind the Pull button (as is done currently for the Push button).
