### ISSUE TITLE
Meta files are not nested

### ISSUE THREAD

**Issue by StanleyGoldman** [github-for-unity/Unity#542]
After release `0.26` meta files are no longer being nested in the view.

**Comment by StanleyGoldman** [comment]
It's trivial to implement, but I'm not sure this is a bug that should be fixed.
Folders can also have `.meta` files. It makes sense why we would not want to implement this for folders.

If a user has a folder structure  ...`Plugins/Plugins`
The following paths exist:
`Plugins/`
`Plugins.meta`
`Plugins/Plugins/`
`Plugins/Plugins.meta`

Attempting to change that path display in anyway would be odd.

Implementing this for files and not folders would result in an ambiguous visual metaphor of "this is in a folder".

![](https://i.imgur.com/fZ7uhAa.png)

![](https://i.imgur.com/8vXuEXw.png)

**Comment by StanleyGoldman** [comment]
https://github.com/github-for-unity/Unity/pull/541/commits/56bc1047770ce5bc03a98a4c77c0c7178ec0e93b

**Comment by sguthals** [comment]
I agree with this. It's something that is easily changeable if for some reason there is an outcry from users, but I think it makes more logical sense to have them at the same level.

**Comment by StanleyGoldman** [comment]
@shana she pointed me to several conversations from over a year ago, where this was heavily considered. 

The changes view is not intended to be a literal view of the file system but a logical view of the changes that a user has accumulated.

Regardless of whether or not the meta file nesting is confusing, we decided that it was a mistake not to merge this pull request in earlier as it is a change from the original intentionally designed functionality.

**Comment by shana** [comment]
I'm reopening the design discussion around the changes view in #576.
