### ISSUE TITLE
Linux Editor support

### ISSUE THREAD

**Issue by michael-nischt** [github-for-unity/Unity#555]
It would be great if the plugin would also work with the (experimental) [Unity3D Linux Editor](https://forum.unity.com/forums/linux-editor.93/).

**Comment by StanleyGoldman** [comment]
Hey @michael-nischt 

The linux client is something we are aware of.
But we have a lot of work to do first.

**Comment by michael-nischt** [comment]
Thanks for the reply. Of course I understand that it doesn't have the highest priority but glad to hear it's on the road-map for the future!

**Comment by xaviergmail** [comment]
What is the current state of Linux support? I can't seem to get it to get past the spinning logo. I've tried with a new project and one that is already tracked by Git

**Comment by upkl** [comment]
Login via browser and login with user/password : 
`<LoginManager>                      Login Exception`
`GitHub.Unity.ProcessException: Error code -42`
`Cannot start process because a file name has not been provided.`
