### ISSUE TITLE
Organization repositories not visible to the plugin

### ISSUE THREAD

**Issue by Funkeys** [github-for-unity/Unity#556]
### Prerequisites

- Be sure to run with tracing enabled to capture runtime details in the log file
- Include the log file in the PR.
  - On Windows, the extension log file is at `%LOCALAPPDATA%\GitHubUnity\github-unity.log`
  - On macOS, the extension log file is at `~/Library/Application Support/GitHubUnity/github-unity.log`

### Description

There is a setting for organizations under:
* Organisation/Settings/Third-party access/Third-party access policy

This setting is default set to restricted, when you create a new organization! This makes the repositories created under this organization invisible for the github-for-unity plugin.
Inside Unity, the plugin just gives a message box "Cannot update branch", when you try to push the automatic created first commit.
When you try to publish directly form the history tab, just the user and no organization is shown in the drop down of the publish window.

In the log file i found an exception form the github API the the repo cannot be found!
Sorry, I did delete all the logs while playing around to find what´s wrong.

### Steps to Reproduce

1. set Organisation/Settings/Third-party access/Third-party access policy = restricted
2. try to push to an organization repo

**Comment by meaghanlewis** [comment]
👋  @Funkeys, thanks for writing in. What you are experiencing is expected behavior. The GitHub for Unity plugin is a third-party application since it is not actually owned by the GitHub organization. Please remove restrictions for organizations you want to access using the GitHub for Unity plugin.

**Comment by Funkeys** [comment]
Hi @meaghanlewis, thank you for your description, but I was looking for about a day for a solution. Even had a chat with @StanleyGoldman, and we could not found out what it is in the first place, because of somehow misleading error.
As I found it out then, @StanleyGoldman asked me to wirte it down, so he remembers the setting to add it to the wiki.

**Comment by meaghanlewis** [comment]
@Funkeys I do agree the error could be misleading and not give you a great idea of what the problem is. Apologies that you were searching for a solution for a while. We also had to investigate this to determine that GitHub for Unity is in fact a third-party application.

**Comment by StanleyGoldman** [comment]
Don't worry @Funkeys... I'm gonna add it to the markdown in a bit.
