### ISSUE TITLE
Is there a way to access number of modified files from another script

### ISSUE THREAD

**Issue by Reddevildragg** [github-for-unity/Unity#564]
Is there a way to access the number of modified (files that need to be committed to git) from outside of github-for-unity. Looking to create an editor script to open github for unity and prompt (but not force) a team after every X number of modified files to consider committing if it is relevant. had a sift through the released version and guessing this is kinda what i need but its internal so cant access it externally.
```

this.gitStatusEntries = this.Repository.CurrentChanges.Where<GitStatusEntry>((Func<GitStatusEntry, bool>) (x => x.Status != GitFileStatus.Ignored)).ToList<GitStatusEntry>();
this.gitStatusEntries.Count; 
```

**Comment by StanleyGoldman** [comment]
Hi @Reddevildragg 

I can't say it's a good idea to use us as an API. We aren't looking to create an API that we have to support. Initially we tried to keep all of our APIs internal but changes in Unity forced us to make some classes public.

All that said... I understand your desires to keep control of your team. So I don't mind telling you what you would need to do.

1. So you will need to maintain your own fork to make public the things you need public.
2. Read the code for the [ChangesView](https://github.com/github-for-unity/Unity/blob/2220d771d75f548c2c9a50afbad4374af3bbba5b/src/UnityExtension/Assets/Editor/GitHub.Unity/UI/ChangesView.cs). It will show you how we listen to updates and get data from `Repository`.

I'd be interested in seeing what you come up with. Let me know if you need a hand.
