### ISSUE TITLE
Show errors and success messages in Console window

### ISSUE THREAD

**Issue by chall3ng3r** [github-for-unity/Unity#567]
### Description

Showing very little info for errors to users in a modal window doesn't help much. Then user have to dig into folders to look in logs. 

![image](https://user-images.githubusercontent.com/529419/34916152-08d543b0-f955-11e7-8106-046d3984ed1c.png)

It'd be great if error and success messages are sent to Unity's Console window. If not the whole stack trace, just the exception message would really help.

### Steps to Reproduce

1. Click Push in History tab

**Expected behavior:** 
Changes pushed to remote branch, and success message in Console window. Or if there's password error or anything, show an exception message in Console window.

**Actual behavior:**
Modal window shows, branch pushed successfully or a window shows "Could not push branch".

**Reproduces how often:**
Every time.

### Additional Information

Windows 10 Pro 64bit (16299.192), Unity 2017.3.0f3.

**Comment by StanleyGoldman** [comment]
Hey @chall3ng3r Thanks for testing our stuff out.

And you make a fair point, that popup message isn't very useful.
We are looking to get more information out of the commands that get run to you.
I'll definitely look at doing something better than this popup.
