### ISSUE TITLE
Can't sign in to GitHub in Unity 2017.2.0f3 using .NET 4.6

### ISSUE THREAD

**Issue by meaghanlewis** [github-for-unity/Unity#570]
### Description
There is an issue on Mac using Unity 2017.2.0f3 in .NET 4.6 mode where users cannot sign in to GitHub.

![screen shot 2018-01-17 at 8 58 26 am](https://user-images.githubusercontent.com/10103121/35055690-9ff01f3e-fb64-11e7-93e6-bebfe453f666.png)

Exception can be found [here](https://gist.github.com/meaghanlewis/7929120f385178a599609188a811cfa4)

### Additional Information
This issue was resolved in Patch 2017.2.0p2. There does not seem to be anything we can do to resolve this in Unity 2017.2.0f3, so if you experience this issue, please upgrade your version of Unity to the latest final build.

**Comment by StanleyGoldman** [comment]
This actually should be fixed by the beta.

**Comment by meaghanlewis** [comment]
yes, this is fixe @StanleyGoldman 🎉

**Comment by StanleyGoldman** [comment]
Thanks @meaghanlewis
