### ISSUE TITLE
Branch list not updating after creating branch in github.com

### ISSUE THREAD

**Issue by ThomasAunvik** [github-for-unity/Unity#571]
### Description

The branch i created in github.com does not show in the branch list, it also shows deleted branches.

After trying to use the deleted branch, it gives an error: "Could not to switch to branch UI-Anims--Card viewing", i think that has to do with how the git handles & and other things. since the URL end in github is: UI-Anims-%26-Card-viewing. Using the & does not work with git. (#515)

### Steps to Reproduce

1. Create a new branch via github.com
2. Open Unity with the plugin
3. Check branches

Fix: Open git console and type `git checkout <branch>` (this probably only shows the one you checkout to)

Another note: The branch list shows also old/deleted branches.

**Expected behavior:** Update its branch list.

**Actual behavior:** Nothing happens

**Reproduces how often:** Always?

### Additional Information
Log File: https://gist.github.com/ThomasAunvik/0569718a6a8353935628f5f1897ab55d
Unity Version: 2018.1.0b3

![image](https://user-images.githubusercontent.com/9968151/35265491-89f618a8-0020-11e8-9965-60cfc3acbfb2.png)
![image](https://user-images.githubusercontent.com/9968151/35265509-94d9f12c-0020-11e8-8973-d424e0610968.png)
![image](https://user-images.githubusercontent.com/9968151/35265620-ee164786-0020-11e8-9f3b-e87183c77581.png)

**Comment by meaghanlewis** [comment]
Hi @ThomasAunvik thanks for your detailed bug report.

In regards to the branch you created on github.com, you should go to the History tab and then select `Fetch`. When you go back to Branches, you should see the branch from github.com under remote branches. I just tried this out in `2018.1.0b4` and it was all good, so let me know if that works for you.

We are aware that Unity continues to show deleted branches, as you saw mentioned in issue #515, but have not prioritized this enhancement to be worked on anytime soon.

**Comment by ThomasAunvik** [comment]
It seems to work for a completely new project, but for my project that wont work for some reason.

**Comment by StanleyGoldman** [comment]
Fixed after some debugging. The problems seem to stem from being unable to correctly unset the git executable path once chosen.
