### ISSUE TITLE
git fetch should also fetch tags

### ISSUE THREAD

**Issue by shana** [github-for-unity/Unity#572]
`git fetch` doesn't fetch tags that aren't directly reachable by current branch heads. Long-lived release or maintenance branches are not normally merged back to master and tags created on them won't be fetched normally. We should do ~`git fetch --all`~`git fetch --tags` to ensure all tags are fetched.

EDIT: we want the --tags flag, not the --all flag

**Comment by parkgs** [comment]
Has anyone addressed this issue yet?

**Comment by StanleyGoldman** [comment]
Not yet @parkgs but I'll see what I can do about it...

**Comment by parkgs** [comment]
@StanleyGoldman I can try working on this! Do you have any general idea of what area of the source code to look at?
