### ISSUE TITLE
Changes view: design discussion

### ISSUE THREAD

**Issue by shana** [github-for-unity/Unity#576]
Should the Changes view show a view of the filesystem, or should it show a logical or more abstracted view of the assets that have been changed? Or both? Or something else?

The original discussion happened haphazardly in https://github.com/github/UnityInternal/issues/7 and in calls we did at the time, some of the context is there (as well as the old mockups), I'll bring that info here as I sort through it.

There are pros and cons to both approaches, and right now we're kinda doing a mix of both by showing a view of the filesystem but nesting meta files under the files they belong to. This kinda breaks with folders, where the meta file lives outside the folder in the filesystem, and that gave rise to the questions in https://github.com/github-for-unity/Unity/issues/542. Let's debate this here and see what we can come up with.

**Comment by donokuda** [comment]
I'd love to get more insights from game developers and other users of Unity that have to manage assets. There's another consideration around whether we're able to group related files together.

For example, are we able to find out what textures and models are used in a scene? Can we find out which models utilize a specific texture?

**Comment by shana** [comment]
@donokuda Yeah, we can totally get all that information from the scene. Not sure about objects that aren't on a scene at design time, but probably yes to that as well.

@CapnRat What do you think would be a good way of visualizing the changes that need to be commited? A view mimicking the filesystem, or something showing assets changed grouped by scenes (probably with a "not in any scene" group for other things)? Or something else entirely?
