### ISSUE TITLE
Cannot login to GitHub

### ISSUE THREAD

**Issue by Rubinhuang9239** [github-for-unity/Unity#586]
Hey Team,

I cannot login to my Github account on 2017.3.1f1.
I do have enabled Two-Factors Auth and tried both my password and Personal Token with it, but still failed.

Any idea?

```
180222-16:02:46.996  INFO [ 1] <LoginManager>                 Login Username:Rubinhuang9239
180222-16:02:48.662  WARN [ 1] <LoginManager>                 Login Exception
An error occurred while sending the request
at DotNetHttp35.HttpClientHandler+<SendAsync>c__async0.MoveNext () [0x00000] in <filename unknown>:0 
at GitHub.Unity.LogFacade.Warning(System.Exception ex, System.String message) in C:\Users\Spade\Projects\GitHub\Unity\src\GitHub.Logging\LogFacade.cs:line 120
```

**Comment by shana** [comment]
Oooof, we have a bit of a problem. TLS 1.0/1.1 has just been deprecated on the GitHub (https://githubengineering.com/crypto-removal-notice/) servers, and Mono 3.5 doesn't support TLS 1.2, which means it can't do the necessary connection to do the authentication.

We're working on it as fast as possible and I'm hoping to get a release in the next 24 hours to fix this. I'm trying to figure out a decent workaround while we fix the issue, I'll post here as soon as I have one.

**Comment by shana** [comment]
While we fix the underlying problem, a workaround that you can use is to login in Visual Studio with the GitHub Extension for Visual Studio. Once you login there, you'll be able to push/pull/fetch from Unity. The authentication in Unity won't work, but git operations should pick up the login from VS and work correctly.

Let us know if you have problems with this.

**Comment by shana** [comment]
There's a new release 0.26.2 https://github.com/github-for-unity/Unity/releases/tag/v0.26.2-alpha with a patch for this problem. Right now it only fixes authentication on Windows, Mac is still broken. I hope to have Mac support back up and running early next week.

Let us know if it works for you or not!

**Comment by Rubinhuang9239** [comment]
Hey! Any update on this?

**Comment by StanleyGoldman** [comment]
Hey @Rubinhuang9239 thanks for hanging in there.
I'm working everyday to get a new api solution back in GitHub for Unity.
We are making progress, so hopefully soon.

**Comment by IARI** [comment]
I cannot login using the plugin on windows. I also don't see any debug output in unity

**Comment by hu243285237** [comment]
When I sign in to GitHub in Unity editor,it will show a error that "OctoRun stop work",and then show "Login Failed" in Authenticate.

**Comment by StanleyGoldman** [comment]
Hey @hu243285237 thanks for hanging in there.

I'm working on a new fix which completely replaces the patch we rolled out in a hurry.
After we push that out I'm gonna ask you to try it out for us. It should be ready sometime next week.

**Comment by Rubinhuang9239** [comment]
This a super responsive repo Stanley! looking forward to your good news soon. Thanks. @StanleyGoldman

**Comment by SirWindfield** [comment]
Hey! It still doesn't work for Windows though. I created a personal access token since I use 2FA but every time I try to sign-in, I get the `Login failed` error message. Running on Windows 10.

**Comment by StanleyGoldman** [comment]
Hey @SirWindfield I'm sorry about that, but rather than debug your issue, I'm focusing on replacing it entirely. We should be ready next week.

**Comment by SirWindfield** [comment]
No problem! Thanks for the reply!

**Comment by Rubinhuang9239** [comment]
Hey guys. How's going?

**Comment by shana** [comment]
We're racing to get the 1.0rc/master branch stable so we can get a release out with all the fixes. Our plan is to get it out at most by the end of next week (but really I'd rather have it out before GDC starts on Monday), and it'll have all the needed fixes for this stuff included. 🔜!

**Comment by StanleyGoldman** [comment]
So the new GitHub for Unity beta release should resolve this issue. I invite you guys to download the new release and give it a shot.

cc: @Rubinhuang9239  @SirWindfield @hu243285237 @IARI

**Comment by jmgawecki** [comment]
Hi. Was this problem fixed for the mac? Im getting the exact same error on Apple Silicon Unity for Silicon. Thanks!
