### ISSUE TITLE
GitHub api calls on dotcom and the missing TLS support

### ISSUE THREAD

**Issue by shana** [github-for-unity/Unity#597]
## Problem:

Mono in Unity doesn't support TLS 1.2. The experimental 4.6 runtime might support it, but so far in my tests it just fails, so the support might not be all there. Regular mono in Unity is the 3.5 profile which definitely doesn't support it. This means Unity can't talk to github.com at all. git can, but we can't make github api calls.

### Potential solutions:

Build a helper tool that talks to the github api on behalf of Unity. This allows us to use modern languages and full encryption and not rely on what Unity ships with.

The first jab at it is a .NET 4.6 command line tool that takes one-shot commands, executes them and outputs the result on the console. It works for login right now.

This current language choice has the problem that .net does not run natively anywhere except on Windows, and Unity's bleeding edge mono doesn't seem to include the right bits to run this on other platforms. That means we'd have to package our own mono in order for the tool to run properly on non-Windows platforms. Ugh.

Besides the language problem, in terms of how to approach this problem, I'm thinking there's two ways of going about this:

1) one shot command line tool. it takes a command and does a thing and exits. keeps no state between commands
2) a daemon process. listens on a socket/port/whatever, runs commands, does not exit. can keep state between commands

#### pros and cons

1) simple, straightforward. Bound to the command line, so we are limited by whatever command line length is shorter (windows?). Formatting long output is going to be the same pain as invoking  git on the command line. usual encoding issue. caller needs to keep and send all the state if a command needs to be split up (like login and 2fa which requires user input in between to complete)
2) can throw json at it and not worry about sizes of inputs and outputs. slightly less simple to manage, need to think about lifetime of the process, shutting it down if it's zombied, reconnecting to it when we lose the managed domain. can keep state between commands so the caller doesn't have to worry about it.

We can do all json output for the command line tool, which means if we decide that the daemon approach is better we can switch to it without major changes to the caller.

### What language should the tool be built with

Whatever language we choose for the tool should be something that we can easily maintain and something that runs natively or near natively on windows, mac and linux. This is mostly for distribution reasons - we need to ship a thing that has minimal dependencies and can be shipped with the extension with a small footprint and just unzipped somewhere and ran without any need for installers.

Unity ships with nodejs and mono. Additionally, .net apps run natively on Windows, but not on mac or linux. We might not be able to use Unity's bleeding edge mono, as it doesn't to work properly for TLS.
We might be able to leverage Unity's nodejs across all platforms though, which means we wouldn't have to worry about distributing runtimes for the tool to work

**Comment by shiftkey** [comment]
@shana 

> Mono in Unity doesn't support TLS 1.2. The experimental 4.6 runtime might support it, but so far in my tests it just fails, so the support might not be all there.

I think you're stuck until [4.8.0](http://www.mono-project.com/docs/about-mono/releases/4.8.0/#tls-12-support) unless it gets backported.

**Comment by StanleyGoldman** [comment]
After experimenting with the version of nodeJs that is bundled with Unity.
It is nodeJS `v0.12.7` which only supports `ES3`. The octokit library requires `ES2015+`
Which means that we would need our own version of the octokit library.

**Comment by StanleyGoldman** [comment]
I think the next language down the list of options would be Go.

**Comment by StanleyGoldman** [comment]
Some conversations with octokit maintainers has resulted in them creating an `ES3` port for us.

https://github.com/gr2m/octokit-rest-es3

**Comment by StanleyGoldman** [comment]
Closing this issue as it has been resolved by the beta
