### ISSUE TITLE
Command Line not showing

### ISSUE THREAD

**Issue by ThomasAunvik** [github-for-unity/Unity#598]
### Description

When trying to open the command line from Unity via this plugin
![image](https://user-images.githubusercontent.com/9968151/36754390-1939b76e-1c09-11e8-9372-24ba68b8026e.png)

### Steps to Reproduce

1. Open Unity 2017.3.0f3 and create a new project (does not have to be a new project)
2. Install Github for Unity (unless you already have github for unity)
3. Go to Github > Command line
4. Expect something to not work.

**Expected behavior:** To show this for example:
![image](https://user-images.githubusercontent.com/9968151/36754433-3b62f1f2-1c09-11e8-8545-058bf7d0ac0e.png)

I managed to get this via File Explorer and typing `cmd` in the file path.

**Actual behavior:** Nothing shows on the console, unable to type in the console either.
The image above in description.

**Reproduces how often:** 100% prob

### Additional Information
Default configuration with trace logging
Gist log: https://gist.github.com/ThomasAunvik/697d655743168aa6596cc652a233efdd

**Comment by meaghanlewis** [comment]
Hi @ThomasAunvik thanks for reporting this detailed issue. I just tried to repo this issue myself on Windows using the Unity 2017.0f3 with GitHub for Unity version 0.26.2, but was unable to do so. The terminal window opens just fine for me.

You mentioned this is probably reproducible 100% of the time. Have you tried this again and if so, do you continue to the experience same result every time?

**Comment by ThomasAunvik** [comment]
I have tried creating a new project folder and testing it, i will see if i can debug it.

**Comment by ThomasAunvik** [comment]
Alright, so i deleted the GitHubUnity folder in AppData, and it still did not work.

**Comment by StanleyGoldman** [comment]
Hey @ThomasAunvik after I debug some more pressing issues. I can take a look at this with you.

**Comment by StanleyGoldman** [comment]
Hey @ThomasAunvik can you see if you can reproduce this bug with the latest beta version?

**Comment by shana** [comment]
This *should* be fixed with the latest beta - if it isn't, please feel free to reopen!

**Comment by ThomasAunvik** [comment]
Sorry, still not fixed, it works for my laptop though, weird bug.

**Comment by ThomasAunvik** [comment]
1. Temporary Fix: Reimport All assets. (Right click in Project window and press Reimport All)
2. (Sometimes) After rebooting unity (after reimport): Command line closes immidiately after trying to open it.
3. Rebooting again: Command line shows as the original issue.

**Comment by StanleyGoldman** [comment]
I've received confirmation from users that this is still reproducible with the latest versions of GitHub for Unity and Unity.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/417571/46490096-0d4e5900-c7d5-11e8-9558-d71f676e78fa.gif)

**Comment by jwvanderbeck** [comment]
I am experiencing this bug.

**Comment by Cdddo** [comment]
This is still happening on 1.3.0 Unity 2018.3
and 1.3.1 and Unity 2018.4 (on Windows 10)

**Comment by GDelavy** [comment]
Still happening on 2019.1.6f1

**Comment by matthewbegun** [comment]
Still happening using editors ranging from 2017.1 -> 2019.2 on Windows 10 pro using version 1.4 of the plugin.

**Comment by devinallen1** [comment]
This is happening on 2019.2.2f1 also.

**Comment by AlvaroSReis** [comment]
I'm with the same issue.

**Comment by ilirvg** [comment]
Me as well on 20019.2

**Comment by CKew** [comment]
Same issue here.

**Comment by YichenJia** [comment]
Same bug here with 2019.1.7f1

**Comment by psben113** [comment]
Can we get a fix for this already?

**Comment by Daniyal424** [comment]
same, come on guys fix it, 2019.3.11f1

**Comment by manic145** [comment]
Same!!! 2019.4.1f1

**Comment by phantomsom** [comment]
Bump, Unity 2018.4.23f1

**Comment by tobilinz** [comment]
Same on 2020.1!

**Comment by viniciussvl** [comment]
Same on 2021.1!

**Comment by TiltedWatcher** [comment]
Experiencing this issue as well. On 2020.2.3f

**Comment by Diti000** [comment]
Same 2019.4.17f1

**Comment by MCTTAN** [comment]
Same 2019.4.18f1

**Comment by ThomasAunvik** [comment]
Surely this issue isn't going to be fixed magically the newer the unity version is, so most likely this issue is going stale either way.
