### ISSUE TITLE
Authentication problem with specific account (Windows)

### ISSUE THREAD

**Issue by IARI** [github-for-unity/Unity#600]
### Description

The procedure to Sign in to Github fails with a certain account.

### Steps to Reproduce
Note: This can not be reproduced with any github account.

1. Install github for unity (v0.26.2-alpha) with a Unity (2017.3.0f3) project on windows 10.
2. Try to sign in using the plugin.

**Problem:**
The login fails despite having supplied correct authentication data.
Excerpt from the log:

> 180301-14:25:00.901  WARN [ 1] <LoginManager>                      Login Exception
> Authentication failed
> 
> Server stack trace: 
>   at GitHub.Unity.LoginManager+<TryLogin>c__async4.MoveNext () [0x00283] in D:\code\github\Unity\src\GitHub.Api\Authentication\LoginManager.cs:294 
> 
> Exception rethrown at [0]: 
>   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0002b] in <1461b69994364e8cb0dbf43292f1a9bf>:0 
>   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccess (System.Threading.Tasks.Task task) [0x0002f] in <1461b69994364e8cb0dbf43292f1a9bf>:0 
> ...

**Reproduces how often:**
Depends on the github acount.

With acount A: always
With acount B: never

### Additional Information
It may be an encoding issue, or something connected to the usage of special characters in the password.

**Comment by StanleyGoldman** [comment]
Hey @IARI thanks for testing our patch.

After some consideration we are going in a completely different direction than the first fix we pushed out. So we aren't going to pay attention to this one for now. I'm gonna close this out and we can still track this problem at the other issue.
