### ISSUE TITLE
Extremely high RAM on "changes" tab with ~300k changes

### ISSUE THREAD

**Issue by joehot200** [github-for-unity/Unity#602]
### Steps to Reproduce

Click the "changes" tab in the Github window (presumably with thousands of changes like I have).

**Expected behavior:**
The changes tab opens quickly and RAM usage stays the same.

**Actual behavior:**
The changes tab takes over 5 minutes to load, and Unity takes up MORE THAN THREE TIMES the RAM that was in use before clicking the changes tab.

**Reproduces how often:**
100% of the time. Sometimes the editor crashes due to an out of memory exception.

### Additional Information
![image](https://user-images.githubusercontent.com/6872507/36921958-18390836-1e5e-11e8-9f30-ef9eea159216.png)
The memory usage in the above picture after the "changes" tab has been pressed. Note that while this picture was taken, the Unity editor was (and still isn't, with about the same amount of RAM in use) not responding.
The memory usage before clicking on the "changes" tab read as about 1200MB.

The log file says nothing I believe is of importance but since you'll probably ask for it anyway here it is.
`180302-20:53:51.382 TRACE [ 1] <Repository>                        GitTrackingStatusCache Updated 2018-03-02T20:53:51.3465374+00:00
180302-20:53:51.800 TRACE [ 8] <RepositoryWatcher>                 Handling 15 Events
180302-20:53:51.869 TRACE [ 8] <RepositoryWatcher>                 Processed 0 Events
180302-20:53:52.984 TRACE [ 1] <GitTrackingStatusCache>            Updating: 3/2/2018 8:53:52 PM +00:00 behind:0
180302-20:53:53.016 TRACE [ 1] <GitTrackingStatusCache>            Verified: 3/2/2018 8:53:52 PM +00:00
180302-20:53:53.888 TRACE [ 8] <RepositoryWatcher>                 Handling 9 Events
180302-20:53:53.901 TRACE [ 8] <RepositoryWatcher>                 Processed 0 Events
180302-21:03:46.761 TRACE [ 1] <HistoryView>                       OnDisable
180302-21:03:46.768 TRACE [ 1] <ChangesView>                       OnEnable
180302-21:03:46.774 TRACE [ 1] <Repository>                        Check RepositoryInfoCache CacheUpdateEvent Current:3/2/2018 4:37:09 PM +00:00 Check:3/2/2018 4:37:09 PM +00:00 Result:False
180302-21:03:46.778 TRACE [ 1] <Repository>                        Check GitStatusEntriesCache CacheUpdateEvent Current:3/2/2018 8:53:25 PM +00:00 Check:3/2/2018 4:01:06 PM +00:00 Result:True
180302-21:03:46.782 TRACE [ 1] <Repository>                        GitStatusEntriesCache Updated 2018-03-02T20:53:25.3081555+00:00
180302-21:03:46.787 TRACE [ 1] <Repository>                        Check GitLocksCache CacheUpdateEvent Current:1/1/0001 12:00:00 AM +00:00 Check:1/1/0001 12:00:00 AM +00:00 Result:False
180302-21:03:46.793 TRACE [ 1] <GitLocksCache>                     Not Initialized
180302-21:03:46.797 TRACE [ 1] <GitLocksCache>                     Invalidate
180302-21:03:46.801 TRACE [ 1] <CacheContainer>                    OnCacheInvalidated cacheType:GitLocksCache
180302-21:03:46.805 TRACE [ 1] <RepositoryInfoCache>               Not Initialized
180302-21:03:46.811 TRACE [ 1] <GitClient>                         ListLocks
180302-21:03:46.900 TRACE [ 1] <GitStatusEntriesCache>             Timeout Invalidation
180302-21:03:46.904 TRACE [ 1] <GitStatusEntriesCache>             Invalidate
180302-21:03:46.908 TRACE [ 1] <CacheContainer>                    OnCacheInvalidated cacheType:GitStatusEntriesCache
180302-21:03:46.912 TRACE [ 1] <GitClient>                         Status
180302-21:03:55.397 TRACE [24] <RepositoryManager>                 Starting Operation - Setting Busy Flag
180302-21:03:55.403 TRACE [24] <RepositoryManager>                 IsBusyChanged Value:True
180302-21:03:56.223 TRACE [ 8] <RepositoryWatcher>                 Handling 1 Events
180302-21:03:56.229 TRACE [ 8] <RepositoryWatcher>                 Processed 0 Events
180302-21:03:57.236 TRACE [ 8] <RepositoryWatcher>                 Handling 1 Events
180302-21:03:57.243 TRACE [ 8] <RepositoryWatcher>                 Processed 0 Events
180302-21:04:51.839 TRACE [ 8] <RepositoryWatcher>                 Handling 1 Events
180302-21:04:51.845 TRACE [ 8] <RepositoryWatcher>                 Processed 0 Events
180302-21:04:52.046 TRACE [26] <RepositoryManager>                 Ended Operation - Clearing Busy Flag
180302-21:04:52.053 TRACE [26] <RepositoryManager>                 IsBusyChanged Value:False
180302-21:04:52.850 TRACE [ 8] <RepositoryWatcher>                 Handling 1 Events
180302-21:04:52.854 TRACE [ 8] <RepositoryWatcher>                 Processed 0 Events`

I suspect this may not become such a large issue if I don't have so many changes (or more RAM) to commit, but as I am on my slow college laptop I have not had time to test that at the moment.

After a long (approximately 10 minutes) time, the RAM usage appears to drop (to about 1700MB) and the changes tab opens. Of course, this doesn't happen when the editor crashes due to an out of memory exception, but if the editor does not crash, the tab will eventually open.

Edit: Approximately 12 minutes after clicking the "changes" tab, RAM is back down to 1157MB (which is what it was before I clicked the "changes" tab), and the changes tab is now responding - However, the response time on the "changes" tab is slow, and each character typed in the changelog takes about 5 seconds to appear.

Edit: Apparently, 330821(!) changed files. A lot of them are .bin level data files.

**Comment by StanleyGoldman** [comment]
Oh boy! Hey @joehot200 thanks for stress testing!
Geez, I only tested 10k ish files. I'm happy to know that it even works with that many.
So okay, you might've found our next limit to break.

**Comment by StanleyGoldman** [comment]
I'm gonna edit the title to be a little bit more reflective of your scenario

**Comment by StanleyGoldman** [comment]
I only now saw your messages in gitter. The notifications in the gitter desktop client don't always get my attention.
 
You did the right thing, whenever you don't get me on a chat system that day, just open an issue.

**Comment by joehot200** [comment]
Just to clarify, it is 300k files, not 30k.

**Comment by StanleyGoldman** [comment]
Hot damn.
