### ISSUE TITLE
No build instructions for osx. 

### ISSUE THREAD

**Issue by SoylentGraham** [github-for-unity/Unity#62]
What tool are we supposed to be using for OSX builds?

`build.sh` references OSX as well as windows, then invokes `xbuild`, which is... a mono based wrapper for visual studio? visual code? on windows, but not osx?

**Comment by shana** [comment]
You can use `build.sh` on OSX and Windows, you just need Mono 4.8 on your path.

**Comment by StanleyGoldman** [comment]
Hey @SoylentGraham you can find more information here [How to Build](https://github.com/github-for-unity/Unity/blob/master/docs/contributing/how-to-build.md)

**Comment by SoylentGraham** [comment]
Aha, thanks! I spent ages looking for a page like that and obviously glossed over that one :)

**Comment by StanleyGoldman** [comment]
You aren't completely wrong, there is an environment setup page that needs to go away.
