### ISSUE TITLE
Quotation Marks (") in CommitBody fails to commit, loses commitMessage, and locks out commits

### ISSUE THREAD

**Issue by Hassurunous** [github-for-unity/Unity#625]
### Prerequisites

- Be sure to run with tracing enabled to capture runtime details in the log file
- Include the log file in the PR.
  - On Windows, the extension log file is at `%LOCALAPPDATA%\GitHubUnity\github-unity.log`
  - On macOS, the extension log file is at `~/Library/Application Support/GitHubUnity/github-unity.log`

### Description

If you include a quotation mark in your "Commit summary" (commitBody in the codebase) it fails to log the commit, and erases the commitBody and commitMessage.

### Steps to Reproduce

1. Make changes that can be seen in the "Changes" tab.
2. Select changes to commit.
3. Write a "Commit Summary" that includes a quotation mark ("). 

**Expected behavior:** Logs the commit, possibly inserting escape characters as necessary or replacing quotation marks if necessary.

**Actual behavior:** Lose the commit. Changes are preserved, but the message and body are lost. 

**Reproduces how often:** 100% reproduce rate.

### Additional Information

Gonna take a crack at fixing this today once I finish what I'm working on. Should be easy enough. 

Thanks!

**Comment by sguthals** [comment]
Hi @Hassurunous 

Thanks for reporting this and taking a stab at fixing it! Let us know if you run into trouble and how it goes!

**Comment by StanleyGoldman** [comment]
Hey @Hassurunous 

Be sure to read the [How to Build](https://github.com/github-for-unity/Unity/blob/master/docs/contributing/how-to-build.md) document before you start fighting...

**Comment by StanleyGoldman** [comment]
This is no longer a bug in the current beta.
But we still want to put something in place to prevent similar errors

**Comment by StanleyGoldman** [comment]
I stand corrected, this is still a bug
