### ISSUE TITLE
The plugin fails to initialize LFS

### ISSUE THREAD

**Issue by valyard** [github-for-unity/Unity#650]
The plugin silently fails when trying to create a new repo or change settings.
Log contains this error: `Exception on concurrent thread: 1 lfs version
GitHub.Unity.ProcessException: git: 'lfs' is not a git command. See 'git --help'.`

I am starting Unity 2017.3.1 with an empty project and pressing "initialize repo" in the plugin window. Nothing seems to happen, though the .git folder in the project is created.

First of all, it would be nice to have some kind of error reported to the UI when a failure happens.

I'm not sure about my local git and lfs install, but it works from command line and other tools.
```
valentin-mac:git-test valyard$ which git
/usr/local/bin/git
valentin-mac:git-test valyard$ git lfs version
git-lfs/2.3.3 (GitHub; darwin amd64; go 1.9.1)
```

Where is the plugin running `git` from?

[github-unity.log](https://github.com/github-for-unity/Unity/files/1849930/github-unity.log)

**Comment by StanleyGoldman** [comment]
Hey @valyard 
Thanks for testing out our stuff..
I'm still reading your log file, but it seems to be using git found at `/usr/bin/git`.

**Comment by StanleyGoldman** [comment]
Hey @valyard 
Do you have a file at `~/.config/GitHubUnity/settings.json`?
What is in it?

**Comment by valyard** [comment]
`~/.config/GitHubUnity/` is empty.
`/usr/bin/git` might be a link to `/usr/local/bin/git` since `/usr/bin/git lfs version` also returns `git-lfs/2.3.3 (GitHub; darwin amd64; go 1.9.1)`.

**Comment by StanleyGoldman** [comment]
Hey @valyard so we are still debugging, this bug is reproduced on a few of our machines here. So it should not take us long to resolve.

**Comment by StanleyGoldman** [comment]
**TLDR**: I've isolated the problem to how we computer the `PATH` environment variable in `ProcessEnvironment`

I'm able to reproduce this on my mac. I have some updated information.
I was interested in capturing what the `PATH` was being set to. I added some logging to...

https://github.com/github-for-unity/Unity/blob/0c3b816f3fdeaeae8648a79707e34e9e0f8c041b/src/GitHub.Api/Platform/ProcessEnvironment.cs#L60-L73

I got this...
```
/usr/bin:/usr::/usr:/usr/bin:/bin:/usr/sbin:/sbin:
```

Meanwhile on my normal shell.. _(Minus some Ruby/homebrew stuff...)_
```
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:
```

In code I forcibly set that value in place and I was able to initialize the repo.

**Comment by neilsarkar** [comment]
yeah I am also having this problem and I think in my case it may have been due to the order that I installed things. Leaving this here in case it helps with repo steps

1. Double click `.unitypackage` to install
1. Use the UI to `Initialize git repository`, silent failure
1. `brew install git-lfs`
1. `brew install git`

the path explanation makes sense, since `git-lfs` is in `/usr/local/bin`. output from my system:

```bash
$ /usr/bin/git lfs version
git-lfs/2.4.0 (GitHub; darwin amd64; go 1.10)

$ /usr/local/bin/git lfs version
git-lfs/2.4.0 (GitHub; darwin amd64; go 1.10)

$ PATH=/usr/bin:/usr::/usr:/usr/bin:/bin:/usr/sbin:/sbin: /usr/bin/git lfs version
git: 'lfs' is not a git command. See 'git --help'.

The most similar command is
	log

$ PATH=/usr/bin:/usr::/usr:/usr/bin:/bin:/usr/sbin:/sbin: /usr/local/bin/git lfs version
git: 'lfs' is not a git command. See 'git --help'.

The most similar command is
	log
```

**Comment by StanleyGoldman** [comment]
Thanks for sounding in @neilsarkar. I'm working on this bug directly today.

**Comment by StanleyGoldman** [comment]
I opened #659 so I can ramble to myself while I fix this...

**Comment by StanleyGoldman** [comment]
Okay, I think i figured out all the "issues" with what's up.

**Comment by StanleyGoldman** [comment]
Release coming soon..

**Comment by neilsarkar** [comment]
yayayay thank you for this release @StanleyGoldman everything worked perfectly on my new project!

**Comment by StanleyGoldman** [comment]
Nice! Happy to hear it!
