### ISSUE TITLE
Extension Tab went blank when click initialize a repository - MissingMethodException Method not found.

### ISSUE THREAD

**Issue by SolarJuice** [github-for-unity/Unity#675]
As title described, anyone who have the same problem? The debugging log on Unity shows below:

##############################
> MissingMethodException: Method not found: 'UnityEngine.Rect.get_zero'.
> GitHub.Unity.Window.OnUI () (at C:/Users/Spade/Projects/GitHub/Unity/src/UnityExtension/Assets/Editor/GitHub.Unity/UI/Window.cs:205)
> GitHub.Unity.BaseWindow.OnGUI () (at C:/Users/Spade/Projects/GitHub/Unity/src/UnityExtension/Assets/Editor/GitHub.Unity/UI/BaseWindow.cs:90)
> System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:222)
##############################

![capture](https://user-images.githubusercontent.com/24984500/38387123-c29f207e-390e-11e8-9bdd-35b0e96dc718.PNG)

**Comment by StanleyGoldman** [comment]
Hmm... okay we should be able to reproduce this. We were just wrapping up a release, so hopefully we can get this in.

**Comment by SolarJuice** [comment]
okay, sure~

**Comment by StanleyGoldman** [comment]
@SolarJuice try out the new build and let us know if it works out for ya

**Comment by SolarJuice** [comment]
I will have a try tomorrow on an university computer.
