### ISSUE TITLE
Views freeze when re-opening project

### ISSUE THREAD

**Issue by ThomasAunvik** [github-for-unity/Unity#679]
### Description

The Changes tab ceases to respond to changes after re-opening a project.

### Steps to Reproduce

1. Initialize Project
2. Close and Re-open project

**Expected behavior:** Changes, History, Branches view to be up to date.

**Actual behavior:** Views retain values from state when project was closed.

**Reproduces how often:** Unknown *(100%)*

**Log File:** https://gist.github.com/StanleyGoldman/5a77601d6042b48d0070859b010f0d39

### Workaround
Leave Settings tab active when closing Unity

**Comment by Lobsterovich** [comment]
+5

**Comment by Lobsterovich** [comment]
Cool

**Comment by StanleyGoldman** [comment]
Hey @ThomasAunvik other than issue #681 I don't see anything i your log file that indicates an error in displaying of changes. Can you tell me what is incorrect here?

**Comment by ThomasAunvik** [comment]
As you can see in the ProjectSettings folder there are folders and assets that belong to the Assets folder.

**Comment by ThomasAunvik** [comment]
![image](https://user-images.githubusercontent.com/9968151/38501708-e5934298-3c0d-11e8-9643-e5d11de8983f.png)

**Comment by StanleyGoldman** [comment]
Question, is your project the root of the git repo or is your project contained in your git repo?
It seems your project is contained in the git repo...

**Comment by ThomasAunvik** [comment]
The project is contained in the git repo.

**Comment by StanleyGoldman** [comment]
Yea, I don't normally test that way. Let me try now.

**Comment by ThomasAunvik** [comment]
I have also noticed the .git url does not change when you change the repository name.

**Comment by StanleyGoldman** [comment]
Wanna throw that note in a separate issue for me?

**Comment by StanleyGoldman** [comment]
Can confirm wonkiness...

![image](https://user-images.githubusercontent.com/417571/38504244-2d84208a-3be2-11e8-9020-19039655a191.png)

**Comment by ThomasAunvik** [comment]
This shows when i do `git status`
![image](https://user-images.githubusercontent.com/9968151/38504551-420f297c-3c15-11e8-8260-6cd580d5938c.png)

**Comment by StanleyGoldman** [comment]
I've discovered the root cause...

**Comment by ThomasAunvik** [comment]
This bug has not been completely fixed.
![image](https://user-images.githubusercontent.com/9968151/38776640-874b9438-409a-11e8-8f02-9b5a361505fe.png)
![image](https://user-images.githubusercontent.com/9968151/38776645-8e0c6306-409a-11e8-88b3-ea4837634f46.png)
Using version: 0.31.7
[Log File](https://gist.github.com/ThomasAunvik/03a7a808fa6548473ab553457536dde2)

**Comment by StanleyGoldman** [comment]
Hey @ThomasAunvik would you mind creating a different bug with this issue...
