### ISSUE TITLE
Sign out functionality does not work for existing repositories

### ISSUE THREAD

**Issue by meaghanlewis** [github-for-unity/Unity#687]
### Description
On a new project, before publishing the repo, I can sign in and sign out successfully using GHfU. After publishing the project, I select sign out, but the UI never updates to show sign out.

### Steps to Reproduce
For an existing project that has been published...
1. Select Account -> Sign out
2. Then open the Account dropdown again

**Expected behavior:**
To see the option Sign in
![sign out responsive](https://user-images.githubusercontent.com/10103121/38574323-69e97b1c-3cad-11e8-90e0-9ffbbdba5d0e.gif)

**Actual behavior:** 
Sign in never shows for existing repositories.
![sign out unresponsive](https://user-images.githubusercontent.com/10103121/38574332-6e8340a4-3cad-11e8-8d8d-73c74991346e.gif)

**Reproduces how often:** 
100%

### Additional Information

I see this in the log `Running '/usr/local/bin/git credential-osxkeychain erase'` but the UI never updates to show that I'm signed out.

**Comment by StanleyGoldman** [comment]
So I've been testing, and I think i reduced the steps to reproduce the behavior you are seeing...

I think the sign out is working, but there is a bit of a race condition before the dropdown updates...

1. Install the plugin in a brand new project (no need to initialize)
2. Authenticate correctly
3. Sign out
4. Click the Account dropdown quickly, notice the option to Sign In
5. Authenticate correctly
6. Close and reopen project
7. Sign out
8. Click the Account dropdown quickly, notice Sign out still appears
9. Do not click sign out, but remove focus from dropdown so it closes
10. Open dropdown again, notice Sign out is gone

![img](https://i.imgur.com/7tJd2df.gif)

**Comment by ThomasAunvik** [comment]
Found the issue of the original problem, at `RemoveConnection()`, changing it to this fixes it:

    private void RemoveConnection(UriString host)
    {
        // create new connection in the connection cache for this host
        if (connections.ContainsKey(host.Host))
        {
            connections.Remove(host.Host);
            SaveConnectionsToDisk();
    }

**Comment by meaghanlewis** [comment]
Im still experiencing the same issue while testing the latest release build. 

Sign out works immediately before the project is initialized, but after initialization the sign out option doesn't sign me out even after waiting for minutes.
