### ISSUE TITLE
Changes are incorrectly sorted/nested

### ISSUE THREAD

**Issue by ThomasAunvik** [github-for-unity/Unity#695]
### Prerequisites

[Log File](https://gist.github.com/ThomasAunvik/029ee830ff76a01409622134eea96c95)
[gitstatusentries.yaml](https://gist.github.com/ThomasAunvik/a9e8162ea3602f9ddd388f017cdbdfba)
### Description

The changes that shows in unity are incorrectly registered, this happens as follows:
![image](https://user-images.githubusercontent.com/9968151/38833289-65b60e3a-41c5-11e8-80a8-320b2c7b9d65.png)
![image](https://user-images.githubusercontent.com/9968151/38833291-65cff048-41c5-11e8-8a2a-57fccd5db822.png)

Sometimes status of the assets do not show in the Project Window. (Check additional screenshots)

### Steps to Reproduce

(Steps to reproduce is uncertain)

1. Create alot of files, i suggest trying on a big project, or change alot of stuff with different stuff.
2. Check changes,
3. See that something is in the wrong folder and changes icon in the asset menu is wrong, (like deleted)

**Expected behavior:** To show correct changes.

**Actual behavior:** Changes are registered in the wrong folder and is registered as deleted.

**Reproduces how often:** 100% for me

### Additional Screenshots
![image](https://user-images.githubusercontent.com/9968151/38833506-03a11914-41c6-11e8-8010-490192f5d8eb.png)

![image](https://user-images.githubusercontent.com/9968151/38833658-73cc768e-41c6-11e8-848c-1e9a8f68a109.png)

**Comment by StanleyGoldman** [comment]
I was able to reproduce this issue...

![image](https://user-images.githubusercontent.com/417571/38836993-513dd6bc-419e-11e8-8d40-513a1dcd2c94.png)

**Comment by StanleyGoldman** [comment]
Now that I understand it... I'm going to update this issue with the actual error.
