### ISSUE TITLE
Files locked by other users can't be unlocked in Settings.

### ISSUE THREAD

**Issue by SanyaIV** [github-for-unity/Unity#711]
### Prerequisites
[github-unity.log](https://github.com/github-for-unity/Unity/files/1971011/github-unity.log)

### Description

Files that are locked by other users can not be unlocked through the Settings by anyone other than the person that locked it.

### Steps to Reproduce

1. Have someone else lock a file
2. Try to unlock that file yourself

**Expected behavior:** File to unlock, alternatively pop-up asking if the user wants to force unlock the file.

**Actual behavior:** Nothing visible happens at all, file remains locked.

**Reproduces how often:** 100% so far.

**Comment by StanleyGoldman** [comment]
Thanks @SanyaIV for sending in this bug report.

**Comment by StanleyGoldman** [comment]
Fix coming soon
