### ISSUE TITLE
Commit Button always Disabled

### ISSUE THREAD

**Issue by Ziflin** [github-for-unity/Unity#712]
### Description

I'm testing the plugin using Unity 2018.1 with VSTS (just had a project there already) and everything seems to work, but the "Commit to [master]" button is disabled even though it's showing I have 1 changed file and have entered a summary and description. 

I know testing it with VSTS probably hasn't been done, but I thought I'd try. Is this something that should work or is expected not to?

(I see no errors in the `github-unity.log` file.)

**Comment by StanleyGoldman** [comment]
Hey @Ziflin thanks for testing out our stuff.
I just started testing in 2018.1 myself today. I have not run into that yet.

But here is what you can do for me..

1. Enable trace logging
2. Make a few changes in your repo to trigger the file watchers and background processes that should trigger a redraw
3. Try to check in your files as normal
4. Upload the log

There may not be an outright error in the log that pops out at you, but the data in the log will give me a lot of information about what is happening and then we can take it from there.

**Comment by StanleyGoldman** [comment]
Also, the commit button will remain disabled until you check files AND have text in the "Commit summary" textbox.

Sorry if that is obvious... just y'know... had to be sure...

**Comment by ThomasAunvik** [comment]
@Ziflin are you still there?

**Comment by StanleyGoldman** [comment]
Hey @Ziflin I'm gonna close this issue for now. If you are able to reproduce the issue please feel free to re-open the issue.

**Comment by Ziflin** [comment]
Sorry @StanleyGoldman, I tried it on another machine and it seemed fine, so I'll let you know if I run into it again.

**Comment by StanleyGoldman** [comment]
Don't be sorry. Thanks for testing our stuff out.

**Comment by PierreCorneille** [comment]
Using Unity 2019.4.12f1 the button 'Commit' stays grey, my 'commit summary' and 'commit description' fields are not empty and I selected (all) files I want to commit.

PS: please check the comments on the plugin in the asset store, there are lot of users reporting issues. (As a Unity tool developer myself I know unfortunately publishers are not notified when there is a new comment on the sotre)
