### ISSUE TITLE
How to change connection from github.com to another git based website?

### ISSUE THREAD

**Issue by mwcatt** [github-for-unity/Unity#722]
My employer uses their own git based website and I'm trying to see if this plugin will help our workflow in Unity.  Unfortunately, I can't figure out how to change the website the plugin is trying to connect to, so instead of connecting to github.com, I need to tell the app to connect to mydummygit.com.

Any insight would be much appreciated.

**Comment by mwcatt** [comment]
Just saw another post stating that git needs to be installed in order to connect.  I thought it was, but it turns out I was wrong.  Will install and come back if I have any more issues.

**Comment by StanleyGoldman** [comment]
Hi @mwcatt the only functionality that is tied to GitHub is the authentication and the login process. For everything else we are just executing normal git commands for you. So if you have a project that has a different remote than github.com, things should just work.

**Comment by mwcatt** [comment]
That's the thing, I don't login through GitHub, I login to our server using my credentials there.  I actually had to create a GitHub login simply to make this post...

**Comment by StanleyGoldman** [comment]
Is your company already using git?
