### ISSUE TITLE
Implement Git Fetch

### ISSUE THREAD

**Issue by StanleyGoldman** [github-for-unity/Unity#73]

**Comment by thorade** [comment]
Should there be a notification upon success?
Something like: Already up to date? Analogous to the Pull button?

**Comment by StanleyGoldman** [comment]
We talked about it [here](https://github.com/github-for-unity/Unity/pull/74#pullrequestreview-48048740). We came to the decision that we dont need the confirmation since `git fetch` does not change anything in your workspace directly.

**Comment by thorade** [comment]
Yes, I saw that. I think a confirmation ("Do you REALLY want to fetch?") is not necessary, but some feedback that fetching finished successfully might be helpful!?
Can you use the status bar at the very bottom of the window maybe?

**Comment by StanleyGoldman** [comment]
Using the status bar may not be a bad idea. Do me a favor and throw a feature into the backlog and we can talk about it.

**Comment by thorade** [comment]
Sorry, what do you mean by backlog? Open a new issue?

**Comment by StanleyGoldman** [comment]
Yea, sorry, that's what i meant.
