### ISSUE TITLE
Silent fail of request lock

### ISSUE THREAD

**Issue by sguthals** [github-for-unity/Unity#769]
Request lock silently fails whether:
1. Someone else already has the lock
2. You do not have permissions to request the lock

**Comment by Joen-UnLogick** [comment]
3. If the repository doesn't support LFS
4. If you attempt to lock a folder
5. Any other possible error scenario

Even worse the isBusy flag is never cleared, so the system stays Busy until you do script reload at which point the static bool is cleared.

**Comment by Joen-UnLogick** [comment]
Was this fixed in the release yesterday?

**Comment by shana** [comment]
@Joen-UnLogick This was fixed in the 1.0rc1, yes
