### ISSUE TITLE
Clearly document that GitHub for Unity requires Git be Installed

### ISSUE THREAD

**Issue by soulburner** [github-for-unity/Unity#78]
As I have tried the plugin on the machine which didn't have any kind of Git client installed ever, I've got the issue when I was pressing "Initialize repository" button, but nothing happened (which is abviously confusing for the user).

Then I looked into the log file and found these lines:

> *** Please tell me who you are.
> Run
>   git config --global user.email "you@example.com"
>   git config --global user.name "Your Name"

So, I've opened the command line and setup my e-mail and username. After that, "Initialize" button made its work and also these settings appeared in the "Settings" tab of the plugin window.

My suggestion is that the plugin should treat this situation automatically and ask a user for his email and username. That's a not big problem - just to ask for user data and run these 2 commands. Otherwise it is very confusing for the non-technical user (for example, an artist) to start using git-for-unity.

PS: Maybe if you're testing the plugin on your machines, you have never run into this issue because you have your git client set already ;)

**Comment by StanleyGoldman** [comment]
Hey @soulburner thanks again for testing so much. I appreciate it.

This is a known issue.

I have it here _**#25 Add fields to set git name/email on Initialize Repository view**_
Also, we do make note of that in https://github.com/github-for-unity/Unity#windows but I'm afraid that maybe we aren't clear enough about that right now.

**Comment by soulburner** [comment]
Yeah, that's at the very end of the article. So, if you fail on the step 1, you will not read the whole article to the very end ;)

**Comment by StanleyGoldman** [comment]
😆 Duly noted. I'll fix that for now.

**Comment by StanleyGoldman** [comment]
I'll fix it later. 😆 🍺 🏖

**Comment by adamhill** [comment]
A side test: Does it work / fail in other weird ways with the default OSX Git client?

If we need to get the end use to install Git (ie. the plugin is not going to use libgit) might I make the suggestion we encourage them to use

- [Homebrew](https://brew.sh/) on OSX
- [Chocolatey](https://chocolatey.org/) on Windows 

So they have a mechanism to update as the tool evolves.

**Comment by shana** [comment]
I could have sworn I added some instructions for homebrew on OSX, but apparently not. I'll fix that up.

We're still trying to figure out how best to keep the users up to date, as we can't use libgit2sharp and we can't update native dlls in place. I've opened #84 to discuss distribution mechanisms for git and git lfs, we can chat more there 😄
