### ISSUE TITLE
"Push" Button graphical error hiding button text

### ISSUE THREAD

**Issue by Digbigpig** [github-for-unity/Unity#782]
### Prerequisites

[github-unity.log](https://github.com/github-for-unity/Unity/files/2023296/github-unity.log)

The project location looks like it's using unity 4.6 but it is actually 2017.3. It decided to initialize inside of an old project folder for some reason.
### Description

The "Push" button loses its text after a commit, making it look like there is no option to push your changes.

### Steps to Reproduce

1. Set-up Github for Unity in the project, create remote repo, initial commit through Unity.

2. Commit a change / commit your current project. Notice that the push button is no longer displaying text but it is interactable.

Post Commit: 
![post_commit_unity](https://user-images.githubusercontent.com/33472496/40318447-df4e28c2-5ce1-11e8-8724-914af3744c02.PNG)
![post_commit_unity1](https://user-images.githubusercontent.com/33472496/40318456-ea010cd0-5ce1-11e8-8336-01f2c716a393.PNG)

3. Once you have pushed the changes the text will reappear.

![post_commit_unity2](https://user-images.githubusercontent.com/33472496/40318507-17846594-5ce2-11e8-8994-546db2c50c5f.PNG)

![post_commit_unity3](https://user-images.githubusercontent.com/33472496/40318509-19aa0e8c-5ce2-11e8-912e-ec4009a0889c.PNG)

**Expected behavior:** The push button should hide its text when there are no pending commits as there would be no reason to push nothing.

**Actual behavior:** It displays when there are no commits to send and hides when there are

**Reproduces how often:** After every commit I've done on this project. I've reproduced 3 times.

**Comment by shana** [comment]
@Digbigpig Thanks for the report! We have a fix for this, should be out today with the new release, just as soon as I put some release notes together 😄

**Comment by Digbigpig** [comment]
@shana Looks like that did the trick. Great work.
