### ISSUE TITLE
Change in project location produces warnings (Initialization failed)

### ISSUE THREAD

**Issue by Digbigpig** [github-for-unity/Unity#784]
### Prerequisites

[github-unity.log](https://github.com/github-for-unity/Unity/files/2028825/github-unity.log)

### Description

After I moved my Unity project location locally (It had initialized its folder within another project for some reason) I receive a few warnings within the unity console.

![warning0](https://user-images.githubusercontent.com/33472496/40394196-a87e1268-5ddf-11e8-9a6d-6431b36b5690.PNG)

![warning1](https://user-images.githubusercontent.com/33472496/40394210-bcab6114-5ddf-11e8-832f-62077719b4e7.PNG)

### Steps to Reproduce

1. Copy folder containing Unity project to another location and delete the original folder

**Expected behavior:** No warnings

**Actual behavior:** Receives warnings.

**Reproduces how often:** Warnings show on startup and in play mode.

### Additional Information

Game and github for unity seems to run fine. I will update if there are further issues

**Comment by shana** [comment]
Thanks for the report! Could you enable Trace Logging in the Settings tab and post the log file? Hopefully there will be more details in there about this.

**Comment by StanleyGoldman** [comment]
Hey @Digbigpig I'm gonna close out this issue.
If you continue to have a problem open it up for create a new issue.
