### ISSUE TITLE
Empty .gitignore file gets generator in Assets

### ISSUE THREAD

**Issue by ThomasAunvik** [github-for-unity/Unity#792]
When initializing the project, an empty .gitignore file apperas in the `Project/Assets` folder.

Tested on multiple projects, same thing happened.

Tested on [fixes/783-restart-on-wrong-thread](https://github.com/github-for-unity/Unity/tree/4a6c6d8b5cfabf694d7bb8b0774a2739205a0651)

[Log File](https://gist.github.com/ThomasAunvik/3922ebc26e908a847875226268b23fee)

Notice this on logfile (line 20)
```
180523-20:27:51.226 TRACE [14] <ProcessWrapper> Running 'C:\Users\Bruker\AppData\Local\GitHub for Unity Debug\git\cmd\git.exe add  --  "A:/Projects/New Unity Project/.gitignore" "A:/Projects/New Unity Project/.gitattributes" "A:/Projects/New Unity Project/Assets/.gitignore"'```

**Comment by shana** [comment]
Yes, this is on purpose. The way Unity recognizes a project is if it has an Assets folder, and git can't track folders, so if we didn't add something that git can track in there to the initial commit, no one would be able to open the project in Unity on the first commit.
