### ISSUE TITLE
Lock/UnLock with multiple selected

### ISSUE THREAD

**Issue by Joen-UnLogick** [github-for-unity/Unity#795]
### Description

When selecting more than one file in the project view and then opening the context menu and locking/unlocking will only affect one. 

### Steps to Reproduce

1. Select two versioned files in Unity
2. Right click and "Request Lock"

**Expected behavior:** [What you expect to happen]

I expect both to be locked.

**Actual behavior:** [What actually happens]

Only one is locked.

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

### Additional Information

Just look at all of Selection.objects instead of only Selection.activeObject

**Comment by ThomasAunvik** [comment]
Kind of similar to #780
