### ISSUE TITLE
No public access to the git client

### ISSUE THREAD

**Issue by Joen-UnLogick** [github-for-unity/Unity#810]
### Description

As part of our internal tools pipeline it would be super helpful to have public access to the GitClient class. In particular we have one repository for development and another repository for our actual releases.

### Additional Information

I know this is a feature request and you're unlikely to drop everything in your hands to add this. I am surprised at how tightly everything is wrapped into dlls without public visibility, is there a reason for this?

**Comment by shana** [comment]
@Joen-UnLogick It was done to avoid conflicting with other namespaces during development, until we settled on a decent API. I'm happy to make things public now, the GitClient is definitely meant to be an independent API that anyone can use.

**Comment by StanleyGoldman** [comment]
Hey @Joen-UnLogick I've started work on this. If you'd like to pitch in you are more than welcome. 🍻
