### ISSUE TITLE
Update documentation and user guides

### ISSUE THREAD

**Issue by shana** [github-for-unity/Unity#825]
This is a starting list of the user guides that we should probably have at a minimum. Some of them have already started to be fleshed out, others need starting. This isn't exhaustive, if you see something missing, feel free to add it to the list.

The user guides are currently in the https://github.com/github-for-unity/Unity/tree/master/docs/using folder. If you want to work on a doc, just add a comment with what you're grabbing. For guidelines on how docs should generally look like, see the GHfVS at https://github.com/github/VisualStudio/tree/master/docs

- [ ] Getting Started
   - [ ] Setup GitHub for Unity
      - [ ] On an existing project
      - [x] On a new project
   - [x] Install & Updating GitHub for Unity
   - [ ] Uninstalling GitHub for Unity
   - [ ] Git configuration
   - [ ] Repository configuration
   - [ ] Git installation
   - [x] Authentication
      - Login in GitHub for Unity
      - Personal access tokens
      - Working with other git providers
- [ ] Working with GitHub for Unity
   - [x] Commit your changes
   - [x] Pushing your work
   - [x] Reverting changes
   - [x] Pulling other people's changes
   - [ ] Exclusive locks on files for editing
      - Requesting locks
      - Releasing locks
      - Seeing existing locks
   - [x] Managing branches
     - Create
     - Checkout
     - Delete

**Comment by stanishev** [comment]
If anyone can add **Uninstalling Github for Unity** that would be truly stellar.
🙏

**Comment by makkasu** [comment]
Hi, I'm trying to use this project but running into difficulties connecting two machines/accounts to the same project. [This section of the docs](https://github.com/github-for-unity/Unity/blob/master/docs/using/getting-started.md#connecting-to-an-existing-repository-that-already-has-the-github-for-unity-package) is missing - if someone has some instructions I'd be happy to write them up nicely for the docs. 

Currently I've ended up in a mess with the two machines on completely different version histories, refusing to pull or push.

**Comment by Ragueel** [comment]
I can take the git configuration and installation. What exactly is needed from the git configuration?
