### ISSUE TITLE
Tree incorrectly parents meta files

### ISSUE THREAD

**Issue by shana** [github-for-unity/Unity#830]
If two files start with the same string, the tree control incorrectly parents the first file's metafile (i.e., it doesn't get parented).

![image](https://user-images.githubusercontent.com/310137/41368484-fa103b2c-6f39-11e8-87c4-1793b8b4eb90.png)

**Comment by StanleyGoldman** [comment]
```
12:05 $ git status -b -u --porcelain
## master
?? Assets/Plugins/GitHub/Editor/GitHub.Unity.dll
?? Assets/Plugins/GitHub/Editor/GitHub.Unity.dll.mdb
?? Assets/Plugins/GitHub/Editor/GitHub.Unity.dll.mdb.meta
?? Assets/Plugins/GitHub/Editor/GitHub.Unity.dll.meta
```
