### ISSUE TITLE
Credentials have changed when publishing

### ISSUE THREAD

**Issue by Swinkid** [github-for-unity/Unity#831]
### Prerequisites
[github-unity.log](https://github.com/github-for-unity/Unity/files/2099265/github-unity.log)
- Latest Git (Same results on older versions)
- Latest Git for Unity
- Latest Unity (Same results on older versions)
- Windows 10

### Description

Prompts for credentails and 2FA every time I click publish. Doesn't let me get futher. Produces error message that credentials have changed and I need to login.

### Steps to Reproduce

1. Initialize Repository
2. Sign In
3. Commit Changes
4. Publish

**Expected behavior:** 
Be able to publish to github.

**Actual behavior:** 
Prompts for sign in credentials again. Error message mentioning that my credentials have changed and I need to sign in.

**Reproduces how often:** Always

### Additional Information

Using Git for unity 1.0.0rc4, Latest Git Bash. Same behaviour happened with older version of git.

**Comment by shana** [comment]
@Swinkid Are you on Mac or Windows?

**Comment by Swinkid** [comment]
Windows. I should've mentioned that. Apologies, I'll amend my post.

**Comment by shana** [comment]
@Swinkid No worries, thanks for the update! Not sure why this is happening, but I can give you some steps to clean up the login state, and maybe that will make things work.

Before that though, could you paste the `%LOCALAPPDATA%\GitHubUnity\connections.json` file so I can doublecheck what it has? After that, you can nuke it and try to publish again, see if that sorts it out (you might want to restart Unity just to make sure it picks up the deleted file)

**Comment by Swinkid** [comment]
[connections.txt](https://github.com/github-for-unity/Unity/files/2099329/connections.txt)
Had to rename it for github to let me upload a json file.

Should have also mentioned I tried both bundled and git for windows.

**Comment by Swinkid** [comment]
So i think I've found the problem.

Their seems to be some conflict between using my username and email address. I've just cleared my user settings and connections.json and tried signing in with my email address. This seems to have worked properly.

**Comment by shana** [comment]
@Swinkid Thank you for the report, that's definitely a bug, we'll dig into it.

**Comment by Swinkid** [comment]
@shana Thanks. I'll see if i can take a look also and ill submit a p/r if i find out why

**Comment by StanleyGoldman** [comment]
Hey @Swinkid 

There have been a few changes to how we authenticate by now.
I'm going to close up this issue.

If you can reproduce a problem, please let me know and we can open this issue back up.
