### ISSUE TITLE
Support stashing files

### ISSUE THREAD

**Issue by spaceemotion** [github-for-unity/Unity#837]
This is more of a feature request, as I haven't had the time to try out the plugin yet (I just finished watching the session video).

I very frequently use the stash feature to check out a working commit to quickly show people the things I've been working on. It would be nice if the extension could add support for the stash push and pop features (including untracked files) – I'd also be willing to work on a PR for this, if I got some free time and/or my team needs it.

**Comment by StanleyGoldman** [comment]
Hey @spaceemotion that would be cool. If you want to do it yourself we will definitely help point you in the right direction. Otherwise we will get to this eventually.
