### ISSUE TITLE
Distributing git + git lfs - strategies and alternatives

### ISSUE THREAD

**Issue by shana** [github-for-unity/Unity#84]
Right now we're bundling git + git lfs on Windows and and unpacking it to a known placed tagged with the md5 of the package. We check md5 sums for git and git lfs to determine whether we need to update it - git lfs gets updated in place, while git gets updated by unpacking it to a new directory (since the folder has the md5 in its name)

We're doing this so we know that we have a git and git lfs version we can trust in a know location, but it adds a lot of bloat to the extension package. We need to figure out our git and git lfs distribution mechanism and how to best handle updates and version checks.

## Options

1. Bundle git and git lfs in the package for windows and mac as we do now
   - Pros: We always know what we're running and the user doesn't have to do anything or wait for anything once the extension has been downloaded
   - Cons: Large initial download size
2. Don't bundle anything; on first install, download git and git lfs from our own hosting server and put them in a known place. On every first run of the extension, check for updates of git and git lfs and download them as needed.
known to not happen)
   - Pros: Small extension package size. Automatic updates
   - Cons: We don't have downloader code yet.

3. Don't bundle anything and do a version check on the system git and git lfs. If they don't exist on the path, or if they're not recent enough, disable the UI and provide an instructional message on how to install git and git lfs on the user system
   - Pros: Small extension package size. Existing update mechanisms (at least for OSX, Windows is way more annoying).
   - Cons: User has to set up things and keep them up to date (something that traditionally has been known to be a failure point). User has to update two things - git and git lfs (different release schedules)

Other options? Ideas? Thoughts? Opinions? Missing pros and cons above?

**Comment by tagsrock** [comment]
I love that it is bundled. I use Ubuntu for Windows / Linux for Windows on Win 10, and try not to install gitscm on windows as every program seems to integrate it differently, some pipelines want it as path, some want it local. I honestly didn't even know it could be embedded in a project like this. To me this is the way to go, have your repo and git where you control both and their implementation. This is the way to think in my humble opinion. You asked for thoughts :-)
