### ISSUE TITLE
Undo Commit

### ISSUE THREAD

**Issue by ghost** [github-for-unity/Unity#840]
### Description

Feature request.

The Github desktop client has the capability to undo a commit. 

Having the same functionality in this client would be *very* nice.

**Comment by StanleyGoldman** [comment]
Hey @rgjones33... Thanks for testing our stuff out.

We already have this function. If you right click a commit in the history view, you get the option to revert.

![img](https://i.imgur.com/PXVwmtQ.png)

**Comment by rgjones33** [comment]
Stanley, revert is not the same as undo. Please refer to your own client client for mac or windows.

![image](https://user-images.githubusercontent.com/26989653/41810229-29f26720-76c9-11e8-9140-d82fd3d74976.png)
