### ISSUE TITLE
Hanging on Initialization

### ISSUE THREAD

**Issue by schooltoons** [github-for-unity/Unity#841]
### Description

Console Displays this Error
ArgumentException: Value does not fall within the expected range.
SyntaxTree.VisualStudio.Unity.Bridge.CompilationUnit.LanguageOf (SyntaxTree.VisualStudio.Unity.Bridge.CompilationUnit unit)
SyntaxTree.VisualStudio.Unity.Bridge.CompilationUnit.CompilationUnits (System.String method)
SyntaxTree.VisualStudio.Unity.Bridge.CompilationUnit.CompilationUnits ()

Accessing the window Github for Unity and it displays the rotating logo. Account info grayed out. Selecting built in or System Github succeeds but makes no difference. Just hangs on the rotating logo, with Initializing message.

### Steps to Reproduce.

1. Launch Unity with new empty project
2. Open GitHub window
3. Fails to initialize beyond showing the logo
4. github-unity.log indicates C:\Users\Jim\AppData\Local\GitHubUnity\git-lfs\git-lfs.exe is out of date, Plugin was installed from latest download from Asset Store and popup window indicating new version available was used to install new version.

### Additional Information

Downloaded and installed Git LFS. Used find system git successfully. Tried to initialize. Git for Unity autofilled user with computer name and correct email. Quit Unity, restarted Unity, entered correct user name and email, initialization ran correctly

[github-unity.log](https://github.com/github-for-unity/Unity/files/2130973/github-unity.log)

[github-unity.log](https://github.com/github-for-unity/Unity/files/2131105/github-unity.log)

**Comment by harperAtustwo** [comment]
I also have this problem. I closing and re-opening the Github window within Unity. It got rid of the little "Initialization" progress bar but I only get a spinning logo. No ability to perform any actions, like commit my changes.

**Comment by schooltoons** [comment]
Solved by installing LFS locally and 2 relaunches of Unity. Not OS related.
For me personally, I am looking at ways to integrate version control for Unity projects in a high school classroom. I am still experimenting with Git-Classroom and various ways of sharing art assets.

**Comment by StanleyGoldman** [comment]
Let us know if you have more trouble with it.

**Comment by StanleyGoldman** [comment]
Hey, you guys were not crazy, this issue should be fixed by #876 and #877
