### ISSUE TITLE
Allow pulling with uncommitted changes

### ISSUE THREAD

**Issue by Baste-RainGames** [github-for-unity/Unity#849]
Whenever you click the "pull" button with uncommitted changes, you get the message "You need to commit your changes before pulling".

This is a major drawback, as you often might want to pull changes while having code files or asset files that are not ready to be committed. 
For example, if my level designer is working on a level and assets, and runs into a bug that's blocking progress, he'll often ask me for a fix. If I push the fix up, now he has to either commit a half-finished level, or discard his work, in order to pull the fix. 
In this case, running the "git pull" command from the command line would work without problems.

I suggest that the plugin should instead do what git does, and allow the pull as long as there won't be a conflict with any of the uncommitted files. If there's a conflict with any uncommitted files, you should list the files that need to be discarded or committed before the pull can go through. This information is provided by the git pull command in a pretty readable format, so you probably just want to pipe that information through to the user as-is.

**Comment by Romaleks360** [comment]
Any updates? I'm afraid this weird behavior will force my team of non-programmers to use GitHub Desktop.

**Comment by aymusbond** [comment]
Yeah, it's been 2 years since this issue was posted, no solutions yet?

**Comment by MacKenzieHnC** [comment]
Right click on the changes, select discard
