### ISSUE TITLE
SharpZipLib conflicts with third parties

### ISSUE THREAD

**Issue by trilobyteme** [github-for-unity/Unity#850]
### Conflict with Archimatix

When installing into Unity 2017.2.3p1 on macOS, I get the following hard stop error that will not clear:

![image](https://user-images.githubusercontent.com/22625985/42064910-fcca4c90-7aec-11e8-94ac-a51a8c61a046.png)

### Steps to Reproduce

1. Launch Unity
2. Install Github for Unity

I expected this to install without any errors that could not be cleared easily.

**Actual behavior:** hard stop error that will not clear

**Reproduces how often:** Always

**Comment by StanleyGoldman** [comment]
Thanks for reporting this. We can work around it soon.

**Comment by shana** [comment]
@trilobyteme While we're figuring out how to make this not happen, you can delete one of the copies of the assembly and things should work well - only one of them needs to be loaded in the process for things to work.

**Comment by StanleyGoldman** [comment]
Hey @trilobyteme sorry this has taken so long to get to.
We have an official fix coming soon. It will be fixed along with #908.

**Comment by sguthals** [comment]
Testing: 
1. install our extension and that app from the store
2. delete octorun from your appdata folder 
3. hit play and stop
