### ISSUE TITLE
Not show "Release Lock" in Menu Item

### ISSUE THREAD

**Issue by ykush** [github-for-unity/Unity#851]
### Description
Not show "Release Lock" in Menu Item
![2018-06-29_17h07_29](https://user-images.githubusercontent.com/23243915/42080918-0d1fd2a4-7bbf-11e8-891a-0138fe399b7f.png)

### Steps to Reproduce
1. Lock any file
2. Right click locked file

**Reproduces how often:** Always

### Additional Information
https://github.com/github-for-unity/Unity/blob/41ae437c8b664872116bf5b596b588a7b08af2d6/src/UnityExtension/Assets/Editor/GitHub.Unity/UI/ProjectWindowInterface.cs#L122
This line should be `AssetsMenuReleaseLock` here instead of `AssetsMenuReleaseLockForced`, shouldn't it?

**Comment by StanleyGoldman** [comment]
🥇 LOL thanks @ykush.
Would you want to make that change in a pull request so you can get the credit?

**Comment by ykush** [comment]
@StanleyGoldman Thank you for your proposal.
I tried creating this pull request https://github.com/github-for-unity/Unity/pull/852.
But build is failed..

**Comment by StanleyGoldman** [comment]
Hey @ykush I don't think the failure is your fault. We have bugs in the build server that prevent it from building successfully for other users.

**Comment by StanleyGoldman** [comment]
Fixed by #852 thanks @ykush
