### ISSUE TITLE
Fails to push: HttpRequestException fatal: could not read username for "https://github.com": no error

### ISSUE THREAD

**Issue by blackpandastudios** [github-for-unity/Unity#856]
### Prerequisites

[github-unity.log](https://github.com/github-for-unity/Unity/files/2152366/github-unity.log)

### Description

Initially it hung on publish and then unity crashed.

the github window on re-launch said I had nothing to push, however nothing was on the github repo it created.

I then went to git cmd line and tried to push and got an error saying git credentials were not found.
I then went to source tree and hit push, worked fine.

Went back to unity to make a change, hit push and now I get this error:

GitHub.Unity.ProcessException: fatal: HttpRequestException encountered.
   An error occurred while sending the request.
bash: /dev/tty: No such device or address
error: failed to execute prompt script (exit code 1)
fatal: could not read Username for 'https://github.com': No error

### Steps to Reproduce

1. make a change
2. hit push
3. errors on a httpswebexception

**Expected behavior:** It to push to the repo

**Actual behavior:** It fails. (it is as if my credentials are wrong but I am logged in)

**Reproduces how often:** Every time I push through github for unity

### Additional Information

It is a private repository created from the git for unity repo creation.

Also the output from source tree has the same error however it succeeds still.

git -c diff.mnemonicprefix=false -c core.quotepath=false push -v --tags origin master:master
fatal: HttpRequestException encountered.
   An error occurred while sending the request.

Pushing to https://github.com/blackpandastudios/VR-Avatar-Essentials.git
POST git-receive-pack (2940 bytes)
To https://github.com/blackpandastudios/VR-Avatar-Essentials.git
   b512009..03f5cf7  master -> master
updating local tracking ref 'refs/remotes/origin/master'

Completed successfully.

**Comment by shana** [comment]
@blackpandastudios Thanks for the report, we're investigating it. Do you get that error every time you push from sourcetree (even though it succeeds afterwards)?

**Comment by blackpandastudios** [comment]
@shana No worries! And yeah that's right!

It is my first private repo, I'm just wondering if there were some prerequisite setup tasks I may have overlooked maybe?

**Comment by shana** [comment]
I don't know, it's odd, I don't know what's causing that error. Could you open a command line, run `set GIT_TRACE=1` and then try to push and paste the output? That will enable trace logging on git and hopefully show which command is causing that http request error

**Comment by blackpandastudios** [comment]
Ahh ok, I will enable trace logging and give it a go shortly.

I'm also working on 2 different accounts on GitHub, not on the same project of course, however I'm constantly entering credentials into cmd when pushing when swapping from work to personal, maybe there's user data stored there that is clashing with the acc I'm trying to use? Bit of a stav in the dark but yeah.

**Comment by blackpandastudios** [comment]
C:\Users\InspaceXR\Documents\BlackPandaStudios\VR-Locomotion-Essentials>git push origin master
09:11:19.678123 git.c:344               trace: built-in: git 'push' 'origin' 'master'
09:11:19.681100 run-command.c:626       trace: run_command: 'remote-https' 'origin' 'https://github.com/blackpandastudios/VR-Locomotion-Essentials.git'
09:11:19.691085 git.c:576               trace: exec: 'git-remote-https' 'origin' 'https://github.com/blackpandastudios/VR-Locomotion-Essentials.git'
09:11:19.691085 run-command.c:626       trace: run_command: 'git-remote-https' 'origin' 'https://github.com/blackpandastudios/VR-Locomotion-Essentials.git'
09:11:20.568945 run-command.c:626       trace: run_command: 'git credential-manager get'
09:11:20.598827 git.c:576               trace: exec: 'git-credential-manager' 'get'
09:11:20.599824 run-command.c:626       trace: run_command: 'git-credential-manager' 'get'
fatal: HttpRequestException encountered.
   An error occurred while sending the request.
09:11:24.257551 run-command.c:626       trace: run_command: 'bash' '-c' 'cat >/dev/tty && read -r line </dev/tty && echo "$line"'
Username for 'https://github.com': joel@blackpandastudios.com
09:11:32.047966 run-command.c:626       trace: run_command: 'bash' '-c' 'cat >/dev/tty && read -r -s line </dev/tty && echo "$line" && echo >/dev/tty'
Password for 'https://joel@blackpandastudios.com@github.com':
09:11:37.076104 run-command.c:626       trace: run_command: 'git credential-manager store'
09:11:37.102987 git.c:576               trace: exec: 'git-credential-manager' 'store'
09:11:37.102987 run-command.c:626       trace: run_command: 'git-credential-manager' 'store'
09:11:37.324580 run-command.c:626       trace: run_command: 'send-pack' '--stateless-rpc' '--helper-status' '--thin' '--progress' 'https://github.com/blackpandastudios/VR-Locomotion-Essentials.git/' '--stdin'
09:11:37.333565 git.c:344               trace: built-in: git 'send-pack' '--stateless-rpc' '--helper-status' '--thin' '--progress' 'https://github.com/blackpandastudios/VR-Locomotion-Essentials.git/' '--stdin'
09:11:37.335552 run-command.c:626       trace: run_command: 'pack-objects' '--all-progress-implied' '--revs' '--stdout' '--thin' '--delta-base-offset' '--progress'
09:11:37.344527 git.c:344               trace: built-in: git 'pack-objects' '--all-progress-implied' '--revs' '--stdout' '--thin' '--delta-base-offset' '--progress'
Counting objects: 11, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (10/10), done.
Writing objects: 100% (11/11), 910 bytes | 910.00 KiB/s, done.
Total 11 (delta 8), reused 0 (delta 0)
remote: Resolving deltas: 100% (8/8), completed with 8 local objects.
To https://github.com/blackpandastudios/VR-Locomotion-Essentials.git
   2caa472..c411c67  master -> master

**Comment by blackpandastudios** [comment]
Sorry for the lack of formatting! 

seems to be after git-credential-manager. But I know for a fact I was logged in correctly through unity as I created the repo from within git for unity. The stored git user and pw however could be causing this though right? because cmd defaults to my work github acc, so every push I do to these repo's result in me re-entering username and pw.

**Comment by StanleyGoldman** [comment]
Hey @blackpandastudios the latest release fixed up a few things with authentication.
I'm hoping the latest release will resolve these issues for you.

I'm gonna close up this issue for now.
If you are still having trouble don't hesitate to reopen it.

**Comment by StanleyGoldman** [comment]
>I'm also working on 2 different accounts on GitHub

Also, this will be a problem. Credentials are definitely shared, you will always have to switch accounts.
