### ISSUE TITLE
Editing a file locked by another user should issue a warning

### ISSUE THREAD

**Issue by shana** [github-for-unity/Unity#858]
Editing a file that's locked by another user should be issuing a warning, feels like this is broken in some way.

Also, on a wider note, it should also warn at commit time, if the user modified the file outside of Unity (or something else made the warning not show up)

**Comment by SamuHell** [comment]
Totally agree, it's a bit heart breaking right now that you made changes to a scene for hours only to realize someone else has locked the file and you need to revert your changes.
An error showing the asset is locked should appear as soon as you try to save the asset (best scenario would be preventing the edition of the asset and having an "offline" mode in the case someone doesn't care it's locked)

**Comment by AgentOttsel** [comment]
Do we have any updates on this? It's the main thing stopping my team at work from using GitHub for Unity.
(For some reason, posting this comment caused someone to be unassigned... I'm not sure if that was supposed to happen)

**Comment by shana** [comment]
@AgentOttsel This is going to get fixed as part of moving the core functionality of this plugin to a package and having Unity expose more APIs to it, over the next 3 to 4 months. The work for that is happening at https://github.com/Unity-Technologies/Git-for-Unity.
