### ISSUE TITLE
Push ALWAYS disabled

### ISSUE THREAD

**Issue by colabi** [github-for-unity/Unity#864]
### Prerequisites

- Be sure to run with tracing enabled to capture runtime details in the log file
- Include the log file in the PR.
  - On Windows, the extension log file is at `%LOCALAPPDATA%\GitHubUnity\github-unity.log`
  - On macOS, the extension log file is at `~/Library/Logs/GitHubUnity/github-unity.log`

### Description

No matter what I do, PUSH is never enabled in the ui

### Steps to Reproduce

Instructions followed from web page.
Login successful and id indicated in UI.  Git repo create, public and access through regular CLI git confirmed.  Changes indicated in history.  Commits made.  However PUSH is never enabled.

**Expected behavior:** [What you expect to happen]

I'd expect to be able to push

**Actual behavior:** [What actually happens]

Always grayed out

**Reproduces how often:** [What percentage of the time does it reproduce?]

Always

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by colabi** [comment]
[github-unity.log](https://github.com/github-for-unity/Unity/files/2180606/github-unity.log)

**Comment by colabi** [comment]
These were the instructions I followed from the GitHub for Unity page.

DONE Go to github.com and create a new empty repository - do not add a license, readme or other files during the creation process.
DONE Copy the https URL shown in the creation page
DONE In Unity, go to Windows -> GitHub -> Settings and paste the url into the Remote textbox.
DONE Click Save repository.

Unfortunately, Push is just never enabled.
Go to the History tab and click Push.

**Comment by StanleyGoldman** [comment]
Hey @colabi 

So you know for next time. The process would be simpler if you use the Publish button in GitHub for Unity. It will create the repo for you, set the remote, and push your master branch.

![image](https://user-images.githubusercontent.com/417571/42520527-708d9452-8434-11e8-8dc3-ad69bf14cab9.png)

That said... You've already created the repo manually. So let's just get this working.

I'm going to assume you did the setup on the client side correctly (copying the correct url and pasting it into the right spot). 

 So let's try to push your branch and track it...
1. With GitHub for Unity open the Command Line, by going to `Window > GitHub Command Line`
2. Type the following `git push -u origin master`

That should push and track your master branch.
After you make more commits the push button should be enabled correctly.

If you want to push a branch other than master. Be sure to push and track it once manually with: `git push -u origin [name of branch]`.

After the next release (should be this week) that bug will be fixed.

**Comment by colabi** [comment]
i'm a fan of going with least resistance.  and this project can start with publish (may be good to reflect in official docs?)

however, trying the publish route brings up a dialogue like this:

![github_unity_publish](https://user-images.githubusercontent.com/2132341/42521304-50fd616a-841d-11e8-8da7-a2e0f5eb2342.png)

However, clicking on the *select user or org* dropdown reveals no selections.  However, the UI does reflect that I'm logged in.  In the log file there is an error that says: 

Error Getting Organizations

Included is the log as well:

[github-unity.log](https://github.com/github-for-unity/Unity/files/2181096/github-unity.log)

**Comment by colabi** [comment]
Just wanted to check in.  Is Error Getting Organizations and no ability to select an owner a bug?

**Comment by StanleyGoldman** [comment]
Sorry I dropped off yesterday, had other things to tackle.
And for sure, that's a bug.

We just pushed out a release yesterday.
If you can give that release a shot, and I will look more into your issue in a bit.

**Comment by colabi** [comment]
Thanks!  Will check out the new release

**Comment by colabi** [comment]
looks like i already was on 1.0.0.4809 (latest build?).

**Comment by StanleyGoldman** [comment]
`1.0.1.4860` is the latest.

**Comment by StanleyGoldman** [comment]
Hey @colabi are you able to reproduce the "Error Getting Organizations" bug with the latest version?

**Comment by StanleyGoldman** [comment]
Hey @colabi I'm gonna close this issue for now.
If you are still experiencing an issue publishing, please open a new issue.

**Comment by JoseLu1200** [comment]
Hi, this is happening to me too, I can only push changes if I create a new branch every time I want to do it.
