### ISSUE TITLE
Buttons too small in Unity 2018.2 w/ High DPI

### ISSUE THREAD

**Issue by GriffinBrodman** [github-for-unity/Unity#867]
Due to Unity 2018.2's high DPI support, these buttons are no longer wide enough to fit in one row.

![github bug](https://user-images.githubusercontent.com/5846636/42708087-218ab024-86aa-11e8-9ab6-351f74e78078.PNG)

**Comment by GriffinBrodman** [comment]
To note, it can happen on any of the four buttons in that row

**Comment by amputek** [comment]
+1. This is happening for me on a 2560x1440 monitor.

**Comment by StanleyGoldman** [comment]
Thanks for reporting the bug guys. We hope to get Better 2018.2 support soon.

**Comment by StanleyGoldman** [comment]
@CapnRat would you say this is related to #17

**Comment by StanleyGoldman** [comment]
![](https://i.imgur.com/jusuDcP.gif)

**Comment by StanleyGoldman** [comment]
LOL, would you believe it was word wrapping?

**Comment by GriffinBrodman** [comment]
Nice!
