### ISSUE TITLE
Release Notes

### ISSUE THREAD

**Issue by aproctor** [github-for-unity/Unity#869]
### Description
It'd be really nice if there were high level release notes available.  I was recently prompted in editor to upgrade but had to dig quite a bit to see what has changed.

I was able to compare tags, though I'm not sure how many people are familiar enough with GitHub to do that on their own, and it'd probably be helpful to have a high level description of the changes in a markdown file.

### Example
https://github.com/github/octodns/blob/master/CHANGELOG.md

**Comment by shana** [comment]
@aproctor You should be able to see the same release notes that are shown in the release page here: https://github.com/github-for-unity/Unity/releases/tag/v1.0.1, but it looks like the release feed got borked and the information is missing there. Thanks for the heads up, will fix (and sorry for the missing info)!
