### ISSUE TITLE
Cannot be used on Project that is using ECS on 2018.2

### ISSUE THREAD

**Issue by RotaryHeart** [github-for-unity/Unity#870]
### Description

When used on a project with ECS there are errors on the console about conflicting .dll imports. Here's an example of what is displayed.

error CS0433:
The type 'SpinLock' exists in both 'System.Threading, Version=1.0.3333.0, Culture=neutral, PublicKeyToken=402899b480e6f383' and 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'

There are multiple more errors like this one. Log file is empty since the editor doesn't allow to finish compilation.

### Steps to Reproduce

1. Create a Project using 2018.2
2. Do all the needed steps to enable ECS
3. Import GitHub for Unity package

**Reproduces how often:**
Tested with 2 different computers and it happens as soon as the package is imported.

**Comment by shana** [comment]
@RotaryHeart thanks for the report. Yes, this is a problem, the same as in #824. I'm working on a fix for this, I'm hoping I can get a release out next week with it.
