### ISSUE TITLE
Plug-in starts with wrong repo initialized

### ISSUE THREAD

**Issue by rjcarney** [github-for-unity/Unity#872]
### Description

Upon loading the GitHub-for-Unity plugin and logging in a previous GitHub repository on my profile was loaded into the plugin, instead of presenting the opportunity to initialize 
a new repository.

### Steps to Reproduce

1. Download and import GitHub For Unity Plugin through unity asset store
2. Open GitHub plugin window in the unity inspector
3. Sign into GitHub through inspector
4. Previous repository is loaded into plugin settings

**Expected behavior:** Upon signing in there will be a box under the change tab marked initialize that will allow me to create a GitHub repository through my unity project.

**Actual behavior:** Plugin load a previous GitHub repository and does not allow for any push

**Reproduces how often:** 100%

### Additional Information

 I have tried deleting all .git files from my root folder and deleting the plugin from the project and re-importing and the problem reoccurs.

**Comment by StanleyGoldman** [comment]
Hey @rjcarney sorry we've been MIA for a bit. It's been busy around here.
So I've seen this kind of error before, and usually there is a git folder in your parent directory somewhere.

If you can still reproduce this error, please try the follow.
1. Open a git command line window `Window > GitHub Command Line`
1. Run the following command `git rev-parse --show-toplevel`

That command will show you the top level directory of the git folder, if I understand your problem correctly, if your project is in `C:\Projects\UnityProject` I think you will find that there is a git database at `c:\Programs`.

Let me know if that helps you
-Stanley

**Comment by StanleyGoldman** [comment]
Hey @rjcarney I'm going to close out this issue for now. If you are able to perform the test I indicated let mek now. If you are still having a problem feel free to reopen this issue.
