### ISSUE TITLE
Project view is slow to update

### ISSUE THREAD

**Issue by meaghanlewis** [github-for-unity/Unity#882]
### Steps to Reproduce

1. Create and checkout a new branch
2. Create a new asset (script, scene, etc)
3. Commit and push
4. Checkout master branch

**Expected behavior:** 
The asset I just committed on another branch should not be there

**Actual behavior:** 
The asset I just committed shows up on the master branch and the view takes about 1 minute to update.

This same behavior exists for any branch that I switch to- initially the files specific to that branch do not appear but show up eventually.

**Reproduces how often:** 
100

I'm not sure if this behavior can be improved, but it was really confusing me earlier and I imagine it might be to other users as well.

**Comment by StanleyGoldman** [comment]
I've got a fix for this coming soon.
