### ISSUE TITLE
GitClient.Remove() should spool list of files

### ISSUE THREAD

**Issue by StanleyGoldman** [github-for-unity/Unity#887]
The `GitClient.Remove(...)` task takes a list of files as input and does not spool the entries like other `GitClient` operations that take a list of files.

This can lead to a bug where attempting to remove too many files from the index will fail.

**Comment by KonH** [comment]
Hello! I made pull request with proposed changes, can you please take a look?
https://github.com/github-for-unity/Unity/pull/905
