### ISSUE TITLE
Connecting to existing repository is unexplained

### ISSUE THREAD

**Issue by dragonfyre23** [github-for-unity/Unity#891]
Part question part issue:
getting-started.md has a header at the end which has no content
I would love to know how to connect to a repo from a new machine. Cheers!

**Comment by f-wende** [comment]
Is this even possible right now? I am somehow unable to get this work.

**Comment by StanleyGoldman** [comment]
Does that solve the problem for you @f-wende or @dragonfyre23?

**Comment by dragonfyre23** [comment]
I haven't gotten a chance to test yet. Which tools are you referring to? Just downloading the project, removing the plugin by deleting the directory and opening it in unity?

**Comment by StanleyGoldman** [comment]
Hey @dragonfyre23 , okay, maybe I'm making too many assumptions.

1. Is the project on GitHub.com?
2. Does the project already have GitHub for Unity installed?

**Comment by dragonfyre23** [comment]
You assume correctly.
I created the project in Unity, added the GitHub for Unity plugin, then initialized a repo within unity through use of the plugin. 
Next, I created a new empty repository on GitHub.com and copied the https link. I pasted that into the plugin’s remote origin field and saved the link. After making several commits and pushes everything works flawlessly.

My question arose when I tried to access the project from a different machine. What is the proper workflow for this? Should I clone the repository from GitHub.com? or should I make an empty project in Unity first(adding the plugin later). Cheers and thanks for the quick responses.

PS I’m happy to add the documentation once I figure it out.

**Comment by StanleyGoldman** [comment]
So yea, exactly like I was saying before, we don't have a clone function yet.
The best suggestion we can make is to use GitHub Desktop to clone your project.
After you have it local, just open it with Unity and everything should work as normal.
GitHub for Unity will download any additional pieces it needs on that computer to set itself up.

P.S. I appreciate you adding the documentation. 🎖

**Comment by StanleyGoldman** [comment]
https://desktop.github.com/

**Comment by dragonfyre23** [comment]
The above steps worked for me.
Clone project, Open in unity. I did encounter an error when pushing changes but it seems unrelated. All the same, I will post it here then close the issue so that anyone else encountering it can connect the dots. I was able to workaround by pushing through GitHub Desktop instead of the plugin.

Fatal: HttpRequestException encountered.
bash: /dev/tty: No such device or address
error: failed to execute prompt script (exit code 1)
fatal: could not read Username for 'https://github.com': Invalid argument

I double checked my credentials and remote: origin https url as well as my system git installation location. Not sure what to think about that but I'm satisfied with the workaround for now. Cheers and thanks for the help!

**Comment by chubillkelvin** [comment]
@StanleyGoldman Hello from 2019. I just started to use Github for Unity and I still struggled to connect to an existing repository after reading from the documentation. I find this thread extremely useful in helping me to connect to an existing project (it was not obvious to me that as simple as using GitHub Desktop would be the solution). Would you maybe consider writing a few sentences on the getting started guide or simply direct new users to this thread?
