### ISSUE TITLE
Can't sign in ("Login failed") and stuck on "Initialized"

### ISSUE THREAD

**Issue by EmmetOT** [github-for-unity/Unity#892]
Hello!

I'm just trying the GitHub plugin with Unity 2018.2.4, and the newest version of the plugin. 

The GitHub window's "Initialize" tab is displaying a rotating icon with the word "Initialized," but nothing else is happening. When I click the "Sign in" button in the top right of the window and try to sign in, my username and password gives me a "Login failed" message (as distinct from a "Bad credentials" message when I enter an incorrect password.)

**Comment by EmmetOT** [comment]
Seemed to just be a connectivity issue... Not sure why but it worked a few hours later.

**Comment by StanleyGoldman** [comment]
Okay, thanks for creating the issue.
Glad it worked for you in the end.
