### ISSUE TITLE
Unity database not refreshed after Pull

### ISSUE THREAD

**Issue by oboka** [github-for-unity/Unity#907]
### Description

After pulling some commits from remote server the unity database is not refreshed, so new files don't show in the editor until you change focus out and back to unity again.

### Steps to Reproduce

1. User1 create a new script
2. User1 commit and push to the server
3. User2 pull
4. the new script is not shown nor compiled
5. alt+tab, alt+tab and then the new script is incorporated to the assets DB.

**Expected behavior:** 
After pulling new code, it should be shown in the editor authomatically.

**Actual behavior:** 
New files are not shown.

**Reproduces how often:** 
Always

### Additional Information

Just calling:

AssetDatabase.Refresh();

After updating the files is enough.

**Comment by StanleyGoldman** [comment]
Hey @oboka thanks for trying our stuff out and reporting the issue.
Sorry it took so long to get back to you, I've been working on a few other projects lately.

I'm going to try to reproduce this myself? I'm going to try this myself soon.

**Comment by StanleyGoldman** [comment]
I've got a fix for this coming soon.

**Comment by LilMike808** [comment]
I don't know if this is the right place. I know this thread is years old, but I'm at my wits end. No experience with Unity. Signed up with a gamedev course. Everytime I switch branches in Gitbash, Unity will not recompile to new branch at all. Been stuck for days. Reset my newer laptop. Tried to do the same on my old one and the same happened so it's can't be an issue outside of unity and/or Gitbash. It seems I'm connected to the remote repository on GitHub. I pull, add new changes, commit then push just fine. But Unity is not at all receptive to commands. from Gitbash. I've had it switch branches briefly before. Anyone have any idea?
