### ISSUE TITLE
SharpZipLib MissingMethodException

### ISSUE THREAD

**Issue by Dreaddisk** [github-for-unity/Unity#908]
I've installed Github with Unity and imported it in my project. When I'm going to settings and go to the login window, I inserted my credentials but I'm unable to enter, it says that there is an error. I can't get into my Github account.

**Comment by StanleyGoldman** [comment]
Hey @Dreaddisk.

Thanks for trying our stuff out. Can you do me a favor?
Enable trace logging and then try again.
Post the log file here and we can start to take a look.

Also what version of GitHub for Unity, version of Unity, Windows/Mac, etc?

**Comment by urbannilsson** [comment]
Are you using the .NET 4.x? If you are, here is a workaround that worked for me.

- Change to .NET 3.5
- Install the github-for-unity package
- Try to sign in

After signing in you can switch back to .NET 4.x if you want.

Windows 10
Unity 2018.3.0b2 (64-bit)
GitHub for Unity 1.0.3

**Comment by StanleyGoldman** [comment]
Hey @Dreaddisk @inwoods we've confirmed the cause of this issue. We should be able to fix it soon.
Thanks for your hint @urbannilsson.

**Comment by sguthals** [comment]
Testing:
- Download Unity 2018.1.3
- remove octorun from your AppData folder
- open a new project and install
