### ISSUE TITLE
Committing new file by selecting its meta file does not commit the file itself

### ISSUE THREAD

**Issue by LEV3LGames** [github-for-unity/Unity#913]
### Prerequisites
Tracing enabled, log file attached (but not much to see in it).
[github-unity.log](https://github.com/github-for-unity/Unity/files/2398910/github-unity.log)

### Description

When a new file is created, and the file is marked to be committed by selecting its meta file, the file itself will not be committed, even though the tree view shows it as also selected.

### Steps to Reproduce

1. Initialize GitHub for Unity, and a git repository
2. Create any new file in the project.
3. In the GitHub for Unity window click on the meta file of the newly created file. Notice that the newly created file is also marked as selected, as the meta file is a dependency of it.
4. Add commit message, and click on commit.

**Expected behavior:** All the files from the GitHub window that have their checkbox ticked in the tree view are (staged and) committed.

**Actual behavior:** Only the meta file is committed, without the file for which it was created.

**Reproduces how often:** 100% (Always)

### Additional Information
See attached "empty" Unity project, already in inconsistent state. Follow instructions to reproduce issue.
[GitCommitIssue.zip](https://github.com/github-for-unity/Unity/files/2398940/GitCommitIssue.zip)

Unity version is 2018.2.0f2, GitHub for Unity version is latest on Asset Store as of 2018-09-20.

It is probably a UI issue, inconsistency between what the UI logic shows and the list of files to be committed.

**Comment by StanleyGoldman** [comment]
Hey @LEV3LGames thanks for the bug report.

Sorry it's taken so long, been busy with a few other projects.
I can confirm the bug and should be able to wrap it up quickly.

**Comment by StanleyGoldman** [comment]
Fixed up. Should be good to go in the next release.
Thanks.

**Comment by LEV3LGames** [comment]
Great! Thanks for the fix! :+1:
