### ISSUE TITLE
Audit Dispose pattern in the codebase and add it to the style guide for reference

### ISSUE THREAD

**Issue by shana** [github-for-unity/Unity#93]
We should add the Dispose pattern to the style guide so we don't have to go hunting for it whenever we need it. We should also audit the existing code to make sure it follows the correct pattern where it needs to.

```
private bool disposed;
public virtual void Dispose(bool disposing)
{
    if (disposed) return;
    disposed = true;
    if (disposing) {
        // dispose managed stuff
    }
    // dispose native stuff that we hold an exclusive reference to (nobody else is going to kill them off via GC or finalizer). Do not access any data via managed references here.
}

public void Dispose()
{
  Dispose(true);
}
```

**Comment by AkashGutha** [comment]
I'll do this.

where is the style guide? I'm unable to find it.

**Comment by Frozenfire92** [comment]
@AkashGutha https://github.com/github-for-unity/Unity/blob/master/docs/contributing/styleguide.md

**Comment by shana** [comment]
Oh wow I totally forgot about this, thanks @Frozenfire92

**Comment by MariaAp80** [comment]
GitHub utilitário in developmente and Support for unity the blob máster.
