### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by DevCas1** [github-for-unity/Unity#938]
### Prerequisites

- Be sure to run with tracing enabled to capture runtime details in the log file
- Include the log file in the PR.
  - On Windows, the extension log file is at `%LOCALAPPDATA%\GitHubUnity\github-unity.log`
  - On macOS, the extension log file is at `~/Library/Logs/GitHubUnity/github-unity.log`

### Steps to Reproduce

1. Installed Github for Unity from Github
2. Imported asset pack in project
3. Clicked Sign in in the upper right corner of the GitHub window
4. Entered credentials, and received a 'Login failed' error

**Expected behavior:** GitHub for Unity to ask me for a 2FA code

**Actual behavior:** It gave an error stating it was a 'Login failed'

**Reproduces how often:** All the time

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

- Running Unity 2018.2.11f1 Personal with the Unity 3D Gamekit installed
[github-unity.log](https://github.com/github-for-unity/Unity/files/2465498/github-unity.log)

**Comment by StanleyGoldman** [comment]
Hey @DevCas1 thanks for testing our stuff out.
Looking at your error you are getting this...

```
GitHub.Unity.UnzipException: Error unzipping file ---> System.MissingMethodException: long ICSharpCode.SharpZipLib.Zip.ZipFile.get_Count()
  at GitHub.Unity.UnzipTask.RunUnzip (System.Boolean success) [0x0004b] in C:\Users\Spade\Projects\GitHub\Unity\src\GitHub.Api\Installer\UnzipTask.cs:58 
   --- End of inner exception stack trace ---
  at GitHub.Unity.UnzipTask.RunUnzip (System.Boolean success) [0x000ed] in C:\Users\Spade\Projects\GitHub\Unity\src\GitHub.Api\Installer\UnzipTask.cs:83 
  at GitHub.Unity.UnzipTask.RunWithReturn (System.Boolean success) [0x00008] in C:\Users\Spade\Projects\GitHub\Unity\src\GitHub.Api\Installer\UnzipTask.cs:34 
System.MissingMethodException: long ICSharpCode.SharpZipLib.Zip.ZipFile.get_Count()
  at GitHub.Unity.UnzipTask.RunUnzip (System.Boolean success) [0x0004b] in 
```

Which I actually just fixed yesterday.
See #908 and #928.

I should be releasing a new version today or tomorrow.
You should be good to go from there.

What you can try in the meantime:
1. Open up a new blank project
2. Make sure it is using the 3.5 runtime
3. Install GitHub for Unity and login
4. Close up this project and go back to your normal project

You should be good to go from there too.
Let me know if you have any other problems.
