### ISSUE TITLE
2FA still not working on Unity 2018.2.11f1 with .NET 4.x

### ISSUE THREAD

**Issue by DevCas1** [github-for-unity/Unity#940]
### Prerequisites

- Be sure to run with tracing enabled to capture runtime details in the log file
- Include the log file in the PR.
  - On Windows, the extension log file is at `%LOCALAPPDATA%\GitHubUnity\github-unity.log`
  - On macOS, the extension log file is at `~/Library/Logs/GitHubUnity/github-unity.log`

### Description

When logging in, GitHub for Unity asks me for a 2FA code, which dutifully arrives by SMS on my phone. When I enter the code, though, it says 'Login failed', just like with the previous release (1.0.3 - something with robots)...
Hoped updating to the newest release would fix this, but it seems like it didn't...

### Steps to Reproduce

1. Import GitHub for Unity in a blank project in Unity 2018.2.11f1 with the .NET 4.x runtime and IL2CPP set
2. Try to login to GitHub in the GitHub window
3. Witness that beautiful error

**Expected behavior:** GitHub for Unity to login to my account after entering the 2FA code that arrives on my phone (not though any authentication app, like it says it will)

**Actual behavior:** It gives a 'Login failed' error

**Reproduces how often:** All the time (except for when it's done in an empty project with .NET 3.5

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

- GitHub for Unity log: 
[github-unity.log](https://github.com/github-for-unity/Unity/files/2469941/github-unity.log)

**Comment by StanleyGoldman** [comment]
Hey @DevCas1 thanks for testing this out again.
Good news is it's not stuck at the same place as last time. 😆 😞

**Comment by DevCas1** [comment]
Anything I can help with? Be glad to help!

**Comment by StanleyGoldman** [comment]
Hey @DevCas1 if you would like to start debugging the issue, that would be great. I'm busy working on #2 at the moment. If you come up with some details I can definitely coach you through fixing it.

_(I'm also not above bribery and I have a swag account)_

**Comment by StanleyGoldman** [comment]
Hey @DevCas1 sorry I've left you hanging for so long. Are you still having this problem?

**Comment by DevCas1** [comment]
Hey @StanleyGoldman I've made a new repo, tried the version currently in the store (version 1.1.1), and everything works just as it should!
Perhaps it's something with that perticular repo, perhaps it was the version of Unity (currently use 2018.3.0f2), but everything works fine now!
I'll close this issue, because for me it does not exist anymore. If I do run into it again, I'll try to look into it more actively. Can't be that I'm the only one who has this issue.

**Comment by StanleyGoldman** [comment]
Thanks @DevCas1. I'm happy it all worked out.
