### ISSUE TITLE
Is UnityYAMLMerge actually being used?

### ISSUE THREAD

**Issue by Piotr-B** [github-for-unity/Unity#943]
### Description

While investigating using this plugin for our next project I noticed that the UnityYAMLMerge tool seems to get configured for use but never actually gets launched.

When creating a project with the plugin the following configuration options get set:

_.gitattributes_:
```
# Unity files
*.meta -text merge=unityamlmerge diff
*.unity -text merge=unityamlmerge diff
*.asset -text merge=unityamlmerge diff
*.prefab -text merge=unityamlmerge diff
```

_.git/config_:
```
[merge "unityyamlmerge"]
	cmd = 'C:\\Program Files\\Unity 2018.1.1f1\\Editor\\Data\\Tools\\UnityYAMLMerge.exe' merge -p $BASE $REMOTE $LOCAL $MERGED
	trustExitCode = false
```

This looks well and good but:
- Attributes file misspells the tool as "unityamlmerge" (note the missing "y").
- Config file doesn't misspell the tool name.
- Even if the names did match the tool still wouldn't run because the `merge` attribute looks for a custom low-level merge driver in the config file in the following format:
```
[merge "mergeDriverName"]
	name = Human-readable name
	driver = mergeDriverExecutable %O %A %B %L %P
	recursive = binary
```
- The config file as is uses the **custom merge driver** header `[merge "unityyamlmerge"]` but **external merge tool** fields: `cmd =` `trustExitCode =`. These are different things but appear to be mixed here. A `mergetool` section is supposed to look like this:
```
[mergetool "extMerge"]
  cmd = extMerge "$BASE" "$LOCAL" "$REMOTE" "$MERGED"
  trustExitCode = false
```
But for that to work it also requires this entry, which is missing:
```
[merge]
  tool = extMerge
```
And I think that would launch the tool for all file types not just the select ones.

**Disclaimer:**
I'm not very proficient in git so I might be missing something here but this is what it looks like to me after investigating the code and docs.

I'm using **GitHub for Unity 1.1.0** and **Unity 2018.1.1f1**.

### References

https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration#_external_merge_tools
https://git-scm.com/docs/gitattributes#_defining_a_custom_merge_driver
https://git-scm.com/docs/git-config#git-config-mergetool
https://docs.unity3d.com/Manual/SmartMerge.html

https://github.com/github-for-unity/Unity/blob/1c53148a39f81d3146b3843eab21efef16115306/src/GitHub.Api/Resources/.gitattributes#L3-L7

https://github.com/github-for-unity/Unity/blob/1c53148a39f81d3146b3843eab21efef16115306/src/GitHub.Api/Application/ApplicationManagerBase.cs#L291-L299

**Comment by fabiopolimeni** [comment]
Hi guys, I would like to start using GitHub for Unity for our next project, and this bug sounds pretty important to me. At what point you honestly are with this? 

Thanks,
Fabio

**Comment by StanleyGoldman** [comment]
Hey @fabiopolimeni thanks for checking our stuff out.
Sorry, we are a bit behind with things. Shana and I have a few different projects we maintain.
We are planning a release in December and this bug should be fixed in that release.
