### ISSUE TITLE
allow users to disable git lfs easily through GUI

### ISSUE THREAD

**Issue by SupraLP** [github-for-unity/Unity#944]
currently if you don't want to use LFS you have to delete the file ".git/hooks/pre-push" - at least thats what my push error message said. 
Disabling LFS should be made easier and possible through the GUI.

EDIT: Deleting that file is not enough, but I need to get rid of that LFS, it just produces errors.
EDIT2: ok, seems like you are not supposed to work without git LFS...

**Comment by StanleyGoldman** [comment]
Hey @SupraLP ... Yea, files in Unity tend to be larger and rather... well... binary. Which git is not very good at. Which is why Git LFS was created.

**Comment by StanleyGoldman** [comment]
You can choose what files are tracked, btw.
