### ISSUE TITLE
GitHub errors in logs and tabs are constantly spinning

### ISSUE THREAD

**Issue by nukeustwo** [github-for-unity/Unity#946]
### Prerequisites

- Be sure to run with tracing enabled to capture runtime details in the log file
- Include the log file in the PR.
  - On Windows, the extension log file is at `%LOCALAPPDATA%\GitHubUnity\github-unity.log`
  - On macOS, the extension log file is at `~/Library/Logs/GitHubUnity/github-unity.log`

### Description

After launching unity the GitHub plugin never displays any data on any of the changes/locks/history/branches tabs, the spinning icon just spins forever.

However if I manually go to settings and click either 'use system git' or 'use bundled git' then I can see some tasks on the status bar successfully work, but the tabs still display the spinning graphic forever

### Steps to Reproduce

1. Open Unity
2. Observer the plugin tabs spinning forever

**Reproduces how often:** 100%

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.
[github-unity.log](https://github.com/github-for-unity/Unity/files/2518347/github-unity.log)

**Comment by StanleyGoldman** [comment]
Hey @nukeustwo thanks for testing our stuff and glad you figured it out.

I expected this issue some, but I didn't know it was happening on Macs as well.
There are release notes in the last release to delete the `GitHubUnity/octorun` folder.
It's okay if you deleted more than that.

I'll update the notes for mac users also.

Thanks for the feedback.
