### ISSUE TITLE
Checkout a specific version of a file(s)

### ISSUE THREAD

**Issue by sambonfire** [github-for-unity/Unity#947]
This is a feature request.  I'd like the client to support checking out a set of files at a specific changeset.

This is the equivalent of the command:

`git checkout <changset> -- <list of files>`

**Comment by StanleyGoldman** [comment]
Hey @sambonfire. This is another one for the figuring out.

**Comment by sambonfire** [comment]
Similar to my last comment, it would be wonderful if we could just start integrating these into the client API so we can use it in our workflows that we are designing.

**Comment by StanleyGoldman** [comment]
Hey @sambonfire same from me again. If you can start it I will chip in and help.

**Comment by StanleyGoldman** [comment]
Implemented in #999
