### ISSUE TITLE
History of a single file

### ISSUE THREAD

**Issue by sambonfire** [github-for-unity/Unity#948]
I'd like to be able to use the client to view the history of a single file; ie:

`git log -- <file>`

**Comment by StanleyGoldman** [comment]
Hey @sambonfire. Thanks for checking our stuff out.
Yep. We definitely would like to get to all these smaller git features. Half the problem is figuring out how to put it in the UI without being an eyesore. We'll update this issue when we start to give it a shot.

**Comment by sambonfire** [comment]
It would be wonderful if we could just start integrating these into the client API.  We're designing a workflow a bit different than what you guys have envisioned for the plugin, but we'd really like to share the same API layer.  Hopefully we could just add these to the API without worrying about UX immediately?

**Comment by StanleyGoldman** [comment]
Hey @sambonfire that is a reasonable request.

When I get some time I can give it a shot, but I'm working on quite a few different projects at the same time.

If you don't getting it started. I will definitely help you get it done and :shipit:.
I will even send you a tshirt and some stickers for your effort. _**(I am not above bribery)**_ 😄

We have documentation on getting started with building the project.
If you have any questions ask away and I'll get back to you.

**Comment by sambonfire** [comment]
I'm totally not above bribery either! :)

I wasn't able to get the code to build and pass tests on my mac; i'll give it a shot on my windows box.  expect a PR.

**Comment by StanleyGoldman** [comment]
If you wanna set aside 30 minutes or so, I don't mind giving you a tour of the things you'd need to change to get what you want. I'm in EST.

**Comment by StanleyGoldman** [comment]
Implemented in #999
