### ISSUE TITLE
Users should be prompted to lock files

### ISSUE THREAD

**Issue by Ecnassianer** [github-for-unity/Unity#949]
I'm evaluating using GitHub For Unity. From what I can tell, it looks like you can edit an LFS tracked file even if you don't have the lock, and save that out and commit it. If someone else has the lock that whole time, you only realize you're screwed when you go to push.

Is there any way to enforce having the lock in order to edit an LFS tracked file?

**Comment by Ecnassianer** [comment]
I would be happy with a prompt when you go to edit the file, giving you the choice to request the lock before you edit. Or a warning that you're editing an unlocked file. My dream case it is just gets the lock and only notifies me if it fails to grab the lock.

**Comment by StanleyGoldman** [comment]
Hey @Ecnassianer that's a decent request. I was going to start looking at #858. This request seems to fit the same vein of thinking.

**Comment by Ecnassianer** [comment]
Great, I'm glad you're adding it! This is super important for our workflow! :)

**Comment by StanleyGoldman** [comment]
Hey @Ecnassianer I was thinking about implementing this today, but i faltered when I tried to define what files should be prompted for locking. We could just go by the `.gitattributes` file, but LFS Locking can apply to any file in the repository, not just the LFS tracked ones. What do you think?

**Comment by Ecnassianer** [comment]
I think think the .gitattributes is more indicative of what files SHOULD be locked. Though maybe this should be a config option? Give me a few minutes to do some research and I'll answer more.

**Comment by StanleyGoldman** [comment]
Don't get me wrong. The gitattributes file is a good place for starters. I just realized while trying to rubber duck this to someone else that I was unable to definitively explain what files should be prompted for locking.

**Comment by Ecnassianer** [comment]
Ok, I found something in the documentation that's helpful. From here:
https://github.com/git-lfs/git-lfs/wiki/File-Locking

> Once file patterns in .gitattributes are lockable, Git LFS will make them readonly on the local file system automatically. This prevents users from accidentally editing a file without locking it first.

This says to me that the "lockable" attribute is primarily intended for preventing users from editing **files that should be locked before editing**. That's the point of marking them readonly on the local file system. By extension, if a file type _doesn't_ have the lockable attribute, then it is _safe to edit without locking_.

So I'm pretty sure the default behavior should be to prompt for locks only for files that have the lockable attribute. You can still lock any file in the depot, but the default behavior is to edit it without a lock.

**Comment by Ecnassianer** [comment]
Awesome, thanks for the details shana! :D

**Comment by Ecnassianer** [comment]
Any updates on this bug? I'd like to try GitHub For Unity again, but it's not very useful to me if it doesn't prompt for locks.

**Comment by StanleyGoldman** [comment]
Unfortunately I'm spinning a few plates by myself at the moment.
This is on my radar but not being worked on as of yet.
