### ISSUE TITLE
"Login Failed"

### ISSUE THREAD

**Issue by emgillis** [github-for-unity/Unity#950]
### Prerequisites
- Be sure to run with tracing enabled to capture runtime details in the log file
   *--> I'm not 100% sure how to do this_*
- Included log file.
  - MacOS extension log file is at `~/Library/Logs/GitHubUnity/github-unity.log`

### Description

I'm attaching my github-unity.log. I'm very new to GitHub for Unity, and somewhat new to Git & GitHub. I have attempted reinstalling and even creating a new Unity Project on off chance it was project related. I also tried both  my GitHub username and my registered email address with GitHub, but it 

---
### Steps to Reproduce

1. Installed GitHub for Unity for my project
2. Launched GitHub for Unity window
3. Attempted to log in, and get login failed

**Expected behavior:**
Expected to be able to log in and connect to my GitHub account.

**Actual behavior:**
Fails to connect to my GitHub account

**Reproduces how often:**
Always. Cannot log in to my GitHub account via GitHub for Unity

**Comment by emgillis** [comment]
[github-unity.log](https://github.com/github-for-unity/Unity/files/2538948/github-unity.log)

**Comment by LuckierDodge** [comment]
Also seeing this behavior on Windows in the latest LTS release of Unity 2017. Note that the error is distinct from incorrect login info, which yields a "Bad Credentials" error. Also will note that the Settings page appears to forget my Name and email after setting them. Tried finding my system git as well, to no effect.

Log file:
[github-unity.log](https://github.com/github-for-unity/Unity/files/2540003/github-unity.log)

**Comment by LuckierDodge** [comment]
Okay, I was able to get this working, on my machine, so @emgillis this might work for you. I deleted the original project, and created a new one with the same name from Unity Hub. I made sure to select GitHub for Unity from the initial assets tooling, and I was already signed in when I opened the GitHub pane.

**Comment by StanleyGoldman** [comment]
Hey @emgillis and @LuckierDodge thanks for testing our stuff out.
Looking at your errors it seems like you guys had different problems around the same point of startup.

@emgillis I'm seeing that you are on a mac and that we are having trouble finding `git`. For mac's we need you to have git installed as we don't bundle git for mac. Can you install git and give it another try?

@LuckierDodge you are on windows, and it seems like the git that we extract and setup didn't extract completely. But it sounds like everything is working for you now... is that true?

**Comment by AlexEnchanter** [comment]
I have the same problem, I tried logging in but i get the error message "Login failed". I tried  switching unity versions, did not work   

 
[github-unity.log](https://github.com/github-for-unity/Unity/files/2566208/github-unity.log)

**Comment by StanleyGoldman** [comment]
Hey @AlexEnchanter sorry it took so long to get back to you.
Your error looks exactly the same as @emgillis

**Comment by StanleyGoldman** [comment]
While Unity is not running.
1. Delete if exists `C:\ProgramData\GitHubUnity\systemsettings.json`
2. Delete if exists `%USERPROFILE%\AppData\Local\GitHubUnity\git`
3. Delete if exists `%USERPROFILE%\AppData\Local\GitHubUnity\git-lfs`
4. Restart the project with GitHub for Unity.

That will force GitHub for Unity to extract git and gitlfs for you again.
Hopefully that fixes the problem.

**Comment by stanishev** [comment]
This issue happens for me too, consistently. 
I am on ubuntu 18.04 with unity 2019.1.0a12
For what it's worth, if I provide invalid credentials I get an error saying "Bad Credentials"
If I provide the correct credentials, I get: "Login Failed"

**Comment by firebaugh** [comment]
Same issue here as @stanishev 
I get "Login Failed" using Unity 2018.2.3f1 on Ubuntu 18.04.1 LTS
Please find log file attached
[github-unity.log](https://github.com/github-for-unity/Unity/files/2770700/github-unity.log)

**Comment by kmcdowelljr** [comment]
Save isssue, with attempting to login.  I downgraded to 1.2 to see if that would it.. but the same issue.
[github-unity.log](https://github.com/github-for-unity/Unity/files/2824556/github-unity.log)

Using Ubuntu 18.04 LTS and Unity 2018.2.3f1, I am unable to login into my Github account

**Comment by StanleyGoldman** [comment]
Hey @stanishev @firebaugh @kmcdowelljr thanks for letting me know about this issue.
Sorry it's taking me a bit to get back to you. 🤹‍♂️ I juggle quite a few projects.

The error in this issue (for most users) was due to git missing, or configuration files getting messed up after an update. **(I'm going to close this issue, if anyone has any further problem with that please feel free to reopen it)**

These errors on Ubuntu are not the same as the original one that was posted here, but it is just as valid.
I'm going to create a new issue dedicated to your problem and tag you in it, since everyone else's issue was about something else entirely.
