### ISSUE TITLE
Discard doesn't work properly in some cases

### ISSUE THREAD

**Issue by AmitloafTotes** [github-for-unity/Unity#952]
### Description

Sometimes discard doesn't actually work even though it appears like it does.

### Steps to Reproduce

This is consistently recreated by using Unity Post Processing stack v.2 - Try to add a post process effect (like chromatic aberration for example). Save the scene. Discard everything from GitHub, notice that the new effect is still there.
When discarding from GitHub desktop it works properly.

**Comment by StanleyGoldman** [comment]
Hey @AmitloafTotes. Thanks for testing our stuff out. I will try to reproduce this issue and let you know how it goes.

**Comment by StanleyGoldman** [comment]
I experienced this myself recently.
Something about trying to discard a file while Unity is active.
