### ISSUE TITLE
Can't push after the initial commit ! always grayed out !

### ISSUE THREAD

**Issue by OkbaWest** [github-for-unity/Unity#953]
### Description
Hi!
I installed the plugin and everything, but it seems it doesn't push the project files to the remote.
using publish from within the UI , it successfully set up everything and create a repo, but none of the files is uploaded, only the assets folder with gitignore on it.
actually here it is: https://github.com/OkbaWest/ToonShader
tried with the command line like  git push -u origin master but nothing happened, it says it's up to date
Also, nothing shows up on the UI, like history and files changes, even if I delete or move files on the project folder.

### Steps to Reproduce

1. [First Step]
install the plug in
2. [Second Step]
try to publish/push

**Expected behavior:** [What you expect to happen]
Push the project to the repo, display the changes and history on the UI
**Actual behavior:** [What actually happens]
nothing happened beyond the creation of this 
**Reproduces how often:** [What percentage of the time does it reproduce?]
Always so far.

**Comment by glenpierce** [comment]
I suspect that this is related to https://github.com/github-for-unity/Unity/issues/871 the symptoms are very similar.

**Comment by StanleyGoldman** [comment]
Hey @OkbaWest I'm gonna close out this issue.
Feel free to re-open it, if you run into the problem again or have more information.
