### ISSUE TITLE
Add UPM package distribution option

### ISSUE THREAD

**Issue by tlaedre** [github-for-unity/Unity#962]
It would be great if there was a distribution option to get Github4Unity as a upm package. There's no real reason for the tool to live inside the Assets/ folder.

**Comment by nickmccurdy** [comment]
It's also confusing to have the plugin itself show up in changes, it has a lot of binary files that you wouldn't normally want to commit.

**Comment by nickmccurdy** [comment]
I recently reinstalled Unity to get the latest version and then installed the GitHub extension, and it shows up in changes every time I launch this Unity project.

**Comment by StanleyGoldman** [comment]
You should be free to commit the changes, that is the intention.
It shouldn't show up again after you commit it.

**Comment by JoNax97** [comment]
Hey there!
I'm going through the process of moving GithubForUnity to a package, for personal use. I would like to commit it when it's ready, but I have a few questions:

1- Would com.github.unity be the right package name? 
2- Should the UPM version live along with the Assets folder version? Or may it become a replacement going forward?
3- I have modified ExtensionLoader to support loading from packages folder, but the logic for it is currently driven by a const. Is this fine or should it be sorted at runtime?
4- Is there any potential issue I should look into?

**Comment by shana** [comment]
@JoNax97 Hey! This work is already underway at https://github.com/Unity-Technologies/Git-for-Unity, and I'm planning on porting that back here this week. If you want to try it out, the master branch over there is already usable as a package, you can try the sample project in the `UnityProject` folder to see how it works.

**Comment by shana** [comment]
https://github.com/github-for-unity/Unity/pull/1070 has all the changes needed for this, early builds are available in https://ci.appveyor.com/project/shana/git-for-unity

**Comment by shana** [comment]
This project is not maintained anymore. The replacement is Git for Unity, at https://github.com/spoiledcat/git-for-unity. If you have GitHub for Unity in your project, remove it first and then install the [Git for Unity](https://github.com/spoiledcat/git-for-unity) package, see the README in the link for instructions.
