### ISSUE TITLE
Implement Gitflow

### ISSUE THREAD

**Issue by SilverbackKarthik** [github-for-unity/Unity#966]
I/My organization uses Gitflow to manage our project workflow in git.
https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow

We are pushing our artists to use Github for Unity as it will help improve their workflow and they will have everything embedded inside the Unity IDE. But, since we use Gitflow, they can not initialize the same on their repository and use them as Gitflow Implementation is missing in the Plugin.

I have been trying to work on creating an extended UI for GitHub for Unity to have Gitflow related Editor, but I am constantly hit by other work and I thought I would post here so we could have people collaborate in creating the same.

**Comment by StanleyGoldman** [comment]
Hey @SilverbackKarthik thanks for checking our stuff out.

So I've read about Gitflow many times but i personally have never used it. I went and read a howto quickly to make sure I understand what you need...

If I understand your request and gitflow correctly, you are stuck in the current boat...
1. You could initialize with GitHub for Unity, but you would need to perform the gitflow initialization independently (if that is possible, I haven't looked it up)
2. You could initialize your gitflow on the command line, but you would be missing out on the initialization steps GitHub for Unity is performing.

Please let me know if I summed things up correctly.

So we have an issue in our backlog for a health check. When we initialize a project we do things like, make sure you are set to text serialization, make sure UnityYamlMerge is configured correctly, and a few other things. By possibly showing a warning message and a "Fix it" button of some kind, the health check would help users ensure these things are setup correctly, this would help users that are adding GitHub for Unity to an existing project.

If i'm not mistaken this would solve your issue as well. Your users would be able to perform a gitflow initialization on the command line, and then when they came back to Unity, they would get all the suggestions from GitHub for Unity.

Please let me know if that would solve your issue.

**Comment by FurkanKambay** [comment]
After initializing the repo with this plugin, just go to the command line and execute `git flow init`, answer the questions, (or use the `-d` flag to choose all defaults) and it's done.
`git flow init` only creates new branches and adds its configuration to `.git/config`. I don't think it has any conflict with this plugin.

It'd be nice to have a GUI for `git flow`, though. Buttons like "new feature", "new release", etc.

**Comment by SilverbackKarthik** [comment]
What I was talking about was the GUI for git flow.
