### ISSUE TITLE
GitHub for Unity caused VRTK to not work properly

### ISSUE THREAD

**Issue by tien** [github-for-unity/Unity#979]
This happened on Unity 2018.2.18f1 and the latest version of VRTK

Steps to reproduce:

1. Open VRTK project
2. Install Github for Unity
3. Launch VRTK example scene

**Expected behaviour:** Scene to work normally

**Actual behaviour:** Scene freezes until manually unload and reload oculus SDK setup. When the scene does not freeze VRTK pointer wouldn't work.

**Reproduces how often:** Always

**Comment by StanleyGoldman** [comment]
Hey @crazycat9x I tested out the combination of this asset from the store and our plugin. Nothing seemed to pop out at me as a conflict.

What makes you believe we have a conflict with this plugin?

**Comment by crazycat9x** [comment]
The store actually have an older version of VRTk, you need to clone the project on github and point unity to that repo.
