### ISSUE TITLE
Switching between branches sometimes clears out the Branches view

### ISSUE THREAD

**Issue by meaghanlewis** [github-for-unity/Unity#985]
### Description
I noticed that sometimes all the branches in my Branches view disappear. I first noticed this after getting an error when trying to pull from a branch that didn't have a remote ref and switching to another branch. When this happens, switching between tabs will fix the problem.

### Steps to Reproduce

1. Create a new branch
2. Checkout branch
3. Press `Pull`
4. Switch back to master branch
5. Switch between some more branches...

**Expected behavior:**
I can switch between branches and the branches in the view are always available.

**Actual behavior:** 
![screen shot 2018-12-13 at 1 34 09 pm](https://user-images.githubusercontent.com/10103121/49969931-a89f3100-fede-11e8-838a-418dda1094d1.png)

**Reproduces how often:** 50%

**Comment by StanleyGoldman** [comment]
@meaghanlewis are you able to reproduce this?
I'm trying and i'm not having much luck..
