### ISSUE TITLE
Including files in a GitHub Release

### ISSUE THREAD

**Issue by StanleyGoldman** [github-for-unity/Unity#993]
In https://github.com/github-for-unity/Unity/commit/1cfcaad438167a206ec8071b5563c5e3af9dd1f9#commitcomment-31822592 @Serkonda asks:

> What did you that the .unitypackage is placed under the 'Assets' section next to the source code?
If I include some files in a release they appear like normal text.

**Comment by StanleyGoldman** [comment]
Hi @Serkonda.

I am having trouble understanding your question.
Are you referring to the release on GitHub? https://github.com/github-for-unity/Unity/releases/tag/v1.2.0

Maybe this documentation would help: https://help.github.com/articles/creating-releases/

**Comment by Serkonda** [comment]
Yes I mean the release and already googled around in hope to find help but
the documentation doesn't say something about this particular thing.

Am Mi., 2. Jan. 2019, 22:31 hat Stanley Goldman <notifications@github.com>
geschrieben:

**Comment by StanleyGoldman** [comment]
I think the link I sent you shows it clearly...

> 7. If you'd like to include binary files along with your release, such as compiled programs, drag and drop or select files manually in the binaries box. 

![](https://help.github.com/assets/images/help/releases/releases_adding_binary.gif)

**Comment by Serkonda** [comment]
I know how to attach files, but these are just listed like normal text. But
at your release the attached .unitypackage is listed under the Assets
category next to the the source file download. That's what I want to
achieve.

Am Fr., 4. Jan. 2019, 00:37 hat Stanley Goldman <notifications@github.com>
geschrieben:
