### ISSUE TITLE
Hide token text when signing into GitHub Enterprise

### ISSUE THREAD

**Issue by meaghanlewis** [github-for-unity/Unity#994]
### Description

Mask the text typed for the token when signing into GitHub Enterprise.

### Steps to Reproduce

1. Select Sign in
2. Select GitHub Enterprise
3. Enter server address
4. Enter token

**Expected behavior:** [What you expect to happen]

The token is hidden like the password is hidden when signing in to GitHub.
<img width="305" alt="screen shot 2019-01-02 at 4 17 47 pm" src="https://user-images.githubusercontent.com/10103121/50618880-71eb8380-0eaa-11e9-96da-47003a8e8508.png">

**Actual behavior:** [What actually happens]

<img width="306" alt="screen shot 2019-01-02 at 4 18 11 pm" src="https://user-images.githubusercontent.com/10103121/50618884-757f0a80-0eaa-11e9-8887-8daf887fe29a.png">

**Comment by gsveitch** [comment]
I can't even get as far as the token field on enterprise sign in. When I hit Sign In after entering my company's GHEnterprise server address it returns "Forbidden". Anyone else run into this blocker? I feel like if I had a chance to enter a generated token then maybe it would work.
